### ISSUE TITLE
Groupfolder permissions error not handled correctly

### ISSUE THREAD

**Issue by hanserasmus** [nextcloud/groupfolders#579] opened 2019-08-27 13:22 UTC
When trying to edit the permissions for a specific group folder, a stack trace appears and the user cannot clearly see what is wrong.
![image](https://user-images.githubusercontent.com/24249616/63775054-da2a2200-c8de-11e9-9272-cd5a86e87fb5.png)
And running the command @juliushaertl suggested in the last reply in issue #561 also still an error:
![image](https://user-images.githubusercontent.com/24249616/63775164-13fb2880-c8df-11e9-9821-b12736272655.png)

**Comment by juliushaertl** [comment] 2019-08-27 13:26
Might be an issue with the file id not casted to an integer.

**Comment by guystreeter** [comment] 2021-11-02 23:37
Does this problem still exist? I was unable to reproduce it on Nextcloud 22.

**Comment by fschrempf** [comment] 2021-11-04 12:25
Closing as duplicate of #470.

**Closed** 2021-11-04 12:26 UTC
Labels: bug, 0. Needs triage, acl
