### ISSUE TITLE
Sharing permission in ACL is not accessible to all admin groups

### ISSUE THREAD

**Issue by amatteo78** [nextcloud/groupfolders#1344] opened 2021-03-04 21:33 UTC
Hello, I have Group Folder with link Group with 2 admins group. If one of this add some user for sharing only it can change this, other admin can only see but not change. 
I don't know if it bug or not, is there way for share manage permission between admin group ?

Thanks

M.

**Comment by tromlet** [comment] 2021-06-03 22:36
I may be having this same issue - I have a Group Folder, let's call it "Shipping", and while there are many users in the "Shipping" group, TWO of them are admins, but only ONE of them can share files from within.

**Comment by fschrempf** [comment] 2021-11-05 10:29
Closing as duplicate of #642.

**Closed by fschrempf** 2021-11-05 10:29 UTC
Labels: bug, 0. Needs triage, acl
