### ISSUE TITLE
Reverse order of file versions in group folders

### ISSUE THREAD

**Issue by natoponen** [nextcloud/groupfolders#2058] opened 2022-08-11 09:57 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create  any (docx/xlsx/pptx) file in group folder
2. Make several versions of file

### Expected behaviour
Versions are listed starting from latest version of file, like in Nextcloud outside of group folders.

### Actual behaviour
Versions are listed starting from the first version of file.

### Server configuration

**Nextcloud version:** 24.0.1

**Group folders version:** 12.0.1

**Where did you install Nextcloud from:** https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud

### Client configuration
**Browser:** Google Chrome 104.0.5112.80

**Comment by XueSheng-GIT** [comment] 2022-08-12 13:11
Duplicate of https://github.com/nextcloud/groupfolders/issues/1901

**Closed** 2022-08-12 13:35 UTC
Labels: bug, 0. Needs triage
