### ISSUE TITLE
Data in trashbin is kept longer than configured for trashbin app

### ISSUE THREAD

**Issue by hriekehof** [nextcloud/groupfolders#345] opened 2019-03-11 16:15 UTC
i configured the trash bin app in NC 15.0.4 like this `'trashbin_retention_obligation' => 'auto, 7',` 
I would assume that all files in the trashbin are than deleted after 7 days but it seems that they are kept for the standard 30 days.
Is this configuration maybe only true for file which are not in group folders ?

**Comment by hriekehof** [comment] 2019-04-15 14:33
Does no one else experience this problem ? I am affraid a little that my storage is getting slowly less and less since when i look into the trashbin with my admin account. Files deleted from group folders seems to stay there forever

**Comment by Madic-** [comment] 2019-05-31 09:07
I've the same problem.
Set 'trashbin_retention_obligation' => 'auto,1', but trash does not get cleared.
There is also no possibility to manage the trash bin of group folders

**Comment by ldesgrange** [comment] 2019-09-23 07:43
Same issue here, nextcloud 16.0.4, group_folders 4.1.0: `'trashbin_retention_obligation' => 'auto, 30'` files in personal folder are deleted after 30 days but in the trashbin I can see files from group folders more than 8 months old.

**Comment by expert-geeks** [comment] 2019-11-18 00:53
> Same issue here, nextcloud 16.0.4, group_folders 4.1.0: `'trashbin_retention_obligation' => 'auto, 30'` files in personal folder are deleted after 30 days but in the trashbin I can see files from group folders that are 8 months old.

I wrote a quick bash to delete files/folders older than n days.. This might be useful to you.

https://github.com/nextcloud/groupfolders/issues/464#issuecomment-554793564

**Comment by jedi-nz** [comment] 2020-02-05 08:12
Nextcloud 17.0.1 on Ubuntu 19.04

I have `'trashbin_retention_obligation' => '3,4',` in my config.php file which should keep files in the trash bin for at least 3 days and delete all files older than 4 days but I see many files in my trash bin over 4 days old.
I have my data directory set to an external zfs pool/dataset.

**Comment by Beeez** [comment] 2020-02-05 15:51
> Nextcloud 17.0.1 on Ubuntu 19.04
> 
> I have `'trashbin_retention_obligation' => '3,4',` in my config.php file which should keep files in the trash bin for at least 3 days and delete all files older than 4 days but I see many files in my trash bin over 4 days old.
> I have my data directory set to an external zfs pool/dataset.

This is basically the problem. The Groupfolders app does not obey any trash file retention policy and must be cleaned manually.

**Comment by mesiah1970-haydar** [comment] 2020-02-07 09:18
Yeah people,

to add my self as well to the trashbin bug train, I could only say please let's try to find a solution.
I tried to delete the deleted files from the /__groupfolders/trash/#somenumber#, but it still apears in the trashbin folder  as an "odd" file. I had to restore an then delete it again, so it was removed also from the users trashbin, yaaay. But this is not a solution at. 

I must make a little criticism if you allow me to do so. I believe a deleted file from the group folder should be deleted immediately and not be moved to the users trashbin. This could be a workaround for the first. A nice pop up warning before deletion should be fine. In this manner we would avoid to break nextclouds trashbin functionality through the groupfolder app. I guess this would be a good and fast workaround, until the problem get's really solved. Maybe there is some who agrees with me?

Thanks

Haydar

**Comment by hriekehof** [comment] 2020-02-07 10:14
I also would like to ask you what you think about a slight shift in the priorities ? In my opinion before working on something like this #750 and spent development time there, i think a working trashbin is way more important.

Please don't get me wrong here Nextcloud is an amazing project and all you guys do a great job in this project.

**Comment by mesiah1970-haydar** [comment] 2020-02-07 10:19
Sorry, I did not get you Hans, who do you address with your comment?

**Comment by hriekehof** [comment] 2020-02-07 10:37
Anyone who is actively working on the groupfolder app development

**Comment by mesiah1970-haydar** [comment] 2020-02-07 10:46
Yeah, this issue must have the highest priority and the groupfolders app should be integrated as a integral part of NC. I guess it is a very good app with a slightly touch;-) So please developers, just give a hand on it. My opinion just to direct delete the files from the groupfolder would be a good start and easy to implement I guess, of course with a little warning before deleting. I shouldn't be so difficult my opinion eh?

Many Thanks

Haydar

**Comment by Beeez** [comment] 2020-02-07 13:23
I agree with @mesiah1970-haydar That it might just be best to delete the file rather than putting it in the deleted items of a user who deleted it. How can you possibly track down the person who deleted a file out of a group folder. Better to just delete it right away, get the normal trash retention working.

**Comment by Greek64** [comment] 2020-02-07 13:39
> How can you possibly track down the person who deleted a file out of a group folder.

That is not the problem here. The specific user that deleted a file/folder is not tracked down.
When a "shared" file/folder is deleted, the file/folder is moved to the trashbin of ALL users who have read access to it (this is easy to determine). This allows all readers to restore the file/folder.

**Comment by mesiah1970-haydar** [comment] 2020-02-07 13:56
Yeah, I forgot to mention it, maybe some of yours have the retention app enabled, so if a lousy users is not deleting the files by himself, the app would move it to the trashbin. And this leads us again to the trashbin issue again. mmmm maybe my thought was not that simple. 

So we have then one more player on board: The retention app. So it would be a nice option to have the retention app directly delete the files after a certain time e.g. 30 days, instead of moving the files based on their tags to the trashbin. Am I wrong?

Haydar

**Comment by mesiah1970-haydar** [comment] 2020-02-10 08:05
Hello and Good morning,

the groupfolders trashbin should expire. Maybe we can achieve this with a extra option in the group folder app, or create a new groupfolder occ command. It could be something simple, which could help people to get out of the trashbin mess. Please help us! A groupfolder app without a correctly working trashbin is just frustrating

Rgds

Haydar

**Comment by mesiah1970-haydar** [comment] 2020-02-10 12:46
well folks, since there is no response regarding the groupfolder trashbin, I guess this issue is going to take a long time or will not implemented. At least I would expect a response regarding how to handle this issue. really frustrating

Haydar

**Comment by mesiah1970-haydar** [comment] 2020-02-11 07:55
Hello,

ok let's try in dutch:

Ja, dit probleem moet de hoogste prioriteit hebben en de groepsfolders-app moet worden geïntegreerd als een integraal onderdeel van NC. Ik denk dat het een zeer goede app is met een lichte aanraking ;-) Dus ontwikkelaars, geef het gewoon een handje. Mijn mening om alleen de bestanden rechtstreeks uit de groupfolders te verwijderen zou een goed begin zijn en gemakkelijk te implementeren denk ik, natuurlijk met een kleine waarschuwing voor het verwijderen. Naar mijn mening zou het niet zo moeilijk moeten zijn, hè?

Erg bedankt

Haydar

**Comment by kokotko1337** [comment] 2020-02-12 10:27
@mesiah1970-haydar you can pay for support and just make a ticket on their support ...

**Comment by mesiah1970-haydar** [comment] 2020-02-12 11:20
..and if you can explain me where to apply and who to ask etc..that would be just nice my friend.

awaiting your precious information.

Haydar

**Comment by kokotko1337** [comment] 2020-02-12 11:36
@mesiah1970-haydar here you go https://nextcloud.com/enterprise/buy/

**Comment by mesiah1970-haydar** [comment] 2020-02-12 11:45
...please do not misunderstand me, but I don't want to buy a subscription, just want to use the community version of NC. I "just" need a trashbin feature to be implemented. So I guess in your developer jargon it's called a "bounty"? Is that possible?

**Comment by kokotko1337** [comment] 2020-02-12 13:05
@mesiah1970-haydar sorry i dont need this type of communication

**Comment by mesiah1970-haydar** [comment] 2020-02-12 13:21
What is wrong on that my friend, you're confusing me??? It was just a simple question about who would be ready to develop such a feature. If I scratched on the surface, I'm terribly sorry. Anyhow, you don't need to comment, if you're bothered. Thanks anway

**Comment by feutl** [comment] 2020-02-26 14:34
Lets just link the two tickets, basically talking about the same.

https://github.com/nextcloud/groupfolders/issues/464

**Comment by mesiah1970-haydar** [comment] 2020-04-22 07:59
@feutl how do you do that at github;-)

**Comment by feutl** [comment] 2020-04-22 11:41
@mesiah1970-haydar I dont know what exactly you refer to, but linking the tickets just means posting the ticket link into the comments and this creates a "referenced by" information on the ticket linked inside the comment.
This should allow to find tickets which are related to each other.

**Comment by mesiah1970-haydar** [comment] 2020-04-22 11:43
Ahh cool, nice to know. Thanks

**Comment by Beeez** [comment] 2020-05-06 19:24
What would it take to get a fix out there for this? It really seems like you would need indefinite storage if you have a group folder that you frequently delete from. If Group Folders can have configurable storage quotas, its hard to enforce that when the storage balloons because it will hold those files forever instead of obeying retention. 

Is this something that would need to be fixed in the GroupFolder app project itself, or is this a fix that would need to be made as part of the base Nextcloud app files_trashbin?

**Comment by ZeikoFr** [comment] 2020-11-06 15:05
Hi,

Since the command `sudo -u www-data php /var/www/nextcloud/occ groupfolders:trashbin:cleanup` is now present in nextcloud ( https://github.com/nextcloud/groupfolders/issues/464 )

Can we hope for a fix to this issue ?

I had the problem with my cloud where about 150Gb of groupfolder files where in the trashbin and not deleted because groupfolder does not take in count the `'trashbin_retention_obligation'` parameter

Thx

**Comment by jonasgarstick** [comment] 2020-11-17 17:56
You can check the implementation progress here: https://github.com/nextcloud/groupfolders/pull/991#issuecomment-729093708

**Comment by pierreozoux** [comment] 2021-03-14 21:03
Duplicate of #930

**Closed by pierreozoux** 2021-03-14 21:03 UTC
Labels: 0. Needs triage
