### ISSUE TITLE
Transfer ownership of group folder to a user

### ISSUE THREAD

**Issue by unteem** [nextcloud/groupfolders#2006] opened 2022-05-24 13:14 UTC
I want to be able to transfer a group folder to a normal user

Meaning:
- Files ownership should be transferred to the user
- All shares should be kept as is

**Describe the solution you'd like**
I already managed to do it with sql queries which look llike this:

```
update filecache
set
	path = 'files/IndieHosters/liiibre',
	name = 'liiibre',
	parent = 127
where
  storage = 2 and path = '__groupfolders/2';

update filecache
set 
	path = replace(path, '__groupfolders/2', 'files/IndieHosters/liiibre')
where
  storage = 2 and path like '__groupfolders/2%';

update filecache
set 
	path_hash = md5(path),
	storage = 1224
where
  storage = 2 and path like 'files/IndieHosters/liiibre%';
```

This has been working for us. 

I would like to implement it in this app so the community can benefit from it. 

Would it be reasonable to make a command that executes those sql queries ? Would it be merged if I make a PR ?

**Comment by provokateurin** [comment] 2024-09-17 11:43
> Would it be reasonable to make a command that executes those sql queries ? Would it be merged if I make a PR ?

Yes, although I think it makes more sense to add it to the admin settings than to have a command for it.

**Comment by provokateurin** [comment] 2024-09-17 17:18
Duplicate of https://github.com/nextcloud/groupfolders/issues/612

**Closed by provokateurin** 2024-09-17 17:18 UTC
Labels: enhancement, question, 1. to develop, feature: occ
