### ISSUE TITLE
Renaming Errors without delete rights

### ISSUE THREAD

**Issue by the-matzup** [nextcloud/groupfolders#924] opened 2020-05-24 14:11 UTC
Error when renaming if the "delete" permission is missing. (If the permission to delete is allowed, renaming will work.)
![Bildschirmfoto 2020-05-24 um 16 08 01](https://user-images.githubusercontent.com/47818886/82756169-c4e41480-9dd8-11ea-9697-8f79e102a926.png)

Renaming is allowed in the menu. The error occurs only when renaming is actually to be carried out.
![Bildschirmfoto 2020-05-24 um 16 00 05](https://user-images.githubusercontent.com/47818886/82756185-e47b3d00-9dd8-11ea-9ace-52a697c3815e.png)

![Bildschirmfoto 2020-05-24 um 16 11 02](https://user-images.githubusercontent.com/47818886/82756229-31f7aa00-9dd9-11ea-8bb5-71b9e1409189.png)

NC log entry for the error:

`{"reqId":"Xsp@lc1c4Az6edjI5LttcgAAAI8","level":4,"time":"2020-05-24T14:03:01+00:00","remoteAddr":"79.xxx.xxx.xx","user":"zeig.8b","app":"webdav","method":"MOVE","url":"/remote.php/dav/files/zeig.8b/Klassen-%20und%20Gruppen/Klasse%208b/%23%20Abgabeordner/Test.md","message":{"Exception":"Sabre\\DAV\\Exception","Message":"Failed to rename /Klassen- und Gruppen/Klasse 8b/# Abgabeordner/Test.md to /Klassen- und Gruppen/Klasse 8b/# Abgabeordner/Testn.md","Code":0,"Trace":[{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php","line":151,"function":"setName","class":"OCA\\DAV\\Connector\\Sabre\\Node","type":"->","args":["Testn.md"]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":642,"function":"move","class":"Sabre\\DAV\\Tree","type":"->","args":["files/zeig.8b/Klassen- und Gruppen/Klasse 8b/# Abgabeordner/Test.md","files/zeig.8b/Klassen- und Gruppen/Klasse 8b/# Abgabeordner/Testn.md"]},{"function":"httpMove","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://cloud.rkm.de/remote.php/dav/files/zeig.8b/Klassen-%20und%20Gruppen/Klasse%208b/%23%20Abgabeordner/Test.md","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpMove"],[{"absoluteUrl":"https://cloud.rkm.de/remote.php/dav/files/zeig.8b/Klassen-%20und%20Gruppen/Klasse%208b/%23%20Abgabeordner/Test.md","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:MOVE",[{"absoluteUrl":"https://cloud.rkm.de/remote.php/dav/files/zeig.8b/Klassen-%20und%20Gruppen/Klasse%208b/%23%20Abgabeordner/Test.md","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://cloud.rkm.de/remote.php/dav/files/zeig.8b/Klassen-%20und%20Gruppen/Klasse%208b/%23%20Abgabeordner/Test.md","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":319,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":165,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/apps/dav/lib/Connector/Sabre/Node.php","Line":144,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0","version":"18.0.4.2","id":"7r5a7ea365d3d"}`

**Comment by CarlSchwan** [comment] 2021-11-19 14:26
Duplicate of #859

**Closed by CarlSchwan** 2021-11-19 14:26 UTC
Labels: bug, 0. Needs triage
