### ISSUE TITLE
Permissions cascade in unexpected manner

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/groupfolders#69] opened 2017-10-09 07:11 UTC
When you create group folder "A" and grant full permission to group X, with read only permissions granted to group Y, a member of both groups gets only the more limited permission set. Expected behaviour is that the user gets the highest permissions granted.

Use case scenario:

Jane is in the group “all staff” (as a member of staff) who is also in the “health and safety admin” group (and others, but that one’s particularly key).

You create an H&S group folder that is shared with “all staff” as read only, and grant “health and safety admin” full permissions; the intent is to ensure all staff get access to the H&S materials, but cannot change or delete them.

When Jane doesn’t get write permissions, this means you can only create groups that do not overlap; this makes administration of groups difficult - and probably doesn't reflect the nature of most organisations, where people are often in more than one group operationally.

**Comment by gamag** [comment] 2017-10-12 14:58
I can confirm most of this, only for me it looks like it takes not even the lowest permissions, but the permissions of the group that was created last or of the one that is last in some internal order.

**Comment by putt1ck** [comment] 2017-10-16 17:14
Agreed, with further testing we find the permissions that get applied is related to some sort of internal ordering, possibly but not certainly the order in which the user was added to the groups; so this meant that as the initial testing was with an "everyone" group pulled from LDAP, and therefore everyone got added to it immediately they were created on NC, this group always "won" i.e. whatever permission were assigned to this group Jane got, and the permissions granted to the sub-group weren't applied.

**Comment by icewind1991** [comment] 2017-11-08 13:13
Permissions are now merged if a user has access to a folder trough multiple groups (7d837882e50279416ae8ac361dd759639055da72)

**Closed by icewind1991** 2017-11-08 13:13 UTC
Labels: bug

**Comment by HarryK58** [comment] 2017-11-13 14:52
When is the update available? The last version available in the store (V 1.1.0) is still from July
