### ISSUE TITLE
l10n: There are no text strings in Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/groupfolders#2166] opened 2022-10-30 20:30 UTC
**1**. There are no text strings in the file [App.tsx](https://github.com/nextcloud/groupfolders/blob/master/src/settings/App.tsx) in Transifex. All text strings that are in the `<em>` tag are missing.

**2**. Is the word `groupfolders` spelled correctly? Shouldn't there be a `group folders`?

**Comment by CarlSchwan** [comment] 2022-11-21 11:04
Working fixed with #2190 and the second issues is a duplicate of #2131

**Closed by CarlSchwan** 2022-11-21 11:04 UTC
Labels: bug, 0. Needs triage

**Comment by Jerome-Herbinet** [comment] 2024-05-24 11:52
If I understand well, [this](https://github.com/nextcloud/groupfolders/pull/2190) was supposed to fix https://github.com/nextcloud/groupfolders/issues/2131, but in fact, it didn't.
