### ISSUE TITLE
15.1.0 → occ yields "OCA\Files_Versions\Versions\INeedSyncVersionBackend" not found in /path/to/cloud/apps/groupfolders/lib/Versions/VersionsBackend.php:46

### ISSUE THREAD

**Issue by nursoda** [nextcloud/groupfolders#2548] opened 2023-09-11 16:52 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. update to latest Groupfolders app 15.1.0
2. try to run occ after the update → this error:
<details><summary>"OCA\Files_Versions\Versions\INeedSyncVersionBackend" not found in /path/to/cloud/apps/groupfolders/lib/Versions/VersionsBackend.php:46</summary>

```
An unhandled exception has been thrown:
Error: Interface "OCA\Files_Versions\Versions\INeedSyncVersionBackend" not found in /path/to/cloud/apps/groupfolders/lib/Versions/VersionsBackend.php:46
Stack trace:
#0 /path/to/cloud/lib/composer/composer/ClassLoader.php(582): include()
#1 /path/to/cloud/lib/composer/composer/ClassLoader.php(433): Composer\Autoload\{closure}()
#2 /path/to/cloud/apps/groupfolders/lib/AppInfo/Application.php(138): Composer\Autoload\ClassLoader->loadClass()
#3 /path/to/cloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}()
#4 /path/to/cloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#5 /path/to/cloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#6 /path/to/cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(488): OC\AppFramework\Utility\SimpleContainer->query()
#7 /path/to/cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(466): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#8 /path/to/cloud/lib/private/AppFramework/Utility/SimpleContainer.php(97): OC\AppFramework\DependencyInjection\DIContainer->query()
#9 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#10 /path/to/cloud/lib/private/AppFramework/Utility/SimpleContainer.php(84): array_map()
#11 /path/to/cloud/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->buildClass()
#12 /path/to/cloud/lib/private/AppFramework/Utility/SimpleContainer.php(142): OC\AppFramework\Utility\SimpleContainer->resolve()
#13 /path/to/cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(494): OC\AppFramework\Utility\SimpleContainer->query()
#14 /path/to/cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(466): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#15 /path/to/cloud/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\AppFramework\DependencyInjection\DIContainer->query()
#16 /path/to/cloud/apps/groupfolders/lib/AppInfo/Application.php(158): OC\AppFramework\Utility\SimpleContainer->get()
#17 /path/to/cloud/lib/private/AppFramework/Utility/SimpleContainer.php(171): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}()
#18 /path/to/cloud/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#19 /path/to/cloud/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet()
#20 /path/to/cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(488): OC\AppFramework\Utility\SimpleContainer->query()
#21 /path/to/cloud/lib/private/ServerContainer.php(155): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#22 /path/to/cloud/lib/private/Console/Application.php(217): OC\ServerContainer->query()
#23 /path/to/cloud/lib/private/Console/Application.php(131): OC\Console\Application->loadCommandsFromInfoXml()
#24 /path/to/cloud/console.php(99): OC\Console\Application->loadCommands()
#25 /path/to/cloud/occ(11): require_once('...')
#26 {main}
```

</details>
Note: Web access and WebDAV interface seem to work fine!

### Expected behaviour
OCC should work

### Actual behaviour
OCC cannot be used without manual intervention

### Server configuration

**Operating system:** Arch Linux
**Web server:** NGINX
**Database:** MariaDB
**PHP version:** 8.2
**Nextcloud version:** 27.1.0 RC2
**Group folders version:** 15.1.0
**Updated from an older Nextcloud:** yes
**Where did you install Nextcloud from:** nextcloud.com
**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend:** none

#### Web server error log
*no errors*

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```json
{
  "reqId": "MpkAFHQeVclG2JcQoaH5",
  "level": 4,
  "time": "2023-09-11T18:45:45+02:00",
  "remoteAddr": "192.168.1.2",
  "user": "USER",
  "app": "no app in context",
  "method": "PROPFIND",
  "url": "/remote.php/dav/files/USER/",
  "message": "Could not boot files_versions: Interface \"OCA\\Files_Versions\\Versions\\INeedSyncVersionBackend\" not found",
  "userAgent": "Mozilla/5.0 (Linux) mirall/3.9.4git (Nextcloud, arch-6.5.2-arch1-1 ClientArchitecture: x86_64 OsArchitecture: x86_64)",
  "version": "27.0.2.1",
  "exception": {
    "Exception": "Error",
    "Message": "Interface \"OCA\\Files_Versions\\Versions\\INeedSyncVersionBackend\" not found",
    "Code": 0,
    "Trace": [
      {
        "file": "/path/to/cloud/lib/composer/composer/ClassLoader.php",
        "line": 582,
        "function": "include"
      },
      {
        "file": "/path/to/cloud/lib/composer/composer/ClassLoader.php",
        "line": 433,
        "function": "Composer\\Autoload\\{closure}",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/path/to/cloud/apps/groupfolders/lib/AppInfo/Application.php",
        "line": 138,
        "function": "loadClass",
        "class": "Composer\\Autoload\\ClassLoader",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 171,
        "function": "OCA\\GroupFolders\\AppInfo\\{closure}",
        "class": "OCA\\GroupFolders\\AppInfo\\Application",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/path/to/cloud/3rdparty/pimple/pimple/src/Pimple/Container.php",
        "line": 122,
        "function": "OC\\AppFramework\\Utility\\{closure}",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/path/to/cloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 138,
        "function": "offsetGet",
        "class": "Pimple\\Container",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php",
        "line": 488,
        "function": "query",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/lib/private/ServerContainer.php",
        "line": 155,
        "function": "queryNoFallback",
        "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/lib/private/AppFramework/DependencyInjection/DIContainer.php",
        "line": 469,
        "function": "query",
        "class": "OC\\ServerContainer",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/lib/private/AppFramework/Utility/SimpleContainer.php",
        "line": 65,
        "function": "query",
        "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/apps/files_versions/lib/AppInfo/Application.php",
        "line": 152,
        "function": "get",
        "class": "OC\\AppFramework\\Utility\\SimpleContainer",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/apps/files_versions/lib/AppInfo/Application.php",
        "line": 135,
        "function": "loadBackend",
        "class": "OCA\\Files_Versions\\AppInfo\\Application",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/lib/private/AppFramework/Bootstrap/FunctionInjector.php",
        "line": 45,
        "function": "registerVersionBackends",
        "class": "OCA\\Files_Versions\\AppInfo\\Application",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/lib/private/AppFramework/Bootstrap/BootContext.php",
        "line": 50,
        "function": "injectFn",
        "class": "OC\\AppFramework\\Bootstrap\\FunctionInjector",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/apps/files_versions/lib/AppInfo/Application.php",
        "line": 125,
        "function": "injectFn",
        "class": "OC\\AppFramework\\Bootstrap\\BootContext",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/lib/private/AppFramework/Bootstrap/Coordinator.php",
        "line": 200,
        "function": "boot",
        "class": "OCA\\Files_Versions\\AppInfo\\Application",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/lib/private/App/AppManager.php",
        "line": 437,
        "function": "bootApp",
        "class": "OC\\AppFramework\\Bootstrap\\Coordinator",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/lib/private/App/AppManager.php",
        "line": 216,
        "function": "loadApp",
        "class": "OC\\App\\AppManager",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/lib/private/legacy/OC_App.php",
        "line": 126,
        "function": "loadApps",
        "class": "OC\\App\\AppManager",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/apps/dav/lib/AppInfo/Application.php",
        "line": 209,
        "function": "loadApps",
        "class": "OC_App",
        "type": "::"
      },
      {
        "file": "/path/to/cloud/lib/private/AppFramework/Bootstrap/Coordinator.php",
        "line": 200,
        "function": "boot",
        "class": "OCA\\DAV\\AppInfo\\Application",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/lib/private/App/AppManager.php",
        "line": 437,
        "function": "bootApp",
        "class": "OC\\AppFramework\\Bootstrap\\Coordinator",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/lib/private/App/AppManager.php",
        "line": 216,
        "function": "loadApp",
        "class": "OC\\App\\AppManager",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/lib/private/legacy/OC_App.php",
        "line": 126,
        "function": "loadApps",
        "class": "OC\\App\\AppManager",
        "type": "->"
      },
      {
        "file": "/path/to/cloud/remote.php",
        "line": 157,
        "function": "loadApps",
        "class": "OC_App",
        "type": "::"
      }
    ],
    "File": "/path/to/cloud/apps/groupfolders/lib/Versions/VersionsBackend.php",
    "Line": 46,
    "message": "Could not boot files_versions: Interface \"OCA\\Files_Versions\\Versions\\INeedSyncVersionBackend\" not found",
    "exception": {},
    "CustomMessage": "Could not boot files_versions: Interface \"OCA\\Files_Versions\\Versions\\INeedSyncVersionBackend\" not found"
  }
}
```
</details>

#### Browser log
*irrelevant as not in browser*

**Comment by nursoda** [comment] 2023-09-11 17:14
```sh
sed -i -e "/INeedSyncVersionBackend;/d" -e "s/, INeedSyncVersionBackend//" apps/groupfolders/lib/Versions/VersionsBackend.php
```

temporarily solves the issue for NC27 and Groupfolders 15.1.0

**Comment by clorenz150** [comment] 2023-09-11 17:35
cron job is affected and doesn't run any more.

**Comment by claushviid** [comment] 2023-09-11 17:36
👍

**Comment by pov91** [comment] 2023-09-11 18:37
I have the same problem

**Comment by damienvancouver** [comment] 2023-09-11 19:00
I just did a fresh new install of NC27 stable with groupfolders latest yesterday and it was fine, so the problem appears to only happen during occ upgrade.

If you ran the command line updater to NC 27.02 and used the `--non-interactive` switch you can end up with what looks like a successful upgrade, but this bug actually just broke the upgrade halfway through, then --non-interactive disabled maintenance mode prematurely.

This then manifests to users as the "Files" app showing no files, just an empty page.

Meanwhile the log is spammed nonstop with this error: `Could not boot files_versions: Interface \"OCA\\Files_Versions\\Versions\\INeedSyncVersionBackend\" not found`.  

To fix this,  I tried the fix from https://github.com/nextcloud/groupfolders/issues/2548#issuecomment-1714282515 but that didn't help, still no files data.  In hindsight I probably needed to run an `occ upgrade` at this point and it would have worked.

Next I manually downgraded apps/groupfolders to 15.0.2.   Afterwards, when I reloaded a nextcloud page I found myself at an upgrade screen and so I continued on and it finished off the upgrade steps I was missing (including re-upgrading group folders to 15.1.0 again, but by then it was past where it had been stuck).  End result was everything working again.

**Comment by bpmartin20** [comment] 2023-09-12 03:58
Same problem. Temporary partial solution is to disable the GroupFolders app through the web interface (since OCC is dead). Hoping for a fix soon, as we rely on GroupFolders.

**Comment by LanDaze** [comment] 2023-09-12 03:59
Meet same issue with Nextcloud 27.0.2, Debian11, MariaDB and apache2.
Temporarily solved by manually commenting all "INeedSyncVersionBackend" in apps/groupfolders/lib/Versions/VersionsBackend.php.

Checked [https://github.com/nextcloud/server/tree/v27.0.2/apps/files_versions/lib/Versions](Nextcloud 27.0.2 server) and the INeedSyncVersionBackend is only available in the latest branch of Nextcloud server and is not present in version 27.0.2.  I think it's a version issue with the group folders in Nextcloud 27.0.2 that references the INeedSyncVersionBackend which is not available.

**Comment by level420** [comment] 2023-09-12 08:13
@nursoda after your hotfix (thank you for that!): are there any futher steps like occ upgrade which need to be performed afterwards?

**Comment by vasyugan** [comment] 2023-09-12 10:26
I know this isn't a place for general remarks. But still it feels like the group folders team should do less releases and more testing. This isn't the first time that a release broke _a lot_ for _a lot of people_ and did so reproducible. Today I upgraded 4 different NC instances with groupfolders enabled and the issue occurred on each of them. How can this slip through the cracks if you do some testing before pushing out a release?

**Comment by nursoda** [comment] 2023-09-12 10:34
yes, upgrade is required as there is is a migration for DB changes.

**Comment by WhoAmI0501** [comment] 2023-09-12 11:01
I am also seeing the same issue on 12 instances - 2 official docker installations, 10 Debian 12 + PHP 8.2 FPM + Caddy + MariaDB installations. For now, i downgraded Groupfolders on all instances.

The mentioned workarounds regarding to the missing DB upgrade are slightly unclear for me. In each situation, `occ upgrade` returns, that there is no pending upgrade. Is there something that i missed?

**Comment by stefanp2021** [comment] 2023-09-12 11:21
I'm facing the same issue on my Nextcloud LAMP Stack installation

**Comment by JensUweB** [comment] 2023-09-12 11:25
> 

For me this didn't work, because there is no "groupfolders" folder inside apps. For some reason, that folder is in custom_apps/ so I needed to  change the command acordingly.

I'm running nextcloud inside docker (nextcloud-fpm image).

**Comment by artonge** [comment] 2023-09-12 11:31
Two new versions just got released, one for 27.0.0, and one for 27.1.0, you can update to the one offered by your Nextcloud server.
Closing, feel free to reopen if this is not enough.

**Closed by artonge** 2023-09-12 11:31 UTC
Labels: bug, 0. Needs triage

**Comment by tf-webdev** [comment] 2023-09-12 12:15
@artonge Closed?! 
It is actually a recommended update in Nextcloud 27.0.2 (Group folders 15.1.0 from 11. September 2023 13:19 >=27.0.0,<28.0.0)

This is a serious bug, which produce heavy CPU load, logs and stops the cron job.

Can confirm the issue in the **app group folder version 15.10 with nextcloud VM 27.0.2 on Ubuntu 22.04.3 LTS**
and also that the hotfix from @nursoda works. Also thanks for that... saved my day.

CronJob was also affected and didn't work, like @clorenz150 mentioned.

**So, what works for me in following steps:**
1. SSH -> in CLI switch to root
2. change directory
`cd /var/www/nextcloud/`
3. use the hotfix from nursoda within this path
`sed -i -e "/INeedSyncVersionBackend;/d" -e "s/, INeedSyncVersionBackend//" apps/groupfolders/lib/Versions/VersionsBackend.php`
4. As clorenz150 mentioned the cron was also stop and not working (as showed in backend).
Just switched to AJAX in the settings (nextcloud administration settings), did a page reload and switched back to cron.

**Comment by reox** [comment] 2023-09-12 12:17
It seems to be fixed in 15.2.0 - at least for me that works again (I have applied the sed fix before though)

**Comment by stefanp2021** [comment] 2023-09-12 12:57
Thanks a lot for the quick fix! after the update it all worked again!

**Comment by manumitted** [comment] 2023-09-12 13:28
15.3.0 seems to have the problem for me.  I installed it on a test system with 27.1.0 RC2, which was running the modified version of 15.1.0.

It immediately had the log messages again, and I again removed the references to INeedSyncVersionBackend from VersionsBackend.php

```
[no app in context] Fatal: Error: Interface "OCA\Files_Versions\Versions\INeedSyncVersionBackend" not found at <<closure>>

 0. /var/www/nextcloud/lib/composer/composer/ClassLoader.php line 576
    include()
 1. /var/www/nextcloud/lib/composer/composer/ClassLoader.php line 427
    Composer\Autoload\{closure}("*** sensitive parameters replaced ***")
 2. /var/www/nextcloud/apps/groupfolders/lib/AppInfo/Application.php line 138
    Composer\Autoload\ClassLoader->loadClass()
 3. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 171
    OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php line 122
    OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensitive parameters replaced ***")
 5. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 138
    Pimple\Container->offsetGet()
 6. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 488
    OC\AppFramework\Utility\SimpleContainer->query()
 7. /var/www/nextcloud/lib/private/ServerContainer.php line 155
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
 8. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 469
    OC\ServerContainer->query()
 9. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 65
    OC\AppFramework\DependencyInjection\DIContainer->query()
10. /var/www/nextcloud/apps/files_versions/lib/AppInfo/Application.php line 152
    OC\AppFramework\Utility\SimpleContainer->get()
11. /var/www/nextcloud/apps/files_versions/lib/AppInfo/Application.php line 135
    OCA\Files_Versions\AppInfo\Application->loadBackend()
12. /var/www/nextcloud/lib/private/AppFramework/Bootstrap/FunctionInjector.php line 45
    OCA\Files_Versions\AppInfo\Application->registerVersionBackends()
13. /var/www/nextcloud/lib/private/AppFramework/Bootstrap/BootContext.php line 50
    OC\AppFramework\Bootstrap\FunctionInjector->injectFn()
14. /var/www/nextcloud/apps/files_versions/lib/AppInfo/Application.php line 125
    OC\AppFramework\Bootstrap\BootContext->injectFn()
15. /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php line 200
    OCA\Files_Versions\AppInfo\Application->boot()
16. /var/www/nextcloud/lib/private/App/AppManager.php line 437
    OC\AppFramework\Bootstrap\Coordinator->bootApp()
17. /var/www/nextcloud/lib/private/App/AppManager.php line 216
    OC\App\AppManager->loadApp()
18. /var/www/nextcloud/lib/private/legacy/OC_App.php line 126
    OC\App\AppManager->loadApps()
19. /var/www/nextcloud/apps/dav/lib/AppInfo/Application.php line 209
    OC_App::loadApps()
20. /var/www/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php line 200
    OCA\DAV\AppInfo\Application->boot()
21. /var/www/nextcloud/lib/private/App/AppManager.php line 437
    OC\AppFramework\Bootstrap\Coordinator->bootApp()
22. /var/www/nextcloud/lib/private/App/AppManager.php line 216
    OC\App\AppManager->loadApp()
23. /var/www/nextcloud/lib/private/legacy/OC_App.php line 126
    OC\App\AppManager->loadApps()
24. /var/www/nextcloud/lib/base.php line 1051
    OC_App::loadApps()
25. /var/www/nextcloud/index.php line 36
    OC::handleRequest()

GET /index.php/apps/logreader/poll?lastReqId=Bp1WnvMcYFxQYSxqv5qU
from 10.1.10.143 by dan.mahn at 2023-09-12T13:22:04+00:00
```

**Comment by artonge** [comment] 2023-09-12 13:37
> 15.3.0 seems to have the problem for me. I installed it on a test system with 27.1.0 RC2, which was running the modified version of 15.1.0.

Updating to 27.1.0 RC3 should make it work with 15.3.0 :)

**Comment by nursoda** [comment] 2023-09-12 15:24
I confirm that installing GF 15.2 over patched GF 15.1 works without issues.

GF 15.3 requires NC >= 27.1, so that's OK. Unfortunately, 27.1.RC2 does not meet that. So if you run beta channel, make sure to update NC prior to GF.

**Comment by support-criegerde** [comment] 2023-09-12 18:39
What works for me:

```
cd /var/www/nextcloud/
sed -i -e "/INeedSyncVersionBackend;/d" -e "s/, INeedSyncVersionBackend//" apps/groupfolders/lib/Versions/VersionsBackend.php
```

Switch to AJAX instead of cron and switch back to cron.

**Comment by nursoda** [comment] 2023-09-13 13:16
@chrissi55 I don't see that this is related to the GF update.
