### ISSUE TITLE
Crash when deleting file versions via occ groupfolders:expire

### ISSUE THREAD

**Issue by supr4s** [nextcloud/groupfolders#1858] opened 2022-01-05 11:35 UTC
Hi everyone,

I wanted to empty the "versions" folder of our Groups Folders to retrieve space disk but impossible, the command crashes. 

```
$ sudo -u nextcloud php /srv/nextcloud/www/occ groupfolders:expire

Expiring version in 'DIRECTION'
An unhandled exception has been thrown:
TypeError: Unsupported operand types: int & array in /srv/nextcloud/www/lib/private/Files/Cache/Wrapper/CachePermissionsMask.php:43
Stack trace:
#0 /srv/nextcloud/www/lib/private/Files/Cache/Wrapper/CacheWrapper.php(78): OC\Files\Cache\Wrapper\CachePermissionsMask->formatCacheEntry()
#1 /srv/nextcloud/www/apps/groupfolders/lib/Versions/VersionsBackend.php(170): OC\Files\Cache\Wrapper\CacheWrapper->get()
#2 [internal function]: OCA\GroupFolders\Versions\VersionsBackend->OCA\GroupFolders\Versions\{closure}()
#3 /srv/nextcloud/www/apps/groupfolders/lib/Versions/VersionsBackend.php(169): array_map()
#4 /srv/nextcloud/www/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php(63): OCA\GroupFolders\Versions\VersionsBackend->getAllVersionedFiles()
#5 /srv/nextcloud/www/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php(57): OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()
#6 /srv/nextcloud/www/apps/groupfolders/lib/Command/ExpireGroupVersions.php(59): OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
#7 /srv/nextcloud/www/3rdparty/symfony/console/Command/Command.php(255): OCA\GroupFolders\Command\ExpireGroupVersions->execute()
#8 /srv/nextcloud/www/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
#9 /srv/nextcloud/www/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#10 /srv/nextcloud/www/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /srv/nextcloud/www/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#12 /srv/nextcloud/www/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run()
#13 /srv/nextcloud/www/console.php(99): OC\Console\Application->run()
#14 /srv/nextcloud/www/occ(11): require_once('...')
#15 {main}#
```

I have no errors on other occ groupfolders commands such as : 

```
occ groupfolders:trashbin:cleanup
Are you sure you want to empty the trashbin of your group folders, this can not be undone (y/N).
```

I looked at the naming of the group folders, each of the folders is capitalized without any numbers, accents, special characters or anything else.

System information

Nextcloud version 22.2.3
Groups Folders version: 10.0.0
PHP : 8.0.12
MySQL : 10.3.31
Debian 10

We also have other Nextcloud servers configured in the same way and the problem is reproduced on all the others.

Thanks, have a nice day !

**Comment by fschrempf** [comment] 2022-01-05 12:32
This seems like a duplicate of #1724 and should be fixed in groupfolders v10.0.1. Please update and see if this solves your problem.

**Comment by CarlSchwan** [comment] 2022-01-05 16:45
Yeah this is exactly the same error. Please update and reopen this issue if it is still happening after the update

**Closed by CarlSchwan** 2022-01-05 16:45 UTC
Labels: bug, 0. Needs triage

**Comment by supr4s** [comment] 2022-01-06 15:51
Nice ! Indeed I did not see this issue, it's good for me. Thank you for your work
