### ISSUE TITLE
Access rights for users belonging to two groups

### ISSUE THREAD

**Issue by HarryK58** [nextcloud/groupfolders#74] opened 2017-11-11 13:55 UTC
I have a user X who belongs to group A and group B.
I create a group folder and give group A write permission, and group B only read permissions.
User X can then access the folder only with the rights of group B (read only rights).
Why he does not get the access rights of group A (write permissions)?
(Nextcloud 12.0.3  Group folders 1.1.0)

**Comment by icewind1991** [comment] 2017-11-13 14:22
Duplicate of https://github.com/nextcloud/groupfolders/issues/69

**Closed by icewind1991** 2017-11-13 14:22 UTC
