### ISSUE TITLE
add a new group folder in an existing external storage disk

### ISSUE THREAD

**Issue by jw1720** [nextcloud/groupfolders#2897] opened 2024-03-29 16:14 UTC
**Is your feature request related to a problem? Please describe.**

In the current implementation, a new group folder can be created only for a new folder in a nextcloud internal storage. 

**Describe the solution you'd like**

In my nextcloud instance, the nextcloud server has limited space. I use external storage for my main storage needs. So I'd like to be able to establish group folder using external storage and with an existing folder (such as a shared photo folder) 

**Describe alternatives you've considered**

Nextcloud also has External Storage solution. However, external storage has a userID as file path prefix for each user, so many apps will see duplicated files. I think it is a much cleaner solution to mount external storage as a shared group folder.

**Comment by BigBen2003** [comment] 2024-04-30 16:33
[English via Google Translate]
In order to be able to integrate external storage into Nextcloud, you can also mount the path "/data" to an external storage at the operating system level. Then Nextcloud treats the storage like internal storage.

[German]
Um in Nextcloud einen externen Speicher einbinden zu können, kann man auch auf Betriebssystem-Ebene den Pfad "/data" auf ein externe Speicher mounten. Dann wird der Speicher von Nextcloud wie ein interner Speicher behandelt.

**Comment by jw1720** [comment] 2024-05-01 14:46
Thanks for the suggestion. The Nextcloud /data folder contains some "system" data like previews. I like this to be an SSD based faster storage system. The external storage is HDD based, so I think it is better to not mount /data to slower HDD external storage.

**Comment by joshtrichards** [comment] 2024-09-11 23:34
> Thanks for the suggestion. The Nextcloud /data folder contains some "system" data like previews. I like this to be an SSD based faster storage system. The external storage is HDD based, so I think it is better to not mount /data to slower HDD external storage.

You can mount the storage to a more specific spot than `/data` to overcome this. e.g. `/data/__groupfolders` or even `/data/__groupfolders/<folder_id>`.

However, there is a feature request for more functionality, which is probably preferred for more complicated setups. But if you just want to move `__groupfolders` there you should not need to wait for it if you mount your drive/storage where want it in the OS.

Duplicate of #87

**Closed by joshtrichards** 2024-09-11 23:34 UTC
Labels: enhancement, 0. Needs triage
