### ISSUE TITLE
Groupfolders replaces a user folder with the same name

### ISSUE THREAD

**Issue by nils-schween** [nextcloud/groupfolders#1058] opened 2020-10-01 08:54 UTC
Hello everyone,

thanks for taking care of this very useful app. Some days ago, I ran into a "scary" issue: If a group folder has the same name as a folder owned by a user, the user folder is replaced with the group folder. 

Steps to reproduce the problem:

1. Log in as "User_Name" , create a folder with name "Folder_Name"
2. Put a testfile "Testfile_User.txt" into "Folder_Name"
3. Log in as an admin, create a group "Group_Name"
4. Add "User_Name" to the group "Group_Name"
5. Create a groupfolder with name "Folder_Name" (Settings -> Group Folders) and assign the "Group_Name" to the folder
6. Create a testfile "Testfile_Group.txt" in "Folder_Name"
7. Log in as "User_Name" and check the content of "Folder_Name" -> You will find the file "Testfile_Group.txt"  

If you take a look at the the data folder of your nextcloud instance and if you checkout the data of "User_Name", the file "Testfile_User.txt" is not actually replaced. But "User_Name" cannot access it anymore ( he thinks the orginal folder is replaced).

To me it seems, that there is misisng a check: Every time a user is added to a group, which owns group folders, it must be checked, if the user has folders with the same name. And the same has to be done, when creating a group folder.

We are using group folders 7.0.0
And nextcloud 19.0.3

Thank you very much,
Nils

**Comment by Commifreak** [comment] 2020-10-01 11:35
Duplicate of #1045 ?

**Comment by nils-schween** [comment] 2020-10-01 12:26
You are right, it's a duplicate. Thanks.

**Closed** 2021-01-22 14:54 UTC
