### ISSUE TITLE
NC 16 & Group folders 4: Can't move files or folders between different group folders

### ISSUE THREAD

**Issue by jpbraun** [nextcloud/groupfolders#429] opened 2019-05-12 12:21 UTC
It is not possible to move files or folders between different group folders ever if the group folders have the same permissions.

**Comment by MaxGitHubAccount** [comment] 2019-05-15 11:55
I am having the same issue moving files or folders from a non-group-folder to a folder.

I am also seeing an error in the nextcloud logs.

I am trying to move the file "test-log-for-git.txt" from the Folder "Dokumente" which is owned by my user and shared to another user to a group folder "Dokumente-Test" which is available to a group with both users and full access.

{"reqId":"mhSxc8r7L85w1KFp9GLs","level":4,"time":"2019-05-15T11:47:49+00:00","remoteAddr":"88.130.78.57","user":"max","app":"webdav","method":"MOVE","url":"/remote.php/dav/files/max/Dokumente/test-log-for-git.txt","message":{"Exception":"BadMethodCallException","Message":"path needs to be relative to the system wide data folder and point to a user specific file","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Encryption/Keys/Storage.php","line":347,"function":"getUidAndFilename","class":"OC\\Encryption\\Util","type":"->","args":["/__groupfolders/1/test-log-for-git.txt"]},{"file":"/var/www/nextcloud/lib/private/Encryption/Keys/Storage.php","line":298,"function":"getPathToKeys","class":"OC\\Encryption\\Keys\\Storage","type":"->","args":["/__groupfolders/1/test-log-for-git.txt"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php","line":988,"function":"copyKeys","class":"OC\\Encryption\\Keys\\Storage","type":"->","args":["/max//files/Dokumente/test-log-for-git.txt","/__groupfolders/1/test-log-for-git.txt"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php","line":734,"function":"copyKeys","class":"OC\\Files\\Storage\\Wrapper\\Encryption","type":"->","args":["/max//files/Dokumente/test-log-for-git.txt","/__groupfolders/1/test-log-for-git.txt"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php","line":621,"function":"copyBetweenStorage","class":"OC\\Files\\Storage\\Wrapper\\Encryption","type":"->","args":[{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"files/Dokumente/test-log-for-git.txt","/__groupfolders/1/test-log-for-git.txt",true,true]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":574,"function":"moveFromStorage","class":"OC\\Files\\Storage\\Wrapper\\Encryption","type":"->","args":[{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"files/Dokumente/test-log-for-git.txt","/__groupfolders/1/test-log-for-git.txt"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Jail.php","line":505,"function":"moveFromStorage","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":[{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"files/Dokumente/test-log-for-git.txt","/__groupfolders/1/test-log-for-git.txt"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Quota.php","line":198,"function":"moveFromStorage","class":"OC\\Files\\Storage\\Wrapper\\Jail","type":"->","args":[{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"files/Dokumente/test-log-for-git.txt","test-log-for-git.txt"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":574,"function":"moveFromStorage","class":"OC\\Files\\Storage\\Wrapper\\Quota","type":"->","args":[{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"files/Dokumente/test-log-for-git.txt","test-log-for-git.txt"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":574,"function":"moveFromStorage","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":[{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"files/Dokumente/test-log-for-git.txt","test-log-for-git.txt"]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":813,"function":"moveFromStorage","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":[{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"files/Dokumente/test-log-for-git.txt","test-log-for-git.txt"]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":440,"function":"rename","class":"OC\\Files\\View","type":"->","args":["/Dokumente/test-log-for-git.txt","/Dokumente-Test/test-log-for-git.txt"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":158,"function":"moveInto","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["test-log-for-git.txt","files/max/Dokumente/test-log-for-git.txt",{"__class__":"OCA\\DAV\\Connector\\Sabre\\File"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":642,"function":"move","class":"Sabre\\DAV\\Tree","type":"->","args":["files/max/Dokumente/test-log-for-git.txt","files/max/Dokumente-Test/test-log-for-git.txt"]},{"function":"httpMove","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://nc.madlung.eu/remote.php/dav/files/max/Dokumente/test-log-for-git.txt","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpMove"],[{"absoluteUrl":"https://nc.madlung.eu/remote.php/dav/files/max/Dokumente/test-log-for-git.txt","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:MOVE",[{"absoluteUrl":"https://nc.madlung.eu/remote.php/dav/files/max/Dokumente/test-log-for-git.txt","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://nc.madlung.eu/remote.php/dav/files/max/Dokumente/test-log-for-git.txt","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":301,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":163,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Encryption/Util.php","Line":236,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0","version":"15.0.7.0","id":"5cdbfc66816df"}

Same happens from the Nextcloud root directory of my user for the file "test-log-for-git2.txt" to the same directory "Dokumente-Test"

{"reqId":"frTGG6MRjSD9FFMXWmKT","level":4,"time":"2019-05-15T11:49:54+00:00","remoteAddr":"88.130.78.57","user":"max","app":"webdav","method":"MOVE","url":"/remote.php/dav/files/max/test-log-for-git2.txt","message":{"Exception":"BadMethodCallException","Message":"path needs to be relative to the system wide data folder and point to a user specific file","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Encryption/Keys/Storage.php","line":347,"function":"getUidAndFilename","class":"OC\\Encryption\\Util","type":"->","args":["/__groupfolders/1/test-log-for-git2.txt"]},{"file":"/var/www/nextcloud/lib/private/Encryption/Keys/Storage.php","line":298,"function":"getPathToKeys","class":"OC\\Encryption\\Keys\\Storage","type":"->","args":["/__groupfolders/1/test-log-for-git2.txt"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php","line":988,"function":"copyKeys","class":"OC\\Encryption\\Keys\\Storage","type":"->","args":["/max//files/test-log-for-git2.txt","/__groupfolders/1/test-log-for-git2.txt"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php","line":734,"function":"copyKeys","class":"OC\\Files\\Storage\\Wrapper\\Encryption","type":"->","args":["/max//files/test-log-for-git2.txt","/__groupfolders/1/test-log-for-git2.txt"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php","line":621,"function":"copyBetweenStorage","class":"OC\\Files\\Storage\\Wrapper\\Encryption","type":"->","args":[{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"files/test-log-for-git2.txt","/__groupfolders/1/test-log-for-git2.txt",true,true]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":574,"function":"moveFromStorage","class":"OC\\Files\\Storage\\Wrapper\\Encryption","type":"->","args":[{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"files/test-log-for-git2.txt","/__groupfolders/1/test-log-for-git2.txt"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Jail.php","line":505,"function":"moveFromStorage","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":[{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"files/test-log-for-git2.txt","/__groupfolders/1/test-log-for-git2.txt"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Quota.php","line":198,"function":"moveFromStorage","class":"OC\\Files\\Storage\\Wrapper\\Jail","type":"->","args":[{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"files/test-log-for-git2.txt","test-log-for-git2.txt"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":574,"function":"moveFromStorage","class":"OC\\Files\\Storage\\Wrapper\\Quota","type":"->","args":[{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"files/test-log-for-git2.txt","test-log-for-git2.txt"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":574,"function":"moveFromStorage","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":[{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"files/test-log-for-git2.txt","test-log-for-git2.txt"]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":813,"function":"moveFromStorage","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":[{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"files/test-log-for-git2.txt","test-log-for-git2.txt"]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":440,"function":"rename","class":"OC\\Files\\View","type":"->","args":["/test-log-for-git2.txt","/Dokumente-Test/test-log-for-git2.txt"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":158,"function":"moveInto","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["test-log-for-git2.txt","files/max/test-log-for-git2.txt",{"__class__":"OCA\\DAV\\Connector\\Sabre\\File"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":642,"function":"move","class":"Sabre\\DAV\\Tree","type":"->","args":["files/max/test-log-for-git2.txt","files/max/Dokumente-Test/test-log-for-git2.txt"]},{"function":"httpMove","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://nc.madlung.eu/remote.php/dav/files/max/test-log-for-git2.txt","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpMove"],[{"absoluteUrl":"https://nc.madlung.eu/remote.php/dav/files/max/test-log-for-git2.txt","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:MOVE",[{"absoluteUrl":"https://nc.madlung.eu/remote.php/dav/files/max/test-log-for-git2.txt","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://nc.madlung.eu/remote.php/dav/files/max/test-log-for-git2.txt","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":301,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":163,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Encryption/Util.php","Line":236,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0","version":"15.0.7.0","id":"5cdbfce2b74bc"}

I am aware that I could simply copy and paste the files via a client, but I want to keep the tags, versions etc of my files and because of this want to move the files.

Creating files in the group folder works, moving files via a desktop client delivers a 500 error in the client.

Nextcloud version Nextcloud 15.0.7
Group folder version  3.0.2
Server setup debian stretch as lxd container with apache, mariadb, redis

**Comment by icewind1991** [comment] 2019-05-17 11:13
@jpbraun do you have advanced permissions enabled for the folders?

**Comment by jpbraun** [comment] 2019-05-17 12:55
@icewind1991 Yes. Both folders have advanced permissions.

**Comment by jpbraun** [comment] 2019-05-19 15:58
It is probably another problem. I can't open or download the files. I tried deleting and changing the permissions and many more.

**Screenshot 1**
![2019-05-19_174913](https://user-images.githubusercontent.com/31374152/57984714-cdd03680-7a5e-11e9-9526-99b7dbce53a0.gif)

**Screenshot 2**
![image](https://user-images.githubusercontent.com/31374152/57984723-efc9b900-7a5e-11e9-8fea-5fb0f7171b69.png)

**Screenshot 3 (OnlyOffice)**
![image](https://user-images.githubusercontent.com/31374152/57984749-1f78c100-7a5f-11e9-9e9d-88232c501cce.png)

**Screenshot 4 (Download)**
![image](https://user-images.githubusercontent.com/31374152/57984763-3b7c6280-7a5f-11e9-83f7-9a5780910071.png)

**Screenshot 5 (Download folder)**
![image](https://user-images.githubusercontent.com/31374152/57984786-61a20280-7a5f-11e9-9f33-d2d5fba88c5b.png)

**Screenshot 6 (WebDav)**
![image](https://user-images.githubusercontent.com/31374152/57984796-88603900-7a5f-11e9-957f-4ffa48108afb.png)

**Comment by MaxGitHubAccount** [comment] 2019-05-21 11:17
I just tried the same for nextcloud 16 and group folders 4 on debian buster. I am getting the same error and cannot move files from non-group-folders to group folders. As jpbraun is describing a slightly different problem I am wondering if I should open a new issue.
Also I tried with and without advanced permissions and it won't work.

**Comment by langfingaz** [comment] 2019-05-23 22:19
Are group folders implemented through external storages? If yes, then maybe this has to do with _external storage support_. That's at least where I faced very similar problems moving files into and out of external folders: https://github.com/nextcloud/server/issues/15227

**Comment by jpbraun** [comment] 2019-05-24 05:23
Our group folders are not implemented through external storage.
I disabled the App "External storage support". Same problem as before.

**Comment by langfingaz** [comment] 2019-05-24 08:54
Hm ok, I just read that `folders will appear as external storage` in the README file of this groupfolders project (last bullet point under [Notes](https://github.com/nextcloud/groupfolders/blob/68b5cc0989f06ca6e030740ced516904afd69fe3/README.md#notes)), but I'm not a developer and don't know the actual implementation of how the group folders are handled in Nextcloud.

**Comment by MaxGitHubAccount** [comment] 2019-05-24 21:47
> Hm ok, I just read that `folders will appear as external storage` in the README file of this groupfolders project (last bullet point under [Notes](https://github.com/nextcloud/groupfolders/blob/68b5cc0989f06ca6e030740ced516904afd69fe3/README.md#notes)), but I'm not a developer and don't know the actual implementation of how the group folders are handled in Nextcloud.

Maybe that's because they have a special icon and are configured in the admin panel instead of creating them in the files - this is also the same for external storage.

**Comment by jkoopmann** [comment] 2019-11-07 09:19
Just hit the very same problem which unfortunately leaves this useless for me at the moment.... Any ideas on this so far?

**Comment by ElmarJongerius** [comment] 2019-11-25 09:07
Same issue. Group folders are really important for our use, but they started misbehaving.
Moving files (on Win7 / Win10) is problematic, as is renaming.

**Comment by zecrazytux** [comment] 2020-03-24 13:35
+1

**Comment by Vitriia** [comment] 2020-03-28 15:19
I have god the same issue on my side.
I have :
- Decrypted all my files
- Disabled encryption
- Disabled the encryption app

And after it's worked fine. I think there is an issue between the Encryption app and the Group Folder app

**Comment by pierreozoux** [comment] 2021-03-14 20:39
encryption is not yet supported #912 

and the move part is duplicate of #243

**Closed by pierreozoux** 2021-03-14 20:39 UTC
Labels: 0. Needs triage
