### ISSUE TITLE
Possible permission issue with folder in Group Folder for user who is member of multiple groups

### ISSUE THREAD

**Issue by vdietmar** [nextcloud/groupfolders#2280] opened 2023-02-26 15:19 UTC
### Steps to reproduce
1. Create user groups "User Group A" and "User Group B"
2. Create user "User AB" and as member of "User Group A" and "User Group B"
3. Create Group Folder and give "User Group A" and "User Group B" access with "Write/Share/Delete "rights
4. Create folder "See me" in this Group Folder
5. Set the advanced permissions of this folder to deny "Read" for "User Group A"
6. Login in as "User AB" and view Group Folder

### Expected behaviour
As "User AB" is a member of both groups "User Group A" and "User Group B", and "User Group B" still has inherited "Read" access to the folder "See me", it should be visible to "User AB".

### Actual behaviour
"User AB" does not see the folder "See me".

### Server configuration

**Operating system: Linux 5.4.0-137-generic x86_64

**Web server: unknown

**Database: mysql

**PHP version: 8.0.25

**Nextcloud version: 24.0.7 Enterprise

**Group folders version: 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install: fresh

**Where did you install Nextcloud from: managed Nextcloud at IONOS

**Are you using external storage, if yes which one: no

**Are you using encryption: no

**Are you using an external user-backend, if yes which one: no

### Client configuration
**Browser: Chrome

**Operating system: Mac OS

#### Web server error log
<details>
<summary>Web server error log</summary>
Not available b/c managed Nextcloud
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Not available b/c managed Nextcloud
</details>

#### Browser log
<details>
<summary>Browser log</summary>
Not relevant b/c no error is actually thrown
</details>

**Comment by koelle25** [comment] 2023-03-29 09:28
I think this would be desired behaviour. I don't remember if there is anything in the docs about permission precedence, but in e.g. NTFS it is like this:
> The hierarchy of precedence for the permissions can be summarized as follows, with the higher precedence permissions listed at the top of the list:
> - Explicit Deny
> - Explicit Allow
> - Inherited Deny
> - Inherited Allow

(see https://www.ntfs.com/ntfs-permissions-precedence.htm)

**Comment by vbier** [comment] 2023-11-17 08:57
If you look at the readme [here](https://github.com/nextcloud/groupfolders#setting-advanced-permissions), it says:
`If multiple configured advanced permissions for a single file or folder apply for a single user (such as when a user belongs to multiple groups), the "allow" permission will overwrite any "deny" permission.`

So this is no expected behaviour, but a bug. IMHO, any other behaviour makes a logical project and group setup impossible.

**Comment by vbier** [comment] 2023-11-20 09:19
I just saw that this has been worked on in https://github.com/nextcloud/groupfolders/pull/1654. Unfortunately progress has stopped.

**Comment by vbier** [comment] 2023-11-21 08:40
This issue is a duplicate of https://github.com/nextcloud/groupfolders/issues/1212 and can be closed.

**Comment by vbier** [comment] 2023-11-21 08:40
This issue is a duplicate of https://github.com/nextcloud/groupfolders/issues/1212 and can be closed.

**Closed** 2024-02-15 09:00 UTC
Labels: bug, 0. Needs triage
