### ISSUE TITLE
Show Move-Activity in groupfolder for other users

### ISSUE THREAD

**Issue by tbartholdi** [nextcloud/groupfolders#1853] opened 2022-01-04 10:28 UTC
In the activity app, we see changes of file/folders in group folders (rename, delete, ...). But we do not see when a folder is moved by another person in the groupfolder. The moves are only visible in my activities of the user that moved the folder.
Is this by design?

**Comment by fschrempf** [comment] 2022-01-04 12:04
This is a known issue. Closing as duplicate of #1018.

**Closed by fschrempf** 2022-01-04 12:04 UTC
