### ISSUE TITLE
Folder names changed on Nemo Folder Explorar with Davs

### ISSUE THREAD

**Issue by dantriano** [nextcloud/groupfolders#2576] opened 2023-09-26 11:06 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. On Nemo (Debian 12) create a Network Connection with Davs://
2. The connection works and for a moment you read the fodlers names correctly as it is in the Group Folders Admin
3. After one second the names automatically change to the names that the forlders have in the system Data/__groupfolders/[name] with usually is "1" "2" "3"....

### Expected behaviour
To show the folders as they were defined in "Group Folders" admin

### Actual behaviour
Instead it shows numbers 1, 2, 3...

### Server configuration

**Operating system:**
Debian 12 with Nemo as Files Explorer
**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
[Nextcloud Hub 5] (27.0.2)
**Group folders version:**
 15.2.0
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...

### Client configuration
**Browser:**

**Operating system:**

**Comment by XueSheng-GIT** [comment] 2023-09-28 10:41
Duplicate of https://github.com/nextcloud/groupfolders/issues/2527

**Comment by joshtrichards** [comment] 2023-09-30 15:53
@dantriano Please subscribe yourself to existing issue #2527

**Closed by joshtrichards** 2023-09-30 15:53 UTC
Labels: bug, 0. Needs triage

**Comment by svoeth** [comment] 2023-11-28 10:48
Seems to be a nemo issue.
Therefore it is moved here: https://github.com/linuxmint/nemo/issues/3331
