### ISSUE TITLE
Indicating icon if another groupfolder user shared file or subfolder

### ISSUE THREAD

**Issue by ElSi-DVT** [nextcloud/groupfolders#2764] opened 2024-01-17 11:14 UTC
**Is your feature request related to a problem? Please describe.**
The scenario is that two users are member of the same group and have access to a groupfolder.
_User-a_ shares a file within the groupfolder via link.

**Describe the solution you'd like**
_User-b_ is already able to see who has access to the file by clicking on the share option. In this case there is a note "shared by link by _user-a_".

But it would be very handy if there would be an indicator in the list view like _user-a_ has. That _user-b_ could see on the first look if a file or subfolder was shared by another user.

![grafik](https://github.com/nextcloud/groupfolders/assets/142410285/d3bb2237-5479-4c29-9431-8e7566793553)

**Comment by provokateurin** [comment] 2024-09-18 12:43
Duplicate of https://github.com/nextcloud/groupfolders/issues/264

**Closed by provokateurin** 2024-09-18 12:43 UTC
Labels: enhancement, 1. to develop
