### ISSUE TITLE
No ACL's in Sharedview of Groupfolder

### ISSUE THREAD

**Issue by mneuhaus1973** [nextcloud/groupfolders#2173] opened 2022-11-05 08:43 UTC
### Steps to reproduce
1. Create a group folder with extended permission
2. Go to the shared details
3. No extended permissions nor any group folder options seen

### Expected behaviour
I expect to see what is described in doc... advanced permissions in the share view details of the folder

### Actual behaviour
Don't see it there

### Server configuration

**Operating system:**
Debian 10.13
**Web server:**
Nginx
**Database:**
MariaDB
**PHP version:**
8.1
**Nextcloud version:** (see Nextcloud admin page)
25.0.1.1
**Group folders version:**
13.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh
**Where did you install Nextcloud from:**
nextcloud.com
**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
no
### Client configuration
**Browser:**
Safari/Chrome/Firefox
**Operating system:**
MacOS/iOS/Win

**Comment by fschrempf** [comment] 2022-11-05 08:46
@mneuhaus1973 Please check recent issues (also closed ones) for existing issues which cover your problem. Closing as duplicate of https://github.com/nextcloud/groupfolders/issues/2148.

**Closed by fschrempf** 2022-11-05 08:46 UTC
Labels: bug, 0. Needs triage
