### ISSUE TITLE
"advanced permission rules" are not available.

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/groupfolders#1062] opened 2020-10-05 09:59 UTC
I have created a group folder and given myself permission to manage advanced permissions. However, when I click details for any one subfolder or file, I only see the normal sharing dialogue. I see exactly the same after removing the advanced permission management permission from myself. Here you see what it looks like:
![image](https://user-images.githubusercontent.com/3313208/95066100-3aa2aa00-0702-11eb-83b2-51021a970b8f.png)

**Comment by AmatorPhasma** [comment] 2020-10-07 22:49
I have the same experience,

but only with Firefox (tested with version> = 70.0), works well with chromium based browsers like: Google Chrome (86.0.4240.75), Opera etc.

The workaround that works for me is to reload the "Files" page with SHIFT + F5.

I can reproduce this every time I've been on a settings page before.

**Comment by d-jsb** [comment] 2020-10-29 17:17
I see the same with Firefox 82 (64bit linux), switching to another app and back to files makes advanced permissions visible

**Comment by dominik34** [comment] 2020-11-02 16:55
Same Problem. Can't see them on Firefox but in Chrome all's working fine. Needs to be fixed!

**Comment by vasyugan** [comment] 2020-11-03 15:49
> Same Problem. Can't see them on Firefox but in Chrome all's working fine. Needs to be fixed!

Strange. I see exactly the same in Chrome as in Firefox.

**Comment by dominik34** [comment] 2020-11-03 16:39
Hopefully some more information would help.....
I'm using:
NextCloudPi version:  1.31.0
Nextcloud version: 19.0.4.2
Group-Folders: 7.1.0
PHP: v. 7.3.19
MySQL: v. 10.3.25

Maybe someone is using a same version and has the same bug so we could decrease the problem radius...
![Bildschirmfoto von 2020-11-02 17-13-42](https://user-images.githubusercontent.com/47363069/98014105-8167ea80-1dfb-11eb-9e95-f323755f86fe.png)

**Comment by vasyugan** [comment] 2020-11-03 16:46
> Maybe someone is using a same version and has the same bug so we could decrease the problem radius...
 This seems to be a different bug in addition. The "Zu einem Projekt hinzufügen" is something distinct from the "Advanced permissions rules" that you also seem to be lacking btw.

**Comment by dominik34** [comment] 2020-11-17 16:17
Oh I haven't noticed that yet. That's right. But only the writing is different. The functions are the same in both browsers....

**Comment by vasyugan** [comment] 2020-11-19 09:54
> Oh I haven't noticed that yet. That's right. But only the writing is different. The functions are the same in both browsers....

Oh, my mistake. I didn't notice that in the Chrome screenshot, it additionally says "Erweiterte Berechtigungsregel hinzufügen"

**Comment by vasyugan** [comment] 2020-11-19 09:59
Now I also see it on firefox. Hope this persists @dominik34

**Comment by dominik34** [comment] 2020-11-27 14:01
> Now I also see it on firefox. Hope this persists @dominik34

Yes, now I can see it too. The Problem is solved:
Firefox:
![Bildschirmfoto vom 2020-11-27 15-00-11](https://user-images.githubusercontent.com/47363069/100456885-5488b980-30c1-11eb-831b-c489d3bc365f.png)
 Thank you.

**Comment by fschrempf** [comment] 2021-01-04 14:50
I don't think this is solved, see #894.

**Comment by juliushaertl** [comment] 2021-01-05 10:38
Repoened https://github.com/nextcloud/groupfolders/issues/894 and closing this one as a dupliate

**Closed by juliushaertl** 2021-01-05 10:38 UTC
