### ISSUE TITLE
After storage failure group folders receive a new fileid and loose all metadata

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/groupfolders#2577] opened 2023-09-27 13:27 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Run a cluster of 4 Nextcloud app servers with data directory residing on an NFS storage
2. disconnect the network from the NFS storage
3. reconnect the network
4. Files in groupfolders receive a new fileid and loose all tags, shares and other metadata

### Expected behaviour
Once the storage comes back the files should still have the same fileids so metadata can be associated with them

### Actual behaviour
Almost all files in groupfolders get assigned a new `fileid`. Group folders trash is not affected.

### Server configuration

Latest Nextcloud 23 Enterprise cluster of 4 application servers, nfs storage cluster

Further details including logs can be found in the corresponding support ticket.

**Comment by solracsf** [comment] 2023-10-02 13:26
Related to https://github.com/nextcloud/groupfolders/issues/1468

**Comment by provokateurin** [comment] 2024-09-17 18:31
Duplicate of https://github.com/nextcloud/groupfolders/issues/1468

**Closed by provokateurin** 2024-09-17 18:31 UTC
Labels: bug, 0. Needs triage
