### ISSUE TITLE
NC 14/15/16: Opening or adding an OnlyOffice Document within a group folder doesn't work.

### ISSUE THREAD

**Issue by jpbraun** [nextcloud/groupfolders#413] opened 2019-05-02 13:40 UTC
Nextcloud 14, 15, 16:
Opening or adding an OnlyOffice Document within a group folder doesn't work.

![Screenshot 1](https://user-images.githubusercontent.com/31374152/57079401-8d4b8b80-6cf0-11e9-9eca-7df1cd3cd0b1.gif)

![Screenshot 2](https://user-images.githubusercontent.com/31374152/57079400-8d4b8b80-6cf0-11e9-8af7-59a9de80a4d9.gif)

**Comment by puzich** [comment] 2019-05-03 06:20
#411

**Comment by icewind1991** [comment] 2019-05-06 16:36
Closing as duplicate of #411

**Closed by icewind1991** 2019-05-06 16:36 UTC
