### ISSUE TITLE
NC18.0.3 - Can't create group folder (v6.0.5) in admin panel with MacOSX Catalina Safari Browser

### ISSUE THREAD

**Issue by inet-cologne** [nextcloud/groupfolders#862] opened 2020-04-09 20:24 UTC
Nextcloud 18.0.3
Group Folder 6.0.5 --> in general a great app!!
MacOSX Catalina 10.15.4
Version 13.1 (15609.1.20.111.8), Javascript enabled.

New Installation of Nextcloud and the app group folder. *In admin panel if I enter an folder name and click on "create", nothing happens.*

In Chrome- and Firefox-Browser everything's fine.

Am I missing something?

**Comment by bpcurse** [comment] 2020-05-12 12:55
Same issue using Firefox 76.0 (on manjaro linux), but it seems to occur randomly.

Tried two times to create a groupfolder on FF76, didn't work (as described by inet-cologne). Then I tried to use chromium and succeeded. Afterwards the next test with FF76 suddenly worked as well. The next didn't...

In the cases when it doesn't work this error message is thrown, but only sometimes:
`Error while sending QUERY packet. PID=23079 at /www/htdocs/*********/cloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php#88`

The server responses are very slow at the moment, maybe a high server load is somehow involved here?

Nextcloud 18.0.4, Groupfolders 6.0.6
on shared hosting (all-inkl)

**Comment by Franky1** [comment] 2020-05-17 15:57
Nextcloud 18.0.4
App Group folders 6.0.6

I am trying to create a new group under “Group folders”. The page reloads after I enter a new folder name and click Create, but nothing happens, no new group folder appears. But this has worked before.

Tried it with Chrome - there it worked.
Did not work with Firefox.

Firefox 76.0.1 (64-Bit)
Google Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by Franky1** [comment] 2020-05-17 16:06
I have to add new insights:
It was the **Ghostery** Blocking Plugin in Firefox that somehow interferes. Don't know why...
After whitelisting my Nextcloud domain in Ghostery the folder creation worked again.

**Comment by charentonvolley** [comment] 2020-05-23 13:03
Same problem and I notice that is comes with an error: 
Refused to execute .../apps/groupfolders/build/settings.js?v=7c747943-36 as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.

**Comment by pierreozoux** [comment] 2021-03-14 18:00
I'll close as duplicate of #932

**Closed by pierreozoux** 2021-03-14 18:00 UTC
