### ISSUE TITLE
 Group Folder permission and Owner transfer issues

### ISSUE THREAD

**Issue by Fernien** [nextcloud/groupfolders#1908] opened 2022-02-25 08:56 UTC
### Steps to reproduce
1. Create group folder shared with a group
2. Add another Person to this group folder via the share menu
3. Didnt find a way to edit user rights with another user than the inviting person

### Expected behaviour
1. Folder owner and user who added another person should be able to edit the permissions. Group folder should behave like normal shared folder.
2. Group folder should be editable with other users so when the creator leaves the system doesnt brake.

### Actual behaviour
Only the person which added a user to a group folder via the share menu can edit these rights.

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
21.0.3

**Group folders version:**
9.0.4

**Comment by fschrempf** [comment] 2022-02-25 10:42
This seems like a duplicate of #642. Can you confirm?

**Comment by Fernien** [comment] 2022-02-25 11:50
> This seems like a duplicate of #642. Can you confirm?

Yea looks like it. Is there a fix for it?

**Comment by fschrempf** [comment] 2022-02-25 11:52
> Is there a fix for it?

No, I guess not.

**Comment by fschrempf** [comment] 2022-02-25 11:53
Closing as duplicate of #642.

**Closed by fschrempf** 2022-02-25 11:53 UTC
Labels: bug, 0. Needs triage
