### ISSUE TITLE
Error while running background job `OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions`

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/groupfolders#2616] opened 2023-11-13 09:31 UTC
From production instance

```json
{
  "reqId": "CXXpFpSSX1JNMUIX7YAG",
  "level": 3,
  "time": "2023-11-13T09:25:16+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "files",
  "method": "",
  "url": "--",
  "message": "Backends provided no user object for ",
  "userAgent": "--",
  "version": "28.0.0.4",
  "exception": {
    "Exception": "OC\\User\\NoUserException",
    "Message": "Backends provided no user object",
    "Code": 0,
    "Trace": [
      {
        "function": "getUserFolder",
        "class": "OC\\Files\\Node\\Root",
        "type": "->",
        "args": [
          ""
        ]
      },
      {
        "file": "…/lib/private/Files/Node/LazyFolder.php",
        "line": 84,
        "function": "call_user_func_array",
        "args": [
          [
            [
              "OC\\Files\\Node\\Root"
            ],
            "getUserFolder"
          ],
          [
            ""
          ]
        ]
      },
      {
        "file": "…/lib/private/Files/Node/LazyRoot.php",
        "line": 52,
        "function": "__call",
        "class": "OC\\Files\\Node\\LazyFolder",
        "type": "->",
        "args": [
          "getUserFolder",
          [
            ""
          ]
        ]
      },
      {
        "file": "…/apps/groupfolders/lib/Versions/VersionsBackend.php",
        "line": 73,
        "function": "getUserFolder",
        "class": "OC\\Files\\Node\\LazyRoot",
        "type": "->",
        "args": [
          ""
        ]
      },
      {
        "file": "…/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php",
        "line": 72,
        "function": "getVersionsForFile",
        "class": "OCA\\GroupFolders\\Versions\\VersionsBackend",
        "type": "->",
        "args": [
          [
            "OC\\User\\User"
          ],
          [
            "OC\\Files\\FileInfo"
          ]
        ]
      },
      {
        "file": "…/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php",
        "line": 59,
        "function": "expireFolder",
        "class": "OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager",
        "type": "->",
        "args": [
          [
            1,
            "Support data",
            [
              [
                "Support",
                31,
                "group"
              ]
            ],
            -3,
            0,
            "And 1 more entries, set log level to debug to see all entries"
          ]
        ]
      },
      {
        "file": "…/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php",
        "line": 43,
        "function": "expireAll",
        "class": "OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager",
        "type": "->",
        "args": []
      },
      {
        "file": "…/lib/public/BackgroundJob/Job.php",
        "line": 81,
        "function": "run",
        "class": "OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions",
        "type": "->",
        "args": [
          null
        ]
      },
      {
        "file": "…/lib/public/BackgroundJob/TimedJob.php",
        "line": 102,
        "function": "start",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ]
        ]
      },
      {
        "file": "…/lib/public/BackgroundJob/TimedJob.php",
        "line": 92,
        "function": "start",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ]
        ]
      },
      {
        "file": "…/cron.php",
        "line": 152,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ],
          [
            "OC\\Log"
          ]
        ]
      }
    ],
    "File": "…/lib/private/Files/Node/Root.php",
    "Line": 365,
    "message": "Backends provided no user object for ",
    "exception": {},
    "CustomMessage": "Backends provided no user object for "
  }
}
{
  "reqId": "CXXpFpSSX1JNMUIX7YAG",
  "level": 3,
  "time": "2023-11-13T09:25:16+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "core",
  "method": "",
  "url": "--",
  "message": "Error while running background job (class: OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions, arguments: )",
  "userAgent": "--",
  "version": "28.0.0.4",
  "exception": {
    "Exception": "OC\\User\\NoUserException",
    "Message": "Backends provided no user object",
    "Code": 0,
    "Trace": [
      {
        "function": "getUserFolder",
        "class": "OC\\Files\\Node\\Root",
        "type": "->",
        "args": [
          ""
        ]
      },
      {
        "file": "…/lib/private/Files/Node/LazyFolder.php",
        "line": 84,
        "function": "call_user_func_array",
        "args": [
          [
            [
              "OC\\Files\\Node\\Root"
            ],
            "getUserFolder"
          ],
          [
            ""
          ]
        ]
      },
      {
        "file": "…/lib/private/Files/Node/LazyRoot.php",
        "line": 52,
        "function": "__call",
        "class": "OC\\Files\\Node\\LazyFolder",
        "type": "->",
        "args": [
          "getUserFolder",
          [
            ""
          ]
        ]
      },
      {
        "file": "…/apps/groupfolders/lib/Versions/VersionsBackend.php",
        "line": 73,
        "function": "getUserFolder",
        "class": "OC\\Files\\Node\\LazyRoot",
        "type": "->",
        "args": [
          ""
        ]
      },
      {
        "file": "…/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php",
        "line": 72,
        "function": "getVersionsForFile",
        "class": "OCA\\GroupFolders\\Versions\\VersionsBackend",
        "type": "->",
        "args": [
          [
            "OC\\User\\User"
          ],
          [
            "OC\\Files\\FileInfo"
          ]
        ]
      },
      {
        "file": "…/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php",
        "line": 59,
        "function": "expireFolder",
        "class": "OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager",
        "type": "->",
        "args": [
          [
            1,
            "Support data",
            [
              [
                "Support",
                31,
                "group"
              ]
            ],
            -3,
            0,
            "And 1 more entries, set log level to debug to see all entries"
          ]
        ]
      },
      {
        "file": "…/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php",
        "line": 43,
        "function": "expireAll",
        "class": "OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager",
        "type": "->",
        "args": []
      },
      {
        "file": "…/lib/public/BackgroundJob/Job.php",
        "line": 81,
        "function": "run",
        "class": "OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions",
        "type": "->",
        "args": [
          null
        ]
      },
      {
        "file": "…/lib/public/BackgroundJob/TimedJob.php",
        "line": 102,
        "function": "start",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ]
        ]
      },
      {
        "file": "…/lib/public/BackgroundJob/TimedJob.php",
        "line": 92,
        "function": "start",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ]
        ]
      },
      {
        "file": "…/cron.php",
        "line": 152,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ],
          [
            "OC\\Log"
          ]
        ]
      }
    ],
    "File": "…/lib/private/Files/Node/Root.php",
    "Line": 365,
    "message": "Error while running background job (class: OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions, arguments: )",
    "exception": {},
    "CustomMessage": "Error while running background job (class: OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions, arguments: )"
  }
}
```

**Comment by vidlb** [comment] 2023-11-13 16:05
Duplicate of https://github.com/nextcloud/groupfolders/issues/2559

**Closed** 2023-11-27 14:47 UTC
Labels: bug, 1. to develop, feature: versions
