### ISSUE TITLE
Show access in 'others with access'

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/groupfolders#2522] opened 2023-08-19 17:21 UTC
### Steps to reproduce
1. Create Group-Folder
2. Share it to a group
3. Maybe share it to a second group

### Expected behaviour
In the Files app share tab, there is the section 'Others with access'. This one should show the groups, the folder is shared with.

### Actual behaviour
Nothing shown.

### Server configuration

**Nextcloud version:** 26.0.5
**Group folders version:** 14.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:** Updated since a while
**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

#### Nextcloud log (data/nextcloud.log)

```
Information | no app in context | Deprecated event type for \OCP\Collaboration\Resources::loadAdditionalScripts: null
```

#### Browser log
The corresponding request, when selecting 'others with access' returns no data:
`https://domain.de/ocs/v2.php/apps/files_sharing/api/v1/shares/inherited?format=json&path=%2FMaterial`
`{"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":[]}}`

**Comment by joshtrichards** [comment] 2024-09-11 17:40
Related: #975

**Comment by provokateurin** [comment] 2024-09-18 13:10
Duplicate of https://github.com/nextcloud/groupfolders/issues/975

**Closed by provokateurin** 2024-09-18 13:10 UTC
Labels: enhancement, 0. Needs triage, feature: sharing
