### ISSUE TITLE
Folder sync does not work

### ISSUE THREAD

**Issue by Luto73** [nextcloud/groupfolders#43] opened 2017-07-18 10:38 UTC
I just installed the groupfolders app and uploaded some files from computer A. Unfortunately computer B does not recognize that the folder files changed. This is vice versa if I upload files from computer B to the group folder. The are sent to the nextcloud server but not synced with other clients.

System specs:
OS: Debian 9
NC: 12.0.0
PHP: 7.0.20
Apache: 2.4.25
mariadb: 10.1.23

**Comment by icewind1991** [comment] 2017-07-18 12:44
Duplicate of https://github.com/nextcloud/groupfolders/issues/36, will be fixed with NC12.0.1

**Closed by icewind1991** 2017-07-18 12:44 UTC

**Comment by thfree** [comment] 2017-07-20 08:06
Are you sure that in 12.0.1? It says https://github.com/nextcloud/server/pull/5685 "Milestone Nextcloud 13"
