### ISSUE TITLE
Usage of inheriting permissions

### ISSUE THREAD

**Issue by jelle-e** [nextcloud/groupfolders#836] opened 2020-03-30 12:49 UTC
NC 18.03
GF 6.0.3
CONFIG: Rootfolder/Subfolder

Hi, I'm new to groupfolders and trying to configure it.
1) I had things working in version 18.0.1 and 6.0.1 with the following setup:
- Rootfolder in groupfolder settings for GROUP1: NO write/share/delete (to make the rootfolder read-only)
- Subfolder with advanced permissions for GROUP1 set to: ALLOW ALL permissions (to make the subfolder R+W)

Now, after the upgrade to 18.0.3 or 6.0.3 (don't know after which upgrade the problem exactly started) the permissions stopped working. Suddenly the Subfolder wasn't writable anymore by GROUP1.

2) Now, the fix was to:
- Set Write+Delete in the Rootfolder settings for GROUP1
- Add Advanced Permissions to the Rootfolder; set to Read-only permissions for GROUP1. (to make the Rootfolder read-only again)

Now, I'm wondering what should be the correct setup? Should it work as set up in 1 or is 2 (the fix) the way it should work?

**Comment by awesome-manuel** [comment] 2020-04-07 10:58
It seems that the ACL flags stay in the database and are effective even if you disable advanced ACLs.

**Comment by Ludogo** [comment] 2020-04-08 11:30
Hello 
I have the same behavior with Group folder app V5.0.7 with NC 17. 
Is there something to do to enable right elevation for sub folders ? 
Thanks !

**Comment by provokateurin** [comment] 2024-09-18 12:35
Duplicate of https://github.com/nextcloud/groupfolders/issues/598

**Closed by provokateurin** 2024-09-18 12:35 UTC
Labels: question, feature: acl, needs review
