### ISSUE TITLE
Crashes Nextcloud 17 beta

### ISSUE THREAD

**Issue by cabaretboy** [nextcloud/groupfolders#565] opened 2019-08-18 11:23 UTC
As soon as the app is enabled on Nextcloud 17, the browser throws a 500 error. Deleting the app folder allows Nextcloud to work again.

**Comment by cellisten** [comment] 2019-08-20 05:56
I can confirm. Same issue here.

**Comment by cabaretboy** [comment] 2019-08-20 10:58
Thanks cellisten, I hadn't had the chance to dig through the error log yet :) But yes, I just checked, it's the same error :)

**Comment by pixelipo** [comment] 2019-08-22 11:53
I've found the culprit - there's a method in that class that was incompatible with a parent method. I've removed `int` manually on my local setup and it works as expected.

However, it seems like this has already been fixed in commit fa87c7164d01fa4732fcbbc4b498cb4b2926b42e but a version with that code hasn't been released yet. @icewind1991 @juliushaertl any ETA for new release of Group Folders app?

I guess this issue can be closed or do you prefer to keep open until patch is released?

**Comment by oneilonline** [comment] 2019-08-22 22:55
Any update to this? Our nextcloud is dead in the water without this working. None of the syncs can occur and no one can access files/folders. Thank you

**Comment by oneilonline** [comment] 2019-08-25 03:53
> @oneilonline Just a side note: I hope you're not running a productive instance on a Beta, are you?

No.

**Comment by wiswedel** [comment] 2019-08-26 13:56
CC @icewind1991 @juliushaertl

**Comment by juliushaertl** [comment] 2019-08-26 15:28
There is no 17 compatible release yet. See https://github.com/nextcloud/groupfolders/pull/572 for the progress

**Comment by tacruc** [comment] 2019-08-29 13:59
Connected to this issue, this app enabled on an 16 version will break the update process to nextcloud 17 beta 3. You click on update in the settings, which works, but the redirect will not lead to
![image](https://user-images.githubusercontent.com/402891/63946559-99b0dc80-ca75-11e9-980b-47d431952035.png)
but end up on a gray screen. Digging in the logs showed the error above. After disabling the app with occ I cloud continue with the update.

**Comment by Lars1963** [comment] 2019-08-29 16:16
> Connected to this issue, this app enabled on an 16 version will break the update process to nextcloud 17 beta 3. You click on update in the settings, which works, but the redirect will not lead to
> ![image](https://user-images.githubusercontent.com/402891/63946559-99b0dc80-ca75-11e9-980b-47d431952035.png)
> but end up on a gray screen. Digging in the logs showed the error above. After disabling the app with occ I cloud continue with the update.

I can confirm this on updating from 16.04 to 17.0 beta3 with activated groupfolder.

**Comment by wiswedel** [comment] 2019-08-29 19:38
@tacruc @Lars1963 Please see @juliushaertl 's comment above:

> There is no 17 compatible release yet. See #572 for the progress

**Comment by tacruc** [comment] 2019-08-29 19:43
Still an incompatible app should be disabled by the updater and not crash the update process, or?

**Comment by wiswedel** [comment] 2019-08-29 19:45
> Still an incompatible app should be disabled by the updater and not crash the update process, or?

Fair enough...CC @juliushaertl

**Comment by cabaretboy** [comment] 2019-08-29 23:47
Yes, that's why I posted the original bug.
Following the workaround shared by pixelipo [fa87c71](https://github.com/nextcloud/groupfolders/commit/fa87c7164d01fa4732fcbbc4b498cb4b2926b42e) has worked, and seems to work on beta 3 as well.
I haven't found any other compatibility issues since making those minor changes.

**Comment by juliushaertl** [comment] 2019-08-30 05:25
> Fair enough...CC @juliushaertl

Not sure what happened there, there is no 17 compatible release for groupfolders. Maybe the related class gets loaded to early so the disabling is never triggered

**Comment by Lars1963** [comment] 2019-08-30 06:51
> > > Still an incompatible app should be disabled by the updater and not crash the update process, or?
> > > Fair enough...CC @juliushaertl
> 
> Not sure what happened there, there is no 17 compatible release for groupfolders. Maybe the related class gets loaded to early so the disabling is never triggered
As I tried again with disabled and removed groupfolders prior to updating, the updateprocess was smoothly as ever. Other incompatibles were correct disabled during the updating. So it seems to be a groupfolder-problem.

**Comment by juliushaertl** [comment] 2019-08-30 07:25
I just have checked my update log from 16.0.3 to 17.0.0.2 and for me groupfolders has been disabled just fine:

```
{"reqId":"FUAGgFIzU5f9ucgm62hP","level":1,"time":"2019-08-20T09:17:59+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::incompatibleAppDisabled: Disabled incompatible app: groupfolders","userAgent":"--","version":"16.0.3.0"}
```

Any change you could check your logs if that also happened for you?

**Comment by Lars1963** [comment] 2019-08-30 07:40
> I just have checked my update log from 16.0.3 to 17.0.0.2 and for me groupfolders has been disabled just fine:
> 
> ```
> {"reqId":"FUAGgFIzU5f9ucgm62hP","level":1,"time":"2019-08-20T09:17:59+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::incompatibleAppDisabled: Disabled incompatible app: groupfolders","userAgent":"--","version":"16.0.3.0"}
> ```
> 
> Any change you could check your logs if that also happened for you?

I did a complete server-reset, so the logs are not there anymore. 😭 I just noticed, you used beta 2. So maybe a specific beta 3 problem? @tacruc also confirmed with beta 3.

**Comment by tacruc** [comment] 2019-08-30 08:04
Just checkt the log.
```
[PHP] Error: Declaration of OCA\GroupFolders\Versions\VersionsBackend::getVersionFile(OCP\IUser $user, OCP\Files\FileInfo $sourceFile, int $revision): OCP\Files\File must be compatible with OCA\Files_Versions\Versions\IVersionBackend::getVersionFile(OCP\IUser $user, OCP\Files\FileInfo $sourceFile, $revision): OCP\Files\File at /srv/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php#38

GET /
from 138.232.236.7 at 2019-08-29T15:42:39+02:00
```
Disabling the app
`2019-08-29 15:51:15 sudo -u wwwrun php7 occ app:disable groupfolders`
and I managed to start the updater at 
```
[updater] Info: \OC\Updater::maintenanceEnabled: Turned on maintenance mode

GET /core/ajax/update.php?requesttoken=cofjNHs%2Be%2FqB337pv56PUEpddlmKd1uu3Uho0D4mOvU%3D%3ACOioGyxRGpvImy7Q3vngAxAHBxe9Ij%2FirzJZlWoVDa0%3D
from 138.232.236.7 at 2019-08-29T15:53:26+02:00
```

So the error occurs after one clicks on update in the admin setting page and before one cloud start the updater in the web interface.

**Comment by juliushaertl** [comment] 2019-09-06 08:18
5.0.0 has been release for the upcoming Nextcloud 17

**Closed by juliushaertl** 2019-09-06 08:18 UTC
Labels: bug, high

**Comment by Terrox** [comment] 2019-11-16 20:04
I just had a white screen of death after upgrade from Nextcloud 16 to 17.0.1 before the Apps upgrade step. I removed the /app/groupfolders/ to continue after randomly finding this post matching some log errors. So this is a critical bug for upgraders.

**Comment by fsteinbauer** [comment] 2019-11-18 19:33
I also got this error on a production version. 

```PHP Fatal error:  Declaration of OCA\\GroupFolders\\Versions\\VersionsBackend::getVersionFile(OCP\\IUser $user, OCP\\Files\\FileInfo $sourceFile, int $revision): OCP\\Files\\File must be compatible with OCA\\Files_Versions\\Versions\\IVersionBackend::getVersionFile(OCP\\IUser $user, OCP\\Files\\FileInfo $sourceFile, $revision)```

How can I restore the nextcloud instance?

**Comment by fsteinbauer** [comment] 2019-11-18 19:46
To anyone having the same issue while updating from 16.0.5 to 17.0.1:
Disable the groupfolder extension using the cli:
``` runuser --user www-data -- php occ app:disable groupfolders```

Then go back to the web page, finish the update. 
Go to Settings >> Apps und update Groupfolders to 5.0.4. 
Enable Groupfolders again. 
Voilá

**Comment by despens** [comment] 2019-12-31 15:05
I used the web updater from 16.0.7 to 17.0.2 and got the same error with groupfolders. The web updater noted that all apps would have updates available with the new version.
