### ISSUE TITLE
occ groupfolders:scan id -> TypeError: OCA\GroupFolders\ACL\ACLManagerFactory::getACLManager():

### ISSUE THREAD

**Issue by thorsten-schwartz** [nextcloud/groupfolders#2480] opened 2023-07-20 18:51 UTC
Hi I am running nexcloud 27.0.0 with groupfolders 15.0.1 on Ububtu Server.

After adding some files with a bash script I try to run php occ groupfolders:scan 26
26 is right, it is also shown for the folder  with php occ groupfolders:scan

I get the following error (SECRET is a replacement):

www-data@sandwellen:/data/webspace/de/SECRET/cloud/service$ php occ groupfolders:scan 26
An unhandled exception has been thrown:
TypeError: OCA\GroupFolders\ACL\ACLManagerFactory::getACLManager(): Argument #1 ($user) must be of type OCP\IUser, null given, called in /data/webspace/de/SECRET/cloud/service/apps/groupfolders/lib/Mount/MountProvider.php on line 206 and defined in /data/webspace/de/SECRET/cloud/service/apps/groupfolders/lib/ACL/ACLManagerFactory.php:37
Stack trace:
#0 /data/webspace/de/SECRET/cloud/service/apps/groupfolders/lib/Mount/MountProvider.php(206): OCA\GroupFolders\ACL\ACLManagerFactory->getACLManager()
#1 /data/webspace/de/SECRET/cloud/service/apps/groupfolders/lib/Command/Scan.php(82): OCA\GroupFolders\Mount\MountProvider->getMount()
#2 /data/webspace/de/SECRET/cloud/service/3rdparty/symfony/console/Command/Command.php(298): OCA\GroupFolders\Command\Scan->execute()
#3 /data/webspace/de/SECRET/cloud/service/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run()
#4 /data/webspace/de/SECRET/cloud/service/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run()
#5 /data/webspace/de/SECRET/cloud/service/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#6 /data/webspace/de/SECRET/cloud/service/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#7 /data/webspace/de/SECRET/cloud/service/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#8 /data/webspace/de/SECRET/cloud/service/console.php(100): OC\Console\Application->run()
#9 /data/webspace/de/SECRET/cloud/service/occ(11): require_once('...')
#10 {main}www-data@sandwellen:/data/webspace/de/SECRET/cloud/service$ mc
Fehler beim Ausführen:

What's going wrong?

Greets Thorsten

**Comment by solracsf** [comment] 2023-07-20 20:17
Duplicate of https://github.com/nextcloud/groupfolders/issues/2473

**Closed by solracsf** 2023-07-20 20:17 UTC
Labels: bug, 0. Needs triage
