### ISSUE TITLE
Limitation to 2 GB 

### ISSUE THREAD

**Issue by Rude-Boy** [nextcloud/groupfolders#726] opened 2020-01-02 08:00 UTC
Current Installation:
    • NextcloudPi v1.20.1
    • Nextcloud 17.0.2.1
    • Groupfolder App 5.0.5

In the Settings, I put the limit for the size of the group-folder to 5 GB.
![Screenshot1](https://user-images.githubusercontent.com/48384161/71656923-b455d380-2d3d-11ea-82cb-1ad687b222da.png)

The  actual size is 2.3 GB and now i get the message when i open the directory.
![Screenshot2](https://user-images.githubusercontent.com/48384161/71656929-ba4bb480-2d3d-11ea-86ac-02fc6107c415.png)

Also it is not posible to add files to this folder.
It has no affect if i increase the size to 10GB (and so on), it is always limited to 2 GB.
Only with the setting on „unlimited“ there is no limit.

**Comment by wiswedel** [comment] 2020-01-02 08:01
looks like your storage is full. Have you checked that?

**Comment by Rude-Boy** [comment] 2020-01-02 08:05
yes, i checked that. More than 50 GB of the storage are empty. I have that problem only in the group-folder

**Comment by Rude-Boy** [comment] 2020-02-02 13:12
the problem still exists. I have already removed and added the app but without improvement. 
As i wrote a while ago, there is the following entry in the nextcloud log:
`[groupfolders] Debug: Could not find resource file "/apps/groupfolders/css/../build/settings.css"`

There is no directory `/var/www/nextcloud/apps/groupfolders/css/`, but `/var/www/nextcloud/apps/groupfolders/build/` exists.
There is no file`settings.css` in it, but `settings.js`

does this information help? I just want it to work.

**Comment by pkmkrishnakumar** [comment] 2020-05-10 04:38
I too have this problem, is there any work around to sort this out or there any permission related issues to create a group folder.
If there is any requirements for any permissions please let us know

**Comment by CarlSchwan** [comment] 2021-11-11 16:20
I couldn't reproduce this issue anymore with Nextcloud 22. Some size calculation problems got fixed since this bug was reported and maybe this one too at the same time. I'm closing it but feel free to reopen if this problem can be reproduced in a recent Nextcloud version.

**Closed by CarlSchwan** 2021-11-11 16:20 UTC
Labels: bug, 0. Needs triage, integration, feature: quota
