### ISSUE TITLE
Folder gets overriden when create a group folder with a name, already taken by a users local folder

### ISSUE THREAD

**Issue by Commifreak** [nextcloud/groupfolders#1045] opened 2020-09-08 09:46 UTC
NC: 18.0.7
Group Folders: 6.0.7

Issue: If a user has previously created a folder with a name which is now taken by a group folder, it would be overidden. The plugin does not check if a group folders name already exists in the root of a user

Steps to reproduce:

1. Create an own folder named "Very Important"
2. Place some files in it
3. Create a group folder named "Very Important"
4. The users previously created folder is now empty in the WebUI.

That's not acceptable.

**Comment by Commifreak** [comment] 2020-09-08 10:13
Is duplicate with #970 ! Deleting the group folder restores the users local folder.

**Comment by Daksol** [comment] 2020-10-01 12:30
Related issue. Group Folders lets me create two GFs at the same level with same name.

**Comment by wiswedel** [comment] 2021-01-22 14:58
duplicate of https://github.com/nextcloud/groupfolders/issues/648

**Closed by wiswedel** 2021-01-22 14:58 UTC
