### ISSUE TITLE
Check for changers once every direct access

### ISSUE THREAD

**Issue by Unclewowa** [nextcloud/groupfolders#2532] opened 2023-08-30 14:36 UTC
I'd like nextcloud to check groupfolder for changers once every direct access, like External Storage does.
I have direct changes on mounted drives which aren't represented in Nextcloud interface, so that there is no changes unless I initiate cache refreshing.

**Comment by joshtrichards** [comment] 2024-09-11 17:36
Duplicate of #787

**Closed by joshtrichards** 2024-09-11 17:36 UTC
Labels: enhancement, 0. Needs triage
