### ISSUE TITLE
Restoring files from trashbin should be limited to users with write access

### ISSUE THREAD

**Issue by jngrb** [nextcloud/groupfolders#1258] opened 2021-01-31 16:58 UTC
**Actual behaviour**: 
A user can restore files that someone else deleted from folders where the user does have write permission

**Expected behaviour**: 
Users should not be able to restore files to folders where they don't have write permission

**steps to reproduce**: 
- create a groupfolder with create,write,read permissions for user A
- user A creates a file X within the folder
- give read permissions to another user B
- user A deletes the file X
- user B can restore file X despite having write permissions

This should be the enforced both for cases where user B only has read access because of a) general permissions and where b) special advanced permissions for subfolders are configured.

**Comment by ZeikoFr** [comment] 2021-02-06 19:56
I can confirm this issue is present, the ACL are not applied to the trashbin of group folder, and if i'm remember correctly user B in your exemple can also permanently delete the file

**Comment by CarlSchwan** [comment] 2021-11-10 13:16
Hi, unfortunately, I couldn't reproduce this bug with master. Looking at the git history this bug was fixed with 95cb7778. Feel free to reopen if the issue can still be reproduced with recent nextcloud version.

**Closed by CarlSchwan** 2021-11-10 13:16 UTC
Labels: bug, 0. Needs triage, feature: acl, feature: trashbin, integration

**Comment by CarlSchwan** [comment] 2021-11-10 13:37
Actually this might have been fixed much more recently with 8fcff71449cbf2addd198fb8b7be87ba73af0712
