### ISSUE TITLE
THIS APP WILL DELETE EXISTING FILES, WITHOUT WARNING, WHEN ADDING AN EXISTING FOLDER TO A GROUP

### ISSUE THREAD

**Issue by jimoquinn** [nextcloud/groupfolders#138] opened 2018-07-11 05:32 UTC
PLEASE PULL THIS APP FROM THE NEXTCLOUD APP STORE UNTIL THIS IS FIXED.

You'd think that an app designed to manage files as a group would not delete all your files when adding a directory to a group.

You'd think that an application designed to sync files would not approve an app that deletes all the files in a directory without warning.

You'd think if the first two were true, this app would move these files into the Trash so they could be restored.  This app does not do that.

WTH?

**Comment by team-a2** [comment] 2018-07-11 05:36
no.
delete the group-folder and Your other folder will appear again. see https://github.com/nextcloud/groupfolders/issues/18#issuecomment-323316769

**Comment by Cracky5457** [comment] 2018-07-11 09:37
Can you just explain the bug and how to reproduce it ?

**Comment by icewind1991** [comment] 2018-07-11 12:46
Closing as duplicate of https://github.com/nextcloud/groupfolders/issues/18

**Closed by icewind1991** 2018-07-11 12:46 UTC

**Comment by jimoquinn** [comment] 2018-07-21 07:12
"delete the group-folder and Your other folder will appear again. see #18 (comment)"

Ridiculous.  Just look through all the issues at folks chasing their own tails because files disappear.  The goal is to keep files, not magically hide them.  And to get the files to reappear, I have to delete the directory?  I don't know of any filesystem that behaves this way.  This app needs to be pulled because it does not help the reputation of nextcloud and leaves users extremely frustrated and it magically hides files without warning, which is in direct opposition of Nextcloud's basic goals.
