### ISSUE TITLE
($user) must be of type OCP\IUser, null given since update to GroupFolder 13.1.4

### ISSUE THREAD

**Issue by Baptistou** [nextcloud/groupfolders#2479] opened 2023-07-20 13:55 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Update from GroupFolder 13.1.3 to 13.1.4
2. See error logs

### Expected behaviour
No error should happen

### Actual behaviour
Every 12 hours, I receive by email from CronDeamon the following error since I updated GroupFolder 2 days ago.
The first error was sent on 2023-07-18T06:50:04+00:00 while the app was updated on 2023-07-18T06:39:40+00:00.
```
[cron] Erreur: TypeError: OCA\GroupFolders\ACL\ACLManagerFactory::getACLManager(): Argument #1 ($user) must be of type OCP\IUser, null given, called in /homepages/36/d123456789/htdocs/apps/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php on line 206 at <<closure>>

0. /homepages/36/d123456789/htdocs/apps/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php line 206
   OCA\GroupFolders\ACL\ACLManagerFactory->getACLManager()
1. /homepages/36/d123456789/htdocs/apps/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php line 172
   OCA\GroupFolders\Mount\MountProvider->getMount()
2. /homepages/36/d123456789/htdocs/apps/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 68
   OCA\GroupFolders\Versions\VersionsBackend->getAllVersionedFiles()
3. /homepages/36/d123456789/htdocs/apps/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 59
   OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()
4. /homepages/36/d123456789/htdocs/apps/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 43
   OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
5. /homepages/36/d123456789/htdocs/apps/nextcloud/lib/public/BackgroundJob/Job.php line 78
   OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run()
6. /homepages/36/d123456789/htdocs/apps/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
   OCP\BackgroundJob\Job->start()
7. /homepages/36/d123456789/htdocs/apps/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
   OCP\BackgroundJob\TimedJob->start()
8. /homepages/36/d123456789/htdocs/apps/nextcloud/cron.php line 152
   OCP\BackgroundJob\TimedJob->execute()

at 2023-07-20T06:50:04+00:00
```

### Server configuration

**Operating system:** Debian 10.13

**Web server:** Apache 2

**Database:** 10.3.39-MariaDB

**PHP version:** 8.0

**Nextcloud version:** Nextcloud 25.0.8

**Group folders version:** 13.1.4

**Updated from an older Nextcloud/ownCloud or fresh install:** 13.1.3

**Where did you install Nextcloud from:** zip file from website

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"2oRkL5CIP9tVtBuZKU9O","level":3,"time":"2023-07-20T06:50:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"OCA\\GroupFolders\\ACL\\ACLManagerFactory::getACLManager(): Argument #1 ($user) must be of type OCP\\IUser, null given, called in /homepages/36/d123456789/htdocs/apps/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php on line 206","userAgent":"--","version":"25.0.8.2","exception":{"Exception":"TypeError","Message":"OCA\\GroupFolders\\ACL\\ACLManagerFactory::getACLManager(): Argument #1 ($user) must be of type OCP\\IUser, null given, called in /homepages/36/d123456789/htdocs/apps/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php on line 206","Code":0,"Trace":[{"file":"/homepages/36/d123456789/htdocs/apps/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php","line":206,"function":"getACLManager","class":"OCA\\GroupFolders\\ACL\\ACLManagerFactory","type":"->"},{"file":"/homepages/36/d123456789/htdocs/apps/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php","line":172,"function":"getMount","class":"OCA\\GroupFolders\\Mount\\MountProvider","type":"->"},{"file":"/homepages/36/d123456789/htdocs/apps/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":68,"function":"getAllVersionedFiles","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->"},{"file":"/homepages/36/d123456789/htdocs/apps/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":59,"function":"expireFolder","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->"},{"file":"/homepages/36/d123456789/htdocs/apps/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php","line":43,"function":"expireAll","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->"},{"file":"/homepages/36/d123456789/htdocs/apps/nextcloud/lib/public/BackgroundJob/Job.php","line":78,"function":"run","class":"OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions","type":"->"},{"file":"/homepages/36/d123456789/htdocs/apps/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":103,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/homepages/36/d123456789/htdocs/apps/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":93,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/homepages/36/d123456789/htdocs/apps/nextcloud/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/homepages/36/d123456789/htdocs/apps/nextcloud/apps/groupfolders/lib/ACL/ACLManagerFactory.php","Line":37,"CustomMessage":"--"},"id":"64b935fc3f3a8"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

</details>

**Comment by solracsf** [comment] 2023-07-20 14:01
Duplicate of https://github.com/nextcloud/groupfolders/issues/2473

**Closed by solracsf** 2023-07-20 14:01 UTC
Labels: bug, 0. Needs triage
