### ISSUE TITLE
Folder disappears when a group folder with the same name is created.

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/groupfolders#219] opened 2018-10-19 12:56 UTC
Steps to reproduce:

1) User has a folder like "Dokumente"
![image](https://user-images.githubusercontent.com/16019165/47218875-77f2bd80-d3ad-11e8-8b64-74482c3bcd03.png)

2) Create a groupfolder with the name "Dokumente"
![image](https://user-images.githubusercontent.com/16019165/47218923-a1abe480-d3ad-11e8-90be-16d7cfab0491.png)

3) The folder from the user is replaced with the groufolder... the user has no possibility to get his files.
![image](https://user-images.githubusercontent.com/16019165/47218992-cf912900-d3ad-11e8-9b04-180e9c3aff33.png)

When the group folder is removed, the folder reappears.

Group folders should be treated differently. Maybe with an identifier "**GP_**Dokumente" or maybe create a separate view (under "All view") where the groupfolders are displayed...

**Comment by Nils160988** [comment] 2018-10-29 23:55
This issue is a duplicate of #18

**Comment by icewind1991** [comment] 2018-11-27 16:13
Closing as duplicate

**Closed by icewind1991** 2018-11-27 16:13 UTC
