### ISSUE TITLE
permissions dont autorefresh, manual refresh is needed

### ISSUE THREAD

**Issue by diemelone** [nextcloud/groupfolders#1455] opened 2021-04-19 14:56 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Inside a groupfolder create min. two new folders
2. change permissions for groups on one folder, now try the same with the other folder. The permissions section will display the permissions from the previously edited folder. 
3. In order to change permissions on the next folder you have to refresh the site

### Expected behaviour
permission section should automatically update

### Actual behaviour
permission section stays the same when trying to edit permissions on multiple folders after one another 

### Server configuration

**Operating system:**
linux
**Web server:**

**Database:**
mysql
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
21.0
**Group folders version:**
most recent
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
webhoster
**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
no

### Client configuration
**Browser:**
Mozilla and edge, multiple computers tried

**Operating system:**
win 10, multiple computers tried

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by fschrempf** [comment] 2021-04-23 16:34
Closing as duplicate of #1378.

**Closed by fschrempf** 2021-04-23 16:34 UTC
Labels: 0. Needs triage, bug
