### ISSUE TITLE
Lots of PHP error

### ISSUE THREAD

**Issue by tceydeliler** [nextcloud/groupfolders#1238] opened 2021-01-21 05:20 UTC
When I Create A group folder and assign user, I get those errors:
Server: version: 20.0.05 
Ubuntu 20.0.04
MariadB
Apache 2.4
PHP 7.3
> {"reqId":"Zl3SbvujBZVCVwdMdu4O","level":3,"time":"2021-01-21T08:05:49+03:00","remoteAddr":"10.65.8.100","user":"2BE98F99-8969-4CEA-9F71-FC6CB5970795","app":"PHP","method":"PROPFIND","url":"/nextcloud/remote.php/dav/trashbin/2BE98F99-8969-4CEA-9F71-FC6CB5970795/trash","message":{"Exception":"Error","Message":"Trying to access array offset on value of type int at /var/www/html/nextcloud/lib/private/Files/Node/Node.php#328","Code":0,"Trace":
> [{"file":"/var/www/html/nextcloud/lib/private/Files/Node/Node.php","line":328,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/html/nextcloud/lib/private/Files/Node/Folder.php","line":62,"function":"isValidPath","class":"OC\\Files\\Node\\Node","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/Node/Folder.php","line":163,"function":"getFullPath","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/var/www/html/nextcloud/apps/groupfolders/lib/Trash/TrashBackend.php","line":250,"function":"newFolder","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/var/www/html/nextcloud/apps/groupfolders/lib/Trash/TrashBackend.php","line":268,"function":"getTrashFolder","class":"OCA\\GroupFolders\\Trash\\TrashBackend","type":"->"},{"file":"/var/www/html/nextcloud/apps/groupfolders/lib/Trash/TrashBackend.php","line":71,"function":"getTrashForFolders","class":"OCA\\GroupFolders\\Trash\\TrashBackend","type":"->"},{"file":"/var/www/html/nextcloud/apps/files_trashbin/lib/Trash/TrashManager.php","line":48,"function":"listTrashRoot","class":"OCA\\GroupFolders\\Trash\\TrashBackend","type":"->"},{"function":"OCA\\Files_Trashbin\\Trash\\{closure}","class":"OCA\\Files_Trashbin\\Trash\\TrashManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/apps/files_trashbin/lib/Trash/TrashManager.php","line":49,"function":"array_reduce"},{"file":"/var/www/html/nextcloud/apps/files_trashbin/lib/Sabre/TrashRoot.php","line":72,"function":"listTrashRoot","class":"OCA\\Files_Trashbin\\Trash\\TrashManager","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":204,"function":"getChildren","class":"OCA\\Files_Trashbin\\Sabre\\TrashRoot","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":905,"function":"getChildren","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":987,"function":"generatePathNodes","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1678,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1661,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":363,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/remote.php","line":167,"args":["/var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.5.2","id":"60090dd64972f"}

**Comment by rteitge** [comment] 2021-02-20 18:00
I can confirm this error.

Server: 20.0.7
Debian 9.13
MariaDB 10.1.48
PHP 7.4.15

`{"reqId":"iS6IH7YvYu3AO1HWi80H","level":3,"time":"2021-02-20T17:19:57+00:00","remoteAddr":"92.117.122.192","user":"...","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/trashbin/.../trash","message":{"Exception":"Error","Message":"Trying to access array offset on value of type int at /#path-to-cloud/lib/private/Files/Node/Node.php#328","Code":0,"Trace":[{"file":"/#path-to-cloud/lib/private/Files/Node/Node.php","line":328,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/#path-to-cloud/lib/private/Files/Node/Folder.php","line":62,"function":"isValidPath","class":"OC\\Files\\Node\\Node","type":"->"},{"file":"/#path-to-cloud/lib/private/Files/Node/Folder.php","line":163,"function":"getFullPath","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/#path-to-cloud/apps/groupfolders/lib/Trash/TrashBackend.php","line":250,"function":"newFolder","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/#path-to-cloud/apps/groupfolders/lib/Trash/TrashBackend.php","line":268,"function":"getTrashFolder","class":"OCA\\GroupFolders\\Trash\\TrashBackend","type":"->"},{"file":"/#path-to-cloud/apps/groupfolders/lib/Trash/TrashBackend.php","line":71,"function":"getTrashForFolders","class":"OCA\\GroupFolders\\Trash\\TrashBackend","type":"->"},{"file":"/#path-to-cloud/apps/files_trashbin/lib/Trash/TrashManager.php","line":48,"function":"listTrashRoot","class":"OCA\\GroupFolders\\Trash\\TrashBackend","type":"->"},{"function":"OCA\\Files_Trashbin\\Trash\\{closure}","class":"OCA\\Files_Trashbin\\Trash\\TrashManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/#path-to-cloud/apps/files_trashbin/lib/Trash/TrashManager.php","line":49,"function":"array_reduce"},{"file":"/#path-to-cloud/apps/files_trashbin/lib/Sabre/TrashRoot.php","line":72,"function":"listTrashRoot","class":"OCA\\Files_Trashbin\\Trash\\TrashManager","type":"->"},{"file":"/#path-to-cloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":204,"function":"getChildren","class":"OCA\\Files_Trashbin\\Sabre\\TrashRoot","type":"->"},{"file":"/#path-to-cloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":905,"function":"getChildren","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/#path-to-cloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":987,"function":"generatePathNodes","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/#path-to-cloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1678,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/#path-to-cloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1661,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/#path-to-cloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":363,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/#path-to-cloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/#path-to-cloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/#path-to-cloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/#path-to-cloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/#path-to-cloud/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/#path-to-cloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/#path-to-cloud/remote.php","line":167,"args":["/#path-to-cloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/#path-to-cloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0","version":"20.0.7.1","id":"603144bd42bc7"}`

**Comment by pierreozoux** [comment] 2021-03-11 10:50
Do you also have user errors? or just backend erros, and the users are not affected?

**Comment by fschrempf** [comment] 2021-11-10 13:10
Closing as duplicate of #907.

**Closed by fschrempf** 2021-11-10 13:10 UTC
Labels: bug, 0. Needs triage, error_log, feature: trashbin
