### ISSUE TITLE
Permissions not respected

### ISSUE THREAD

**Issue by os-ai** [nextcloud/groupfolders#1905] opened 2022-02-24 15:46 UTC
Using advanced ACL. 
When downloading an entire group folder off the web interface, the permissions are respected for the user.
When copying-pasting a Group (or a parent) folder via the web interface, the permissions are not respected, and a user without read access to certain subfolders can download the entire Group folder with all data.

Example, a user may have the following permissions:

Group folder (read-only)
   |--- Folder 1 (read-only)
   |--- Folder 2 (no read access)
   |--- Folder 3 (read-only)
          |--- Folder 3.1 (no read access)

When the user copies the Group folder via the web interface, the entire contents of the Group folder including folders 2, 3 and 3.1 are copied to the destination.

**Comment by fschrempf** [comment] 2022-02-24 16:52
@os-ai I will close this as you didn't use the issue template and information is missing. Please create a new issue, use the template for bug reports and fill in the required information. You don't need to provide all the information in the template, but as much as you can.

Apart from this I couldn't reproduce this issue on NC 23.

**Closed by fschrempf** 2022-02-24 16:52 UTC
