### ISSUE TITLE
Duplicate GroupNames causes unexpected issues

### ISSUE THREAD

**Issue by 13hannes11** [nextcloud/groupfolders#251] opened 2018-12-14 20:22 UTC
Create a group folder.
Create another with the same name.

Issues for Users who have access to both folders -> just one will be displayed.

My suggestion would be to just allow unique names.

**Comment by Nils160988** [comment] 2018-12-18 00:50
Duplicate of #219 and some similar issues (#18).

**Closed** 2018-12-21 18:05 UTC
