### ISSUE TITLE
Name Overwrite

### ISSUE THREAD

**Issue by sanojkl** [nextcloud/groupfolders#1185] opened 2020-12-21 16:40 UTC
When a Person is added to a Group with a Folder and this Person have a private folder with the same name, the perosn can't access the private files anymore, the only solution without removing from the group is that an admin rename the folder and trigger a file rescan

**Comment by ChristophWurst** [comment] 2021-01-29 10:16
Duplicate of https://github.com/nextcloud/groupfolders/issues/648

**Closed by ChristophWurst** 2021-01-29 10:16 UTC
