### ISSUE TITLE
Files dissapeared after changing size of group folder

### ISSUE THREAD

**Issue by carlosdiaz2017** [nextcloud/groupfolders#1642] opened 2021-08-23 16:09 UTC
Hi there, 

It seems that I changed the size of the group folder to 10 GB when the size of that folder was over 500 GB.
I don't really know how I did it, I was playing around cause I had some sync issues, and probably I selected that. 
Re-enabling the size or disabling/enabling group folder did not solve the issue.
There was no warning messages, or nothing, it just changed and now all the files corresponding to the others 490 GB has dissappeared. 

Anyway, I have a backup and it is fine. But If you could set an alert to prevent this, that would be great. 
Best,
           Carlos

**Comment by fschrempf** [comment] 2021-11-26 09:41
Do you mean you changed the quota of a groupfolder and this resulted in files being deleted? Is this something you can reproduce?

**Comment by joshtrichards** [comment] 2024-09-11 16:09
Closing for the following reasons:

- no follow-up info received ~3 years
- I cannot reproduce this today (at least with the information provided in the original report)
- when the quota is exceeded, various file functions that fail are logged in the `nextcloud.log` (at level 3 so should be apparent if anything happens)
- there's an indicator in the UI today showing utilization on the quota setting itself
- no similar reports

**Closed by joshtrichards** 2024-09-11 16:09 UTC
Labels: bug, needs info, 0. Needs triage, feature: client sync, feature: quota
