### ISSUE TITLE
Could not find mount point, can't keep encryption keys

### ISSUE THREAD

**Issue by Bables55** [nextcloud/groupfolders#773] opened 2020-02-20 00:47 UTC
The following error occurs when user create a document in the folder specified in the groupfolders and try to save it.
`[no app in context] Error: Could not find mount point, can't keep encryption keys`
I remember having this problem since NC18.0.1.

I have more concerns. 
Previously, when I created a file in a folder restricted by Groupfolders, I could only edit it for a few minutes. I couldn't edit the file after a period of time. But now I can edit at any time. 

In the behavior after file generation, the file can be edited and the file can't  be edited. Which is correct?

The default value of my shared NC is only "Create".
The default value of Groupfolders is only "Write" and "Share".
I have not changed these settings.

---
Nextcloud 18.0.1, PHP7.3.14, Groupfolders 6.0.1

**Comment by robertoschwald** [comment] 2020-10-06 18:13
Same here. I'm currently on 19.0.3. 
The count is 7 here.

**Comment by pierreozoux** [comment] 2021-03-14 20:47
duplicate of #912

**Closed by pierreozoux** 2021-03-14 20:47 UTC
Labels: 0. Needs triage
