### ISSUE TITLE
Root of group folders

### ISSUE THREAD

**Issue by sodiumchl** [nextcloud/groupfolders#757] opened 2020-02-09 14:25 UTC
Is it possible to to have the group folders created in this app appear in users' /Group_Folder/ instead of / ?

**Comment by sodiumchl** [comment] 2020-02-10 01:17
It seems the following change works:
MountProvider.php:91:  '/' . $user->getUID() . '/files/Group Folders/' . $folder['mount_point'],
But /Group Folders have to be created for all users first.

**Comment by fschrempf** [comment] 2021-03-30 08:58
It seems like you want to have the groupfolders content not in the users root file view, but in a separate subdir/view. So it seems like this is a duplicate of #139. If I got this wrong, please let me know and I will reopen.

**Closed by fschrempf** 2021-03-30 08:58 UTC
Labels: 0. Needs triage, enhancement
