### ISSUE TITLE
modification of rights with groups that have slash in their names is not possible

### ISSUE THREAD

**Issue by joe-speedboat** [nextcloud/groupfolders#371] opened 2019-04-02 14:23 UTC
NC Version: 15.0.5
GroupFolder: 2.0.4
OS: CentOS 7 recent
Setup with: [Ansible Role](https://galaxy.ansible.com/uniQconsulting/nextcloud)

# Procedure to show up the problem
- create new local group: "test 123" 
- create new local group: "test 1/2/3"
- Settings > GroupFolder > New > "test 123"
  - Add Group "test 123" to GroupFolder "test 123" with perm "write only"
  - Add Group "test 1/2/3" to GroupFolder "test 123" with perm "write only"
- Reload Browser Page
- Review GroupFolder permissions for "test 123"

# expected result
- group rights for both groups are equal

# current result
- group rights for group "test 1/2/3" is write, share & delete
- group rights for group "test 123" is "only write"

It seems that the groupfolder app does not handle perms if group has "/" 
I could not found any logs for that problem in nextcloud/data/nextcloud.log file.

Thanks for helping

**Comment by pierreozoux** [comment] 2021-03-14 21:35
A group with a `/` in the name is actually asubfolder, I'll close it as a duplicate of https://github.com/nextcloud/groupfolders/issues/355

**Closed by pierreozoux** 2021-03-14 21:35 UTC
Labels: 0. Needs triage
