### ISSUE TITLE
Deleted folders get restored (or resynced) later

### ISSUE THREAD

**Issue by markum** [nextcloud/groupfolders#2249] opened 2023-02-03 12:42 UTC
Hey,

we are a small ngo using nextcloud with group folders. Recently I was doing some reorganisation with the folder structure. I had to delete or move subfolders. Unfortunately larger subfolders get restored. I believe this is due to the fact that not everyone is online at the time. The result is when I delete (or move) a folder, the original folder gets uploaded/synced from another user again. it does not matter if I delete the folder directly via the webinterface or locally on my computer. After a while it is back :-(

**Comment by feiltom** [comment] 2023-10-30 13:05
Hello i have the same problem. some issue ? my server is used in production for 20 peoples. this bug is very disadvantageous for us.

**Comment by JocelynDelalande** [comment] 2024-01-16 15:59
@markum same as #2049 ?

**Comment by joshtrichards** [comment] 2024-09-09 21:21
Duplicate of #2049

**Closed by joshtrichards** 2024-09-09 21:21 UTC
Labels: bug, 0. Needs triage, feature: client sync, feature: trashbin
