### ISSUE TITLE
Activity app doesn't log move, rename and share (except for the user that did the change)

### ISSUE THREAD

**Issue by dakser** [nextcloud/groupfolders#1018] opened 2020-08-24 08:33 UTC
Hi, I noticed that if two users edit a file, the activity doesn't show "user1 edited" and then "user2 edited", it only shows the activity for the user viewing the activity, I hope that it could be improved to be able to follow what users are doing in the files in the group folders so we can track the work done, the errors and more. Thanks in advance.

**Comment by sbernhard** [comment] 2020-09-16 19:55
See config option activity_use_cached_mountpoints

**Comment by chrisfritsche** [comment] 2020-10-02 10:09
Hi @dakser ! If you enable the flag, as @sbernhard  write, the only notifications that you will see is the creation but not editing, deleting, moving, unshare and so one. For this reason, i create this [PR](https://github.com/nextcloud/activity/pull/500). And because comments on "group folders files" are also not tracked currently, i create this [PR](https://github.com/nextcloud/server/pull/23036), to solve this issue. Maybe you can comment at this 2 PR's in order to have more discussion about and they want to merge it. Bye and thanks in advance!

**Comment by Zatalyz** [comment] 2021-01-02 17:10
In my config/config.php, I had this:
`'activity_use_cached_mountpoints' => true,`

But it crash my nextcloud, with this error in nginx log : 
`2021/01/02 16:56:54 [error] 8209#8209: *168642 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ''activity_use_cached_mountpoin' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /var/www/nextcloud/config/config.php on line 39" while reading upstream, client: 10.0.0.10, server: mycloud.org, request: "GET /apps/dashboard/ HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "mycloud.org"`

Why it doesn't work ?

**Comment by provokateurin** [comment] 2024-09-18 12:37
Duplicate of https://github.com/nextcloud/groupfolders/issues/2294

**Closed by provokateurin** 2024-09-18 12:37 UTC
Labels: bug, 3. to review, integration, feature: activity and notification
