### ISSUE TITLE
parent level quota does not work for (group)subfolders

### ISSUE THREAD

**Issue by buildingawesomethings** [nextcloud/groupfolders#65] opened 2017-09-15 15:35 UTC
When creating the following structure, the quota of the top-level folder is not respected:
- Groupfolder A  (as groupfolder "folder A", where groups X, Y and Z have access)
   - Subfolder B (as groupfolder "folder A/folder B", where groups X, Y and Z have access)
   - Subfolder C (as groupfolder "folder A/folder C", where only group Z has access)

When i set the quota of folder A to 1 KB, i cannot upload in this folder directly but i can upload in folder B and C.

Expected behaviour:  The sum of the size of all files and folders in subfolder A, including B and C, should count towards the max quota. Thus restricting me from uploading in folders B or C if i go above 1 KB.

**Comment by putt1ck** [comment] 2017-10-09 06:40
For clarity, do you mean:

you create a group folder X and set a quota Y;
the quota is enforced for files added to the root of X;
but subfolders of X fall outside the quota?

**Comment by putt1ck** [comment] 2017-10-09 06:59
NB tested in 12.03:

set quota on group folder;
tried to upload file larger than quota (failed with notification that file too large);
created subfolder, tried to upload file larger than quota (failed with notification that file too large);

**Comment by putt1ck** [comment] 2017-10-09 09:11
further testing: added smaller files to sub folder until quota reached, at which point next upload failed with quota warning message.

@buildingawesomethings can you confirm your scenario and versions of Nextcloud and Group folder app?

**Comment by buildingawesomethings** [comment] 2017-10-09 09:21
Hi Putt1ck,

Thanks for looking into this, and sorry for being unclear! I will try to explain with a more solid example:

- Using the groupfolder app, create the following two folders:
   MyGroup and MyGroup/SecretFolder
- Set the quota of the parent folder "MyGroup" to say 100 MB
- Add file of 200 MB to the child folder "MyGroup/SecretFolder"
- File gets added without problems, and as such doesn't respect the 100 MB limit of the parent.

Note that the MyGroup/SecretFolder is created using the groupfolders app, so i can assign appropriate rights to this sub(group)folder.

It's a recent fresh install of Nextcloud 12.0.2 with the latest version of the Groupfolder app.

**Comment by putt1ck** [comment] 2017-10-09 10:20
@buildingawesomethings I think I'm missing something - how do you add a group folder as a sub folder to another group folder?

**Comment by buildingawesomethings** [comment] 2017-10-09 10:50
You can simply add a subfolder like this screenshot: (this was described in a different issue here)

![screenshot-groupfolders](https://user-images.githubusercontent.com/20867334/31334857-57f8ae34-acf0-11e7-8f25-1f624b388adc.PNG)

**Comment by putt1ck** [comment] 2017-10-09 12:20
I'm not sure that's a subfolder in practice. It appears in the server file system as its own folder (unlike sub folders created in the group folder directly) and doesn't inherit permissions; the only way it acts as a sub folder is it doesn't appear in a users list of shares/folders etc. - which helps if you are likely to end up with a lot of group folders and want to make them easier to find.

**Comment by putt1ck** [comment] 2017-10-09 12:21
NB marked as enhancement request - to have option of sub group folders be counted in the quota of the parent group folder.

**Comment by buildingawesomethings** [comment] 2017-10-09 14:13
@putt1ck since we want different permissions for the subfolder (e.g. only accessible to certain staff), not inheriting rights is a good thing. It would be awesome if the enhancement can be implemented. thanks !

**Comment by icewind1991** [comment] 2017-11-10 14:13
This is expected behaviour, each folder created acts as it's own entity.

Since there are also use cases for not having "subfolders" count toward to quota it's very unlikely that this is something I want to implement.

**Closed by icewind1991** 2017-11-10 14:13 UTC
Labels: enhancement

**Comment by buildingawesomethings** [comment] 2017-11-11 12:38
Hi Icewind,

I understand there could be use cases where it should not count towards the quota, but might it be possible to then at least add a select option in the quota selector like "Use parent quota" ?

Or alternatively; create an option to natively add a subfolder inside an exisiting groupfolder with different rights but the same quota. (this latter seems a bit more complicated though).

I'm really desperate for such a function, i'm willing to pay you for adding it :)
