### ISSUE TITLE
Groupfolder view is empty in 30 RC2

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/groupfolders#3134] opened 2024-08-22 20:58 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Update from 29 to 30 RC2

### Expected behaviour
Opening `apps/files/groupfolders` should show groupfolders

### Actual behaviour
The view is empty. When reloading the page, a loading spinner is shown that never disappears. I don't see a `dav/` request in the dev console

Also seen on c.nc.c

**Comment by skjnldsv** [comment] 2024-08-28 12:44
duplicate of https://github.com/nextcloud/groupfolders/issues/3128

**Closed** 2024-08-28 12:44 UTC
Labels: bug, 0. Needs triage
