### ISSUE TITLE
Can't delete files/folder below the first level

### ISSUE THREAD

**Issue by dakky** [nextcloud/groupfolders#2945] opened 2024-05-03 17:51 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Right click/3-dot-menu on file/folder on first group folder level: delete button is there
2. Right click/3-dot-menu on file/folder on a lower group folder level: delete button is there

### Expected behaviour
deleting files on a lower level should be possible

### Actual behaviour
no delete button on lower level files/folders
* First level:    
  ![image](https://github.com/nextcloud/groupfolders/assets/579584/1e263b49-5200-4608-91db-f3d05f776af9)

* One level deeper:
   ![image](https://github.com/nextcloud/groupfolders/assets/579584/3bc98cbe-7d1b-4f32-887a-5de5aca99079)

### Server configuration
latest nextcloud:apache docker image

**Nextcloud version:** (see Nextcloud admin page)
Hub 8 (29.0)

**Group folders version:**
 16.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**
yes

**Where did you install Nextcloud from:** dockerhub

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Firefox
**Operating system:**
Fedora 39

#### Web server error log
<details>
<summary>Web server error log</summary>

```
nothing relevant
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
groupfolder related messages see  #2935 
```
</details>

**Comment by XueSheng-GIT** [comment] 2024-05-04 05:41
I cannot reproduce.
@dakky is it possible that your "lower level" folder is a nested group folder?
Would be helpful if you could post your groupfolder setup.

**Comment by dakky** [comment] 2024-05-04 06:00
nope they are not. My groupfolder setup:
![image](https://github.com/nextcloud/groupfolders/assets/579584/45b016c6-0760-4069-a392-a4978b21f434)

The content was synced from another nextcloud setup some time ago (not shure if the problem was present there):
oldisntance:/groupfolder1 -> newisntance:/groupfolder1
Tool which was used: `rclone` 

Is there a way to recheck/rebuild/whatever the content of the groupfolder?

I have another groupfolder: there this problem does not exist. so it seems not to be a general issue

**Comment by XueSheng-GIT** [comment] 2024-05-05 04:50
@dakky I assume rclone could be used in different ways. Did you use nextcloud webdav for sync in both cases?

If you don't have any shares related to that groupfolder, I suggest to do a backup (download) of the data, remove the groupfolder, create a new one and upload the data again.
Alternatively, you could create a new groupfolder, copy the data to it (within nextcloud) and if it works as expected, delete the old groupfolder and rename the new one.

**Comment by dakky** [comment] 2024-05-05 07:07
intersting: I moved all content from groupfolder A to groupfolder B (newly created) and there the same problem appears :scream:

**Comment by Mululu** [comment] 2024-05-06 10:11
I think there might be a connection here? #2934

**Comment by provokateurin** [comment] 2024-09-17 19:40
Likely a duplicate of https://github.com/nextcloud/groupfolders/issues/598, but OP didn't share enough details. Please re-open with more information or continue in the other issue.

**Closed by provokateurin** 2024-09-17 19:40 UTC
Labels: bug, 0. Needs triage, feature: trashbin
