### ISSUE TITLE
Issues when Group Folder name starts with "@"

### ISSUE THREAD

**Issue by seerocs** [nextcloud/groupfolders#1172] opened 2020-12-10 08:58 UTC
Test setup:
- Two separate Nextcloud instances (A, B)
- A: Group Folders app (v7.1.1) activated 
- A: Group Folder share created with name "@gf-test" 
- A: New Folder "Test" created within Group Folder and shared by share link (permission: allow upload+editing)
- B: Share link opened and added by "add to your Nextcloud" 
--------------
Behaviour:
- When uploading a bunch of files from an A-account to folder "Test" (direct way without share link): all good
- When uploading a bunch of files from an B-account to folder "Test" (over share link): Error "Storage was not available!"
- Same issue when using Nextcloud windows client or WebGUI

When creating another Group Folder without an "@" in name, sync works as expected.

Client Error Log (shortened):
```
2020-12-09 16:49:27:450 [ info nextcloud.gui.folder ]:	#### Propagation start ####################################################
2020-12-09 16:49:27:454 [ info nextcloud.gui.application ]:	Sync state changed for folder  "https://fs.company.ch/remote.php/dav/files/user1/" :  "Sync Running"
2020-12-09 16:49:27:466 [ info nextcloud.sync.database ]:	Updating file record for path: "SIM - TechDocu" inode: 440940 modtime: 1607528926 type: 2 etag: "5fd0f1dea436c" fileId: "00871309occuc7f5xpgb" remotePerm: "DNVCKS" fileSize: 0 checksum: "" e2eMangledName: "" isE2eEncrypted: false
2020-12-09 16:49:27:472 [ info nextcloud.sync.database ]:	Updating file record for path: "Test" inode: 468866 modtime: 1607528927 type: 2 etag: "5fd0f1df894e4" fileId: "00877270occuc7f5xpgb" remotePerm: "DNVCKS" fileSize: 0 checksum: "" e2eMangledName: "" isE2eEncrypted: false
2020-12-09 16:49:27:473 [ info nextcloud.sync.propagator ]:	Starting INSTRUCTION_IGNORE propagation of "Test" by OCC::PropagateIgnoreJob(0x29ad0382c20)
2020-12-09 16:49:27:473 [ warning nextcloud.sync.propagator ]:	Could not complete propagation of "Test" by OCC::PropagateIgnoreJob(0x29ad0382c20) with status 3 and error: "Directory temporarily not available on server."
2020-12-09 16:49:27:474 [ info nextcloud.gui.socketapi ]:	Sending SocketAPI message --> "STATUS:IGNORE+SWM:S:\\#nextcloud\\Test" to QLocalSocket(0x29aca1f7240)
2020-12-09 16:49:27:474 [ warning nextcloud.gui.activity ]:	Item  "Test"  retrieved resulted in  "Directory temporarily not available on server."
2020-12-09 16:49:27:474 [ warning nextcloud.gui.activity ]:	Item  "Test"  retrieved resulted in error  "Directory temporarily not available on server."
2020-12-09 16:49:27:475 [ info nextcloud.gui.activity ]:	Error successfully added to the notification list:  "Directory temporarily not available on server."
```

**Comment by fschrempf** [comment] 2021-11-10 13:04
I can't reproduce this with current master (nextcloud/server@586cc9bcbc3a2c659d241cf82a538326aaeb3b1d, ccd8e4e5d990b41d0b6f098b9a11749ff5f38b1d). But I didn't test with a federated setup of two instances. I guess this is needed to trigger the bug.

**Comment by jospoortvliet** [comment] 2024-12-18 20:26
A ton of file name issues [has been fixed](https://github.com/nextcloud/groupfolders/issues?q=is%3Aissue%20state%3Aclosed%20label%3A%22hot%20spot%3A%20filename%20handling%22%20label%3Abug) and if in 2021 @fschrempf already couldn't reproduce it, and given we have customers with global scale (using federation) i think it's fairly safe to assume this is long fixed. So let me close it. Re-open if you still experience it...

**Closed by jospoortvliet** 2024-12-18 20:26 UTC
Labels: bug, 0. Needs triage, hot spot: filename handling, feature: federation
