### ISSUE TITLE
new feature suggestion: Individual user permission

### ISSUE THREAD

**Issue by ckywong** [nextcloud/groupfolders#122] opened 2018-06-05 21:05 UTC
I just wonder if it is possible to have a new feature: grant permission to individual user for accessing group folder.

I have created a group folder that is readable by a group.  Inside I have one subfolder for each member of the group.  I would like each member to be able to write to their own subfolder only.  Would it be possible to have this feature?

Thank you.

**Comment by icewind1991** [comment] 2018-11-27 15:35
Closing as duplicate of #28

**Closed by icewind1991** 2018-11-27 15:35 UTC
