### ISSUE TITLE
Uploading New Files

### ISSUE THREAD

**Issue by morgan2233** [nextcloud/groupfolders#1102] opened 2020-11-03 04:27 UTC
**Server**
Operating System: CloudLinux 7
Web Server: Apache
Database: MySQL
PHP: 7.4
Nextcloud: 20.0.1

**Client**
OS: Windows 10
Browser: Edge Chromium

When I upload a new file to the group folder, the following errors show up. Only fix is uploading to my private area then moving to the group folder.

Error 1:

`Could not find mount point, can't keep encryption keys`

Error 2:

`Error: Undefined offset: 3 at /home/kohinoor/cloud.kohinoorltd.co.uk/lib/private/legacy/OC_Helper.php#548`

Error 3:

`Error: Undefined offset: 3 at /home/kohinoor/cloud.kohinoorltd.co.uk/lib/private/legacy/OC_Helper.php#548`

Error 4:

`Sabre\DAV\Exception: path needs to be relative to the system wide data folder and point to a user specific file`

Error 5:

`Error: Cannot modify header information - headers already sent by (output started at /home/kohinoor/cloud.kohinoorltd.co.uk/3rdparty/sabre/http/lib/Sapi.php:132) at /home/kohinoor/cloud.kohinoorltd.co.uk/apps/dav/lib/Connector/Sabre/File.php#691`

Error 6:

`Error: Cannot modify header information - headers already sent by (output started at /home/kohinoor/cloud.kohinoorltd.co.uk/3rdparty/sabre/http/lib/Sapi.php:132) at /home/kohinoor/cloud.kohinoorltd.co.uk/apps/dav/lib/Connector/Sabre/File.php#691`

Error 7:

`Error: Cannot modify header information - headers already sent by (output started at /home/kohinoor/cloud.kohinoorltd.co.uk/3rdparty/sabre/http/lib/Sapi.php:132) at /home/kohinoor/cloud.kohinoorltd.co.uk/apps/dav/lib/Connector/Sabre/File.php#691`

**Comment by axheli** [comment] 2020-11-05 19:14
Is your encryption on?

**Comment by morgan2233** [comment] 2020-11-07 03:58
> Is your encryption on?

yes

**Comment by axheli** [comment] 2020-11-07 11:23
> > Is your encryption on?
> 
> yes

The group folder app dose not support encryption so you can't use it! I had the same problem

**Comment by pierreozoux** [comment] 2021-03-13 08:19
Duplicate of #1031

**Closed by pierreozoux** 2021-03-13 08:19 UTC
