### ISSUE TITLE
Cannot use OCP\Constants as Constants because the name is already in use

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/groupfolders#1854] opened 2022-01-04 19:18 UTC
### Server configuration

**Operating system:**
Ubuntu 20.4
**Web server:**
Apache2
**Database:**
MariaDB 10.5.13
**PHP version:**
8.0.14
**Nextcloud version:** (see Nextcloud admin page)
23.0.0
**Group folders version:**
11.1.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
NC 22
**Where did you install Nextcloud from:**
Nextcloud
**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"iBTu4KlkJhYTgNWdGFCy","level":3,"time":"2022-01-04T18:40:01+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Cannot use OCP\\Constants as Constants because the name is already in use at /var/www/nextcloud/apps/groupfolders/lib/Command/ACL.php#35","userAgent":"--","version":"23.0.0.10","id":"61d49d58a5afd"}
```
</details>

**Comment by CarlSchwan** [comment] 2022-01-04 19:21
Looks like a rebasing went wrong. Temporary fix is too delete the line 35 in the file.

I will submit a PR tomorrow morning.

**Comment by andyxheli** [comment] 2022-01-04 19:23
copy that thank you!

**Comment by fschrempf** [comment] 2022-01-04 19:41
Bugs like these happen easily, but they should never pass the CI. We really should try to make sure that the CI is able to catch stuff like that in some way.

**Comment by CarlSchwan** [comment] 2022-01-04 19:48
https://github.com/nextcloud/groupfolders/pull/1829 would have probably caught it but it's only on master since it's an invasive change.

Only 23 and 22 are affected, 21 and master aren't

**Comment by CarlSchwan** [comment] 2022-01-04 20:12
PRs: https://github.com/nextcloud/groupfolders/pull/1856 and https://github.com/nextcloud/groupfolders/pull/1857 to fix it

I will try to release a bugfix release tomorrow. Ideally, for the 23 release, https://github.com/nextcloud/groupfolders/pull/1849 should also be included since it also fixes an important regression.

**Comment by Githopp192** [comment] 2022-01-05 11:54
same to me .. did open a case .. but saw later, case is already open (will close other one)

Actual behaviour
i've got a bash-shell script, which automatically install new app versions, when available.

(may be a bad idea).

After automatic install of "groupfolders new version available: 10.0.1" PHP reports FATAL ERROR.

PHP Fatal error: Cannot use OCP\Constants as Constants because the name is already in use in /var/www/html/nextcloud/apps/groupfolders/lib/Command/ACL.php on line 35

none of the '/var/www/html/nextcloud/occ' commands is working anymore.

Steps to reproduce
disabling the groupfolders app solves the issue.
enabling the groupfolders app triggers the issue.

Expected behaviour
Especially the "FEATURED" Apps should not bring the CORE Cloud function to malfunction.

Client configuration details
--------------------------------
na

Server configuration details
--------------------------------

**Comment by CarlSchwan** [comment] 2022-01-05 16:44
This is now fixed and @juliushaertl released new versions with the fix.

**Closed by CarlSchwan** 2022-01-05 16:44 UTC
Labels: bug, 1. to develop

**Comment by MrColumbo** [comment] 2022-04-07 16:27
> This is now fixed and @juliushaertl released new versions with the fix.

is it fixed in all versions?
I am running on NC 23.03 and Groupfolder 11.1.1 and I get the error for all OCC commands
