### ISSUE TITLE
Error in groupfolders while updating to 23.0.2

### ISSUE THREAD

**Issue by MikeEchoVoid** [nextcloud/groupfolders#1902] opened 2022-02-16 15:45 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Update to 23.0.2 from 22.2.3.0
2. version app was disabled before updating
3. Error when lauching occ command with any argument
Error: Interface 'OCA\Files_Versions\Versions\IVersionBackend' not found in /home/data/public_html/apps/groupfolders/lib/Versions/VersionsBackend.php:38
...
4. When I enabled the version app, this error disappeared

### Expected behaviour
no error

### Actual behaviour
Error: Interface 'OCA\Files_Versions\Versions\IVersionBackend' not found in /home/data/public_html/apps/groupfolders/lib/Versions/VersionsBackend.php:38

### Server configuration

**Operating system:**
Ubuntu 20.04.3 LTS
**Web server:**
Apache/2.4.41
**Database:**
Mysql Ver 8.0.28
**PHP version:**
PHP version: 7.4.3
**Nextcloud version:** (see Nextcloud admin page)
23.0.2
**Group folders version:**
11.1.2 
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from nextcloud  22.2.3.0
**Where did you install Nextcloud from: official homepage

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
No

### Client configuration
**Browser:**
Not applicable. Server error only
**Operating system:**
Not applicable.
#### Web server error log
<details>
<summary>Web server error log</summary>

not applicable 
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Error: Interface 'OCA\Files_Versions\Versions\IVersionBackend' not found in /home/data/public_html/apps/groupfolders/lib/Versions/VersionsBackend.php:38
Stack trace:
#0 /home/data/public_html/lib/composer/composer/ClassLoader.php(571): include()
#1 /home/data/public_html/lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /home/data/public_html/apps/groupfolders/lib/AppInfo/Application.php(99): spl_autoload_call()
#4 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(160): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo{closure}()
#5 /home/data/public_html/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility{closure}()
#6 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#7 /home/data/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(457): OC\AppFramework\Utility\SimpleContainer->query()
#8 /home/data/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#9 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\AppFramework\DependencyInjection\DIContainer->query()
#10 /home/data/public_html/apps/groupfolders/lib/AppInfo/Application.php(94): OC\AppFramework\Utility\SimpleContainer->get()
#11 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(160): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo{closure}()
#12 /home/data/public_html/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility{closure}()
#13 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#14 /home/data/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(457): OC\AppFramework\Utility\SimpleContainer->query()
#15 /home/data/public_html/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#16 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#17 /home/data/public_html/apps/groupfolders/lib/Command/Trashbin/Cleanup.php(52): OC\AppFramework\Utility\SimpleContainer->get()
#18 [internal function]: OCA\GroupFolders\Command\Trashbin\Cleanup->__construct()
#19 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(106): ReflectionClass->newInstanceArgs()
#20 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#21 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#22 /home/data/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#23 /home/data/public_html/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#24 /home/data/public_html/lib/private/Console/Application.php(217): OC\ServerContainer->query()
#25 /home/data/public_html/lib/private/Console/Application.php(128): OC\Console\Application->loadCommandsFromInfoXml()
#26 /home/data/public_html/console.php(98): OC\Console\Application->loadCommands()
#27 /home/data/public_html/occ(11): require_once('/home/data/publ...')

{"reqId":"xxx","level":4,"time":"2022-02-16T14:31:05+00:00","remoteAddr":"xxxxx","user":"xxxx","app":"no app in context","method":"POST","url":"/index.php/settings/apps/enable","message":"Could not boot files_trashbin: Interface 'OCA\\Files_Versions\\Versions\\IVersionBackend' not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36","version":"23.0.2.1","exception":{"Exception":"Error","Message":"Interface 'OCA\\Files_Versions\\Versions\\IVersionBackend' not found","Code":0,"Trace":[{"file":"/home/data/public_html/lib/composer/composer/ClassLoader.php","line":571,"function":"include"},{"file":"/home/data/public_html/lib/composer/composer/ClassLoader.php","line":428,"function":"Composer\\Autoload\\includeFile"},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"file":"/home/data/public_html/apps/groupfolders/lib/AppInfo/Application.php","line":99,"function":"spl_autoload_call"},{"file":"/home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php","line":160,"function":"OCA\\GroupFolders\\AppInfo\\{closure}","class":"OCA\\GroupFolders\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/home/data/public_html/3rdparty/pimple/pimple/src/Pimple/Container.php","line":118,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php","line":127,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"/home/data/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":457,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/home/data/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":435,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php","line":56,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/home/data/public_html/apps/groupfolders/lib/AppInfo/Application.php","line":94,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php","line":160,"function":"OCA\\GroupFolders\\AppInfo\\{closure}","class":"OCA\\GroupFolders\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/home/data/public_html/3rdparty/pimple/pimple/src/Pimple/Container.php","line":118,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php","line":127,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"/home/data/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":457,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/home/data/public_html/lib/private/ServerContainer.php","line":145,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/home/data/public_html/apps/files_trashbin/lib/AppInfo/Application.php","line":90,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/home/data/public_html/lib/private/AppFramework/Bootstrap/FunctionInjector.php","line":67,"function":"registerTrashBackends","class":"OCA\\Files_Trashbin\\AppInfo\\Application","type":"->"},{"file":"/home/data/public_html/lib/private/AppFramework/Bootstrap/BootContext.php","line":51,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\FunctionInjector","type":"->"},{"file":"/home/data/public_html/apps/files_trashbin/lib/AppInfo/Application.php","line":56,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\BootContext","type":"->"},{"file":"/home/data/public_html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":181,"function":"boot","class":"OCA\\Files_Trashbin\\AppInfo\\Application","type":"->"},{"file":"/home/data/public_html/lib/private/legacy/OC_App.php","line":206,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/home/data/public_html/lib/private/legacy/OC_App.php","line":140,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/home/data/public_html/apps/dav/lib/AppInfo/Application.php","line":171,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/home/data/public_html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":181,"function":"boot","class":"OCA\\DAV\\AppInfo\\Application","type":"->"},{"file":"/home/data/public_html/lib/private/legacy/OC_App.php","line":206,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/home/data/public_html/lib/private/legacy/OC_App.php","line":140,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/home/data/public_html/lib/base.php","line":986,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/home/data/public_html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/home/data/public_html/apps/groupfolders/lib/Versions/VersionsBackend.php","Line":38,"CustomMessage":"Could not boot files_trashbin: Interface 'OCA\\Files_Versions\\Versions\\IVersionBackend' not found"}}

</details>

#### Browser log
<details>
<summary>Browser log</summary>
not applicable
</details>

**Comment by shadowwa** [comment] 2022-02-19 15:26
I got the same bug but upgrading from a more recent version:
starting version 23.0.0 => no problem
upgrade to 23.0.2 => error describe by op

**Comment by acsfer** [comment] 2022-02-21 09:46
Is `files_versions` app enabled on your Nextcloud's?

**Comment by MikeEchoVoid** [comment] 2022-02-21 09:50
> Is `files_versions` app enabled on your Nextcloud's? @CarlSchwan if there is a dependency, shouldn't this be handled?

you mean "versions" application ? 
https://docs.nextcloud.com/server/23/user_manual/en/files/version_control.html

It was disabled before and the error message disappear when I enabled it.

**Comment by t3easy** [comment] 2022-02-21 16:06
We also have this fatal error in the log.

We have upgraded Nextcloud from 22.2.5 to 23.0.2 on a docker setup using the official images.
No errors in 22.2.5
Group folders app is enabled, versions app is disabled because we don't need that feature.

**Comment by MikeEchoVoid** [comment] 2022-02-21 17:14
What happens when you activate the versions app @t3easy ?

**Comment by t3easy** [comment] 2022-02-21 17:42
> What happens when you activate the versions app @t3easy ?

Error is gone. But we don't need/want versions.

**Comment by MikeEchoVoid** [comment] 2022-02-21 18:24
> > What happens when you activate the versions app @t3easy ?
> 
> Error is gone. But we don't need/want versions. And it was never a problem in v20, v21 or v22. There shouldn't be a dependency between this two apps.

Same for me @t3easy

**Comment by fschrempf** [comment] 2022-02-21 19:14
This looks like a duplicate of #1812, which has been fixed in #1849 and backported to NC 23 in #1863. Probably this fix hasn't been released yet.

**Closed by fschrempf** 2022-02-21 19:14 UTC
Labels: bug, 0. Needs triage

**Comment by t3easy** [comment] 2022-02-22 07:53
> This looks like a duplicate of #1812, which has been fixed in #1849 and backported to NC 23 in #1863. Probably this fix hasn't been released yet.

@fschrempf Seems so... Patch was merged on 7th Jan and 11.2.1 was released on 5th Jan.
When is the next release planned?
