### ISSUE TITLE
advanced permissions: who is allowed to edit the permissions?

### ISSUE THREAD

**Issue by schiessle** [nextcloud/groupfolders#400] opened 2019-04-25 17:36 UTC
After a short try of the new advanced permissions it looks like only admins can change the advanced group folder permissions. But what happens if no admin has access to the group folder, e.g. because non of the group members is an admin?

I think we should allow also group admins, to manipulate the permissions of their group folders.

**Comment by wiswedel** [comment] 2019-05-03 14:14
Duplicate of #366

**Comment by wiswedel** [comment] 2019-06-14 17:17
> add a column to the group folder settings where the admin configure the group folders to select the users which are allowed to manipulate the permissions

Keep in mind that the pickable users would need to be members of the previously selected groups.

We could substitute the "Advanced permissions" checkbox with that user selection.

@icewind1991 any opinion about this? This is a real production-blocker for larger organizations.

**Comment by juliushaertl** [comment] 2019-07-15 07:27
@schiessle @wiswedel Wouldn't it make more sense to give allow groups to either change the ACL or not? That way the actual user selection can also be managed by external user backends?

UI wise I have something like this in mind:
![image](https://user-images.githubusercontent.com/3404133/61200723-b28e4a00-a6e2-11e9-9d55-5c6d70767448.png)

**Comment by wiswedel** [comment] 2019-07-15 08:14
> @schiessle @wiswedel Wouldn't it make more sense to give allow groups to either change the ACL or not? That way the actual user selection can also be managed by external user backends?
> 
> UI wise I have something like this in mind:
> ![image](https://user-images.githubusercontent.com/3404133/61200723-b28e4a00-a6e2-11e9-9d55-5c6d70767448.png)

Totally agree. Best approach from my pov

**Comment by juliushaertl** [comment] 2019-07-15 11:53
Implementation is in https://github.com/nextcloud/groupfolders/pull/522, testing is very welcome

**Comment by nursoda** [comment] 2019-07-18 07:24
This is related to https://github.com/nextcloud/groupfolders/issues/400

**Comment by juliushaertl** [comment] 2019-07-18 07:27
@nursoda This is #400 :grin:

**Comment by nursoda** [comment] 2019-07-18 14:34
> @nursoda This is #400 grin

Sorry, I mixed both posts up, correct now, please delete off-topic

**Closed** 2019-08-23 17:05 UTC
Labels: enhancement
