### ISSUE TITLE
Upload on shared folder uses wrong path

### ISSUE THREAD

**Issue by KreativeKrise** [nextcloud/groupfolders#1579] opened 2021-06-28 08:18 UTC
### Steps to reproduce
1. Create a group folder
2. Create a folder inside the group folder
3. Share the nested folder with a guest user (a user who is not member of the group folder)
4. Login as guest user
5. Upload a file into the shared folder

### Expected behaviour
The file should be uploaded into the shared folder.

### Actual behaviour
The user gets the notification "An unknown error occurred".

In the system protocol you get the following error:

```
[core] Error: unable to rename, source directory is not writable : /var/www/vhosts/domain.tld/data/external share
```

It seems that the path is wrong and therefore the file can not be uploaded. The real path is `/var/www/vhosts/domain.tld/data/__groupfolders/1/external share`.

### Server configuration

**Operating system:** Debian 9 / Plesk 17.8

**Web server:** Apache2 with nginx proxy

**Database:** MariaDB 10.1.48

**PHP version:** 7.3.28

**Nextcloud version:** 20.0.10

**Group folders version:** 8.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from an older Nextcloud install

**Where did you install Nextcloud from:**  nextcloud.com archive file

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Google Chrome 91

**Operating system:** Windows 10 Pro

### Logs

<details>
<summary>Nextcloud protocol</summary>

[core] Error: unable to rename, source directory is not writable : /var/www/vhosts/domain.tld/data/external share

[webdav] Error: renaming part file to final file failed $renameOkay: false, $fileExists: false)

[webdav] Fatal: Sabre\DAV\Exception: Could not rename part file to final file at <<closure>>

0. /var/www/vhosts/domain.tld/apps/dav/lib/Connector/Sabre/Directory.php line 156
   OCA\DAV\Connector\Sabre\File->put(null)
1. /var/www/vhosts/domain.tld/3rdparty/sabre/dav/lib/DAV/Server.php line 1104
   OCA\DAV\Connector\Sabre\Directory->createFile("upload_test.png", null)
2. /var/www/vhosts/domain.tld/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 527
   Sabre\DAV\Server->createFile("external share/upload_test.png", null, null)
3. /var/www/vhosts/domain.tld/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
   Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
4. /var/www/vhosts/domain.tld/3rdparty/sabre/dav/lib/DAV/Server.php line 474
   Sabre\DAV\Server->emit("method:PUT", [Sabre\HTTP\Requ ... }])
5. /var/www/vhosts/domain.tld/3rdparty/sabre/dav/lib/DAV/Server.php line 251
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
6. /var/www/vhosts/domain.tld/3rdparty/sabre/dav/lib/DAV/Server.php line 319
   Sabre\DAV\Server->start()
7. /var/www/vhosts/domain.tld/apps/dav/appinfo/v1/webdav.php line 84
   Sabre\DAV\Server->exec()
8. /var/www/vhosts/domain.tld/remote.php line 167
   require_once("/var/www/vhosts ... p")

[PHP] Error: Error: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/domain.tld/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/vhosts/domain.tld/apps/dav/lib/Connector/Sabre/File.php#691 at <<closure>>

0. <<closure>>
   OC\Log\ErrorHandler::onError(2, "Cannot modify h ... )", "/var/www/vhosts ... p", 691, {string: "X-Hash ... "})
1. /var/www/vhosts/domain.tld/apps/dav/lib/Connector/Sabre/File.php line 691
   header("X-Hash-SHA256:  ... d")
2. /var/www/vhosts/domain.tld/apps/dav/lib/Connector/Sabre/File.php line 195
   OCA\DAV\Connector\Sabre\File->header("X-Hash-SHA256:  ... d")
3. <<closure>>
   OCA\DAV\Connector\Sabre\File->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
4. /var/www/vhosts/domain.tld/lib/private/Files/Stream/HashWrapper.php line 71
   call_user_func(Closure {}, "*** sensitive parameter replaced ***")
5. /var/www/vhosts/domain.tld/3rdparty/sabre/dav/lib/DAV/Server.php line 319
   OC\Files\Stream\HashWrapper->stream_close()
6. /var/www/vhosts/domain.tld/apps/dav/appinfo/v1/webdav.php line 84
   Sabre\DAV\Server->exec()
7. /var/www/vhosts/domain.tld/remote.php line 167
   require_once("/var/www/vhosts ... p")

[PHP] Error: Error: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/domain.tld/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/vhosts/domain.tld/apps/dav/lib/Connector/Sabre/File.php#691 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "Cannot modify h ... )", "/var/www/vhosts ... p", 691, {string: "X-Hash ... "})
 1. /var/www/vhosts/domain.tld/apps/dav/lib/Connector/Sabre/File.php line 691
    header("X-Hash-SHA1: 20 ... e")
 2. /var/www/vhosts/domain.tld/apps/dav/lib/Connector/Sabre/File.php line 192
    OCA\DAV\Connector\Sabre\File->header("X-Hash-SHA1: 20 ... e")
 3. <<closure>>
    OCA\DAV\Connector\Sabre\File->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/vhosts/domain.tld/lib/private/Files/Stream/HashWrapper.php line 71
    call_user_func(Closure {}, "*** sensitive parameter replaced ***")
 5. <<closure>>
    OC\Files\Stream\HashWrapper->stream_close()
 6. /var/www/vhosts/domain.tld/3rdparty/icewind/streams/src/Wrapper.php line 132
    fclose(null)
 7. /var/www/vhosts/domain.tld/lib/private/Files/Stream/HashWrapper.php line 75
    Icewind\Streams\Wrapper->stream_close()
 8. /var/www/vhosts/domain.tld/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    OC\Files\Stream\HashWrapper->stream_close()
 9. /var/www/vhosts/domain.tld/apps/dav/appinfo/v1/webdav.php line 84
    Sabre\DAV\Server->exec()
10. /var/www/vhosts/domain.tld/remote.php line 167
    require_once("/var/www/vhosts ... p")

[PHP] Error: Error: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/domain.tld/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/vhosts/domain.tld/apps/dav/lib/Connector/Sabre/File.php#691 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "Cannot modify h ... )", "/var/www/vhosts ... p", 691, {string: "X-Hash ... "})
 1. /var/www/vhosts/domain.tld/apps/dav/lib/Connector/Sabre/File.php line 691
    header("X-Hash-MD5: 8b1 ... 8")
 2. /var/www/vhosts/domain.tld/apps/dav/lib/Connector/Sabre/File.php line 189
    OCA\DAV\Connector\Sabre\File->header("X-Hash-MD5: 8b1 ... 8")
 3. <<closure>>
    OCA\DAV\Connector\Sabre\File->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/vhosts/domain.tld/lib/private/Files/Stream/HashWrapper.php line 71
    call_user_func(Closure {}, "*** sensitive parameter replaced ***")
 5. <<closure>>
    OC\Files\Stream\HashWrapper->stream_close()
 6. /var/www/vhosts/domain.tld/3rdparty/icewind/streams/src/Wrapper.php line 132
    fclose(null)
 7. /var/www/vhosts/domain.tld/lib/private/Files/Stream/HashWrapper.php line 75
    Icewind\Streams\Wrapper->stream_close()
 8. <<closure>>
    OC\Files\Stream\HashWrapper->stream_close()
 9. /var/www/vhosts/domain.tld/3rdparty/icewind/streams/src/Wrapper.php line 132
    fclose(null)
10. /var/www/vhosts/domain.tld/lib/private/Files/Stream/HashWrapper.php line 75
    Icewind\Streams\Wrapper->stream_close()
11. /var/www/vhosts/domain.tld/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    OC\Files\Stream\HashWrapper->stream_close()
12. /var/www/vhosts/domain.tld/apps/dav/appinfo/v1/webdav.php line 84
    Sabre\DAV\Server->exec()
13. /var/www/vhosts/domain.tld/remote.php line 167
    require_once("/var/www/vhosts ... p")

</details>

**Comment by fschrempf** [comment] 2021-06-30 18:15
Closed as duplicate of #1445 and #1453 which is fixed in v21.0.3 Please let me know if you think this is wrong.

**Closed by fschrempf** 2021-06-30 18:15 UTC
Labels: 0. Needs triage, bug
