### ISSUE TITLE
ACL: Access Control List missing for group or multiple users

### ISSUE THREAD

**Issue by caguiar** [nextcloud/groupfolders#894] opened 2020-05-02 11:59 UTC
Nextcloud: 18.0.4
Group Folders App: 6.0.6
Browser: Firefox 75 (on Ubuntu Linux)
If I configure a single user as admin to set advanced permissions, this user is presented with the ACL list on the Share tab, and thus this user can configure advanced permissions.
If I configure a group, to which this same users belongs too, and set that group as admin to set advanced permissions, when this user goes to the Share tab, the ACL list is missing.
The same happens if instead of a sigle user, additional users are configured as admin to set advanced permissions, no ACL list.

**Comment by schiessle** [comment] 2020-05-07 11:25
I can second it. I have the same problem even when I set a single user as admin for the advances permissions:

Group folder settings:

![image](https://user-images.githubusercontent.com/1589737/81289072-0ac57c80-9066-11ea-98d4-246a70f5b678.png)

Share sidebar, as you can see there are no advanced permissions:

![image](https://user-images.githubusercontent.com/1589737/81288950-d8b41a80-9065-11ea-97c1-c21d7cbdc811.png)

**Comment by maxxer** [comment] 2020-05-13 05:18
Could be a duplicate of #774?

**Comment by maxxer** [comment] 2020-05-13 05:46
Is it possible to have an update? It's confusing and problematic for users

**Comment by juliushaertl** [comment] 2020-05-13 06:22
Any error reported in the browser console when you open the sharing sidebar?

**Comment by caguiar** [comment] 2020-05-13 14:02
And I think it is related to these other reported issues:
https://github.com/nextcloud/groupfolders/issues/774
https://github.com/nextcloud/groupfolders/issues/749

The question is that the symptom is intermittent. Sometimes you get the advanced permissions on the sharing sidebar, and sometimes you don't ... and when they don't appear to get them back again it is not easy ... here are a few things I have tried:
- logout and login;
- logout, close browser, open browser and login;
- and last, which works most of the time, is to disable advance permissions on a folder and re-enable them (this works for a group or for single user).
No error is reported in the browser, nor is any error registered on the log.

**Comment by juliushaertl** [comment] 2020-05-15 06:48
I've seen this happening now as well. My guess is that this depends on some timing during the files sidebar and the registation of the acl user interface in the sharing tab. I'll have a closer look.

**Comment by laarisyko** [comment] 2020-07-22 09:44
Hi Julius,

I hope your fine :) When it is not loading correctly, I get the following in the browser console:

```
Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://cloud.irubis.com/apps/groupfolders/build/3.js
Source-Map-Adresse: 3.js.map
```

If I click on: https://cloud.irubis.com/apps/groupfolders/build/3.js
It seems that at least Firefox is not able to write your last name correctly: So HÃ¤rtl instead fo Härtel

**Comment by fschrempf** [comment] 2021-01-04 14:48
While it felt like this does not happen that often with NC 19, it seems like with NC 20 it starts to get really annoying again for me. There are a whole lot of duplicates like: #774, #749, #466, #1014 and probably more that I have missed.

This is not related to the browser or anything and as far as I can see there is no reliable workaround or fix.

@juliushaertl and maintainers: Is there any of you who is willing to close the duplicates and merge them to a single issue to properly track this? Are #917 didn't fix this, are there any other approaches?

**Comment by juliushaertl** [comment] 2021-01-05 10:38
There was a follow-up fix with https://github.com/nextcloud/groupfolders/pull/1086 that should be part of the latest releases. Is this still happening for you with 8.2? Any error in the browser console?

**Comment by fschrempf** [comment] 2021-01-05 10:49
Yes, I'm on 8.2.0 and yesterday I wasn't able to see the ACL controls in the sidebar with Firefox and Chromium. Today it seems to work and I can't reproduce it at the moment. I will continue to check this and look for errors in the console if the problem happens again.

**Comment by fschrempf** [comment] 2021-01-05 10:52
@juliushaertl I think #774 is another duplicate for you to close.

**Comment by dwaxweiler** [comment] 2021-02-08 10:57
I have a user with the same issue: If they use Safari 14.0.1, the option is not shown, while with Firefox 85.0 it is.

**Comment by pierreozoux** [comment] 2021-03-14 20:12
could it be related to adblocker or browser plugins?

**Comment by laarisyko** [comment] 2022-11-16 09:56
I had the same issue 2 years ago, after upgrading to NC 25 it just reappeared :( Anyone having the same issue with NC 25?

**Comment by Chartman123** [comment] 2022-11-16 11:11
@laarisyko see #2177

**Comment by fschrempf** [comment] 2022-11-16 18:53
This is a similar issue as https://github.com/nextcloud/groupfolders/issues/2148, but targeting older versions and probably with different root cause.  
Anyway this issue is outdated and it seems unlikely that this issue still persists in recent stable versions. Let's close it for now.

**Closed by fschrempf** 2022-11-16 18:53 UTC
Labels: bug, high, needs info, 1. to develop, ui, feature: acl
