### ISSUE TITLE
Add the ability to autocreate a folder for each group

### ISSUE THREAD

**Issue by yodatak** [nextcloud/groupfolders#815] opened 2020-03-22 02:17 UTC
I could be cool to automaticly via button or occ create a folder for each group

**Comment by pierreozoux** [comment] 2021-04-02 15:16
closing as a duplicate of https://github.com/nextcloud/groupfolders/issues/815

**Comment by fschrempf** [comment] 2021-04-02 15:18
> closing as a duplicate of #815

This is #815 :smile:

**Comment by pierreozoux** [comment] 2021-04-02 17:57
Arf :) there was another one, cant find it on the phone :/

**Comment by pierreozoux** [comment] 2021-04-05 06:07
Here it is https://github.com/nextcloud/groupfolders/issues/312

**Closed by pierreozoux** 2021-04-05 06:07 UTC
Labels: 0. Needs triage, duplicate, enhancement
