### ISSUE TITLE
Permission to disallow downloads

### ISSUE THREAD

**Issue by DesertCookie** [nextcloud/groupfolders#2424] opened 2023-06-08 17:57 UTC
I think there is a lack of granularity with the current permissions system within group folders.

It would make sense to allow or disallow certain groups from downloading files. This way one could, for example, allow certain users to only view images/videos, but not download them (of course, if one really wants to, he'll find a way, at least with videos where it doesn't only send a preview image).

A current workaround of ours is to only send certain users external links that have the option to disallow downloads. This way they can, for example, still collaborate by uploading or editing (e.g. documents), but have a harder time downloading all the stuff we might not want them to have sitting in their downloads folder forever.

_There are several requests to work this into the main files app already. Since I couldn't find one for support here, I thought I'd create one for the record. Edit: Apparently [♥someone is working on it](https://github.com/nextcloud/server/pull/32482)...?_

**Comment by provokateurin** [comment] 2024-09-17 18:16
Duplicate of https://github.com/nextcloud/groupfolders/issues/1586

**Closed by provokateurin** 2024-09-17 18:16 UTC
Labels: enhancement, 0. Needs triage, feature: acl
