### ISSUE TITLE
After updating to 28.0.8 the group folders are shown numerically in the UI path

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/groupfolders#3077] opened 2024-07-24 18:48 UTC
I have updated my NC instance to 28.0.8 and found that the group folders are shown numerically in the path shown above the list of files instead of their names.

This is the group folder it is shown in text as it is:
![Знімок екрана з 2024-07-24 21-44-49](https://github.com/user-attachments/assets/83256325-caa2-4e92-bc0c-fc90aabf721a)

Here it is shown numerically:
![Знімок екрана з 2024-07-24 21-46-05](https://github.com/user-attachments/assets/69605872-1728-4776-a278-6aa4adde6fba)

And here I am going into the subfolder and observing the number instead of the name of the group folder:
![Знімок екрана з 2024-07-24 21-45-49](https://github.com/user-attachments/assets/83226b38-d530-42c7-be95-5a8cf521cfd9)

Is that a new feature or a bug?

**Comment by Chartman123** [comment] 2024-07-24 21:31
Duplicate of #3068

**Closed** 2024-07-24 21:32 UTC
Labels: bug, 0. Needs triage
