### ISSUE TITLE
A new group folder deletes exiting ones

### ISSUE THREAD

**Issue by Weberknecht37** [nextcloud/groupfolders#126] opened 2018-06-18 15:32 UTC
I am recently testing groupfolders for an educational environment. I had an existing folder, we name it "testfolder" with some test-data. Then i used groupfolders to share this folder. Going back to the overview, "testfolder" was empty! I got no warning that this could happen and the deleted files are not in the deleted files folder.

**Comment by Nils160988** [comment] 2018-07-09 21:07
Duplicate of https://github.com/nextcloud/groupfolders/issues/18

**Comment by marianoju** [comment] 2018-07-11 15:58
+1

**Comment by icewind1991** [comment] 2018-07-12 14:39
closing as duplicate

**Closed by icewind1991** 2018-07-12 14:39 UTC

**Comment by NOULeENGINEER** [comment] 2020-05-17 04:10
How can i get the name of the group folder by the objectid ? i can't find the table that contains this information in the DB. i need this information ASAP
