### ISSUE TITLE
TypeError OCA\GroupFolders\Versions\VersionsBackend::getVersionFolderForFile(): Argument #1 ($file) must be of type OCP\Files\File, OC\Files\FileInfo given

### ISSUE THREAD

**Issue by kaikli** [nextcloud/groupfolders#2972] opened 2024-05-27 07:33 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Description
```plain
TypeError OCA\GroupFolders\Versions\VersionsBackend::getVersionFolderForFile(): Argument #1 ($file) must be of type OCP\Files\File, OC\Files\FileInfo given, called in /srv/http/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 92
Error while running background job OCA\GroupFolders\BackgroundJob\ExpireGroupVersions (id: 37, arguments: null) 
```

### Server configuration

**Operating system:** Arch Linux

**Web server:**

**Database:** 11.3.2-MariaDB
**PHP version:** PHP 8.3.7 (cli)
**Nextcloud version:** 29.0.1
**Group folders version:** 17.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:** updated
**Where did you install Nextcloud from:** nextcloud.com
**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

#### Nextcloud log (data/nextcloud.log)

```
{"reqId":"NYJJUvDABuRFAUngkT6I","level":3,"time":"2024-05-27T06:16:49+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 37, arguments: null)","userAgent":"--","version":"29.0.1.1","exception":{"Exception":"TypeError","Message":"OCA\\GroupFolders\\Versions\\VersionsBackend::getVersionFolderForFile(): Argument #1 ($file) must be of type OCP\\Files\\File, OC\\Files\\FileInfo given, called in /srv/http/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 92","Code":0,"Trace":[{"file":"/srv/http/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php","line":92,"function":"getVersionFolderForFile","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->"},{"file":"/srv/http/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":81,"function":"getVersionsForFile","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->"},{"file":"/srv/http/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":60,"function":"expireFolder","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->"},{"file":"/srv/http/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php","line":43,"function":"expireAll","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->"},{"file":"/srv/http/nextcloud/lib/public/BackgroundJob/Job.php","line":80,"function":"run","class":"OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions","type":"->"},{"file":"/srv/http/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":102,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/srv/http/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":92,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/srv/http/nextcloud/cron.php","line":176,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/srv/http/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php","Line":78,"message":"Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 37, arguments: null)","exception":{},"CustomMessage":"Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 37, arguments: null)"}}
```

**Comment by poldi171254** [comment] 2024-05-28 03:17
I have the same issue and my config is identical apart from running on Ubuntu

**Comment by solracsf** [comment] 2024-05-28 07:53
Duplicate of https://github.com/nextcloud/groupfolders/issues/2964

**Closed by solracsf** 2024-05-28 07:53 UTC
Labels: bug, 0. Needs triage
