### ISSUE TITLE
Upload Error in Shared folders

### ISSUE THREAD

**Issue by dominik34** [nextcloud/groupfolders#1576] opened 2021-06-25 15:59 UTC
**Upload in a shared subfolder of a groupfolder is not possible.
I get the error: "Could not rename part file to final file"**

And in the log it shows the following (first one three times):

PHP - Error: Cannot modify header information - headers already sent by (output started at /data/nextcloud/3rdparty/sabre/http/lib/Sapi.php:132) at /data/nextcloud/apps/dav/lib/Connector/Sabre/File.php#691

webdav - Sabre\DAV\Exception: Could not rename part file to final file

webdav - renaming part file to final file failed $renameOkay: false, $fileExists: false)#

core - unable to rename, source directory is not writable : /data/nextcloud/data/01 Leitung/08 IPF/IPF 2020/ARISE 2021

I am using:
Groupfolder Version
8.2.2
Nexcloud Version:
20.0.10

**Comment by fschrempf** [comment] 2021-06-27 15:45
Closed as duplicate of #1445 and #1453.

**Closed by fschrempf** 2021-06-27 15:45 UTC
Labels: 0. Needs triage, bug
