### ISSUE TITLE
Log changes to advanced permissions for group folders in the admin_audit log.

### ISSUE THREAD

**Issue by devi69** [nextcloud/groupfolders#1756] opened 2021-11-17 02:08 UTC
**Is your feature request related to a problem? Please describe.**
It is not possible to see from the log when users or groups were added or removed from the "Advanced Permissions" of the group folder. It would be great if it could be recorded in the audit.log of the admin_audit app.

**Additional context**
![Groupfolders_Advanced_Permissions](https://user-images.githubusercontent.com/23556623/142094715-bc94face-7f37-417d-96ec-12ac8609af34.png)

**Comment by fschrempf** [comment] 2021-11-17 10:55
@devi69 Please check the existing issues for duplicates. This was already reported a couple of days ago. Thanks!
Closing as duplicate of #1744.

**Closed by fschrempf** 2021-11-17 10:55 UTC
Labels: enhancement, 0. Needs triage

**Comment by devi69** [comment] 2021-11-18 07:14
@fschrempf Thanks for letting me know. I think it would be nice if changes to "Advanced Permissions" were recorded in the audit log. #1744 seems to be talking about ACLs for group folders, but does it include "Advanced Permissions"?

**Comment by fschrempf** [comment] 2021-11-18 09:37
@devi69 "Advanced Permissions" and "ACLs" are different terms for the same feature in the groupfolders app.
