### ISSUE TITLE
Subfolder not available for sync when parent folder has no read permission

### ISSUE THREAD

**Issue by hokascha** [nextcloud/groupfolders#1089] opened 2020-10-16 10:41 UTC
I have a group folder containing some project folders. We assign project members all permissions to their project folders. Sometimes, we need to give access to specific users (not belonging to the regular project team) on specific sub-folders of our project folders. Doing that shows the main project folder is not showing up for these users, as they do not have any rights on that (parent) project folder. 

Expected behavior: When a user has at least read permissions on any sub-folder, the parent folder should show up for synchronisation and on the web allowing the user to travel through the directoy structure.

Partial solution for now: Add read permission for that user to the parent folder. Caveat: The user then has read access to all other sub-folders. You have to manually and explicitly reject read permissions on those.

**Comment by pierreozoux** [comment] 2021-03-15 07:39
It looks to me as intended.

It works the same way on linux.

Closing as wontfix.

If you have a better idea with a ux proposal, we might reconsider.

**Closed by pierreozoux** 2021-03-15 07:39 UTC
Labels: 0. Needs triage, acl, enhancement, wontfix
