### ISSUE TITLE
Groupfolder not created

### ISSUE THREAD

**Issue by Phaeton20** [nextcloud/groupfolders#1425] opened 2021-04-07 18:26 UTC
I insert a groupname and press create. The browser loads something and doesnt vcreate a group folder
### System Information:
Version: 9.0.0
PHP Version: 7.4.16

**Comment by fschrempf** [comment] 2021-04-07 19:29
What NC version do you use?
Does this happen every time you create a groupfolder?
Does the UI not show the groupfolder or is it really not created?
Are there any errors in the logs?
Which browser do you use?
Can you try with a different browser and/or disable all plugins like adblockers, etc?

**Comment by pierreozoux** [comment] 2021-04-08 10:58
Looks a duplicate of https://github.com/nextcloud/groupfolders/issues/1295

**Closed by pierreozoux** 2021-04-08 10:58 UTC
Labels: 0. Needs triage, bug, needs info

**Comment by Phaeton20** [comment] 2021-04-08 13:39
### Server configuration detail

Operating system: FreeBSD 12.2-RELEASE-p3 FreeBSD 12.2-RELEASE-p3 7851f4a452d(HEAD) TRUENAS amd64

Webserver: nginx/1.18.0 (fpm-fcgi)

Database: mysql 5.7.33

PHP version: 7.4.16

Modules loaded: Core, date, libxml, pcre, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, apcu, bcmath, bz2, ctype, curl, dom, mbstring, fileinfo, filter, gd, gmp, iconv, imagick, intl, json, ldap, exif, openssl, PDO, posix, SimpleXML, xml, xmlwriter, zip, zlib, pdo_mysql, xmlreader, xsl, Zend OPcache

Nextcloud version: 21.0.0 - 21.0.0.18

Updated from an older Nextcloud/ownCloud or fresh install: fresh from trueNAS Plugin

Where did you install Nextcloud from: unknown

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - admin_audit: 1.11.0
 - announcementcenter: 5.0.0
 - apporder: 0.12.0
 - auto_groups: 1.3.0
 - calendar: 2.2.0
 - circles: 0.21.0
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 3.5.1
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.17.1
 - deck: 1.3.2
 - extract: 1.3.1
 - federatedfilesharing: 1.11.0
 - files: 1.16.0
 - files_accesscontrol: 1.11.0
 - files_antivirus: 3.2.0
 - files_automatedtagging: 1.11.0
 - files_markdown: 2.3.3
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - forms: 2.2.4
 - group_default_quota: 0.1.0
 - group_everyone: 0.1.7
 - groupfolders: 9.0.0
 - integration_gitlab: 1.0.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - music: 1.1.0
 - notes: 4.0.4
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - password_policy: 1.11.0
 - photos: 1.3.0
 - polls: 1.8.1
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - recommendations: 1.0.0
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - support: 1.4.0
 - survey_client: 1.9.0
 - systemtags: 1.11.0
 - text: 3.2.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - twofactor_email: 2.0.0
 - twofactor_totp: 6.0.0
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - workflow_ocr: 1.21.0
 - workflow_pdf_converter: 1.6.0
 - workflowengine: 2.3.0
Disabled:
 - encryption
 - federation
 - files_external
 - firstrunwizard
 - keeweb
 - nextcloud_announcements
 - onlyoffice
 - user_ldap



</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "apps_paths": [
        {
            "path": "\/usr\/local\/www\/nextcloud\/apps",
            "url": "\/apps",
            "writable": true
        },
        {
            "path": "\/usr\/local\/www\/nextcloud\/apps-pkg",
            "url": "\/apps-pkg",
            "writable": true
        }
    ],
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "192.168.178.27",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "21.0.0.18",
    "overwrite.cli.url": "http:\/\/localhost",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "app_install_overwrite": [
        "flowupload"
    ]
}


</details>

External storages: files_external is disabled

Encryption: no

User-backends:

OC\User\Database

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0
