### ISSUE TITLE
[25] Missing ACL panel in share dialog

### ISSUE THREAD

**Issue by PVince81** [nextcloud/groupfolders#2177] opened 2022-11-08 12:31 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Setup NC 20.0.14
2. Enable group folders
3. Create a group folder "/gf1"
4. Make it applicable to group "admin"
5. Allow the user "admin" to set advanced permissions there
6. Open the share panel for "/gf1"
7. Try to edit ACLs

### Expected behaviour
ACL panel visible

### Actual behaviour
ACL panel not visible

### Server configuration

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** stable25

**Group folders version:**

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
No errors there

**Comment by CarlSchwan** [comment] 2022-11-08 12:42
It was fixed last week but we need a new release

**Comment by CarlSchwan** [comment] 2022-11-08 12:42
See https://github.com/nextcloud/groupfolders/pull/2170

**Comment by szaimen** [comment] 2022-11-15 14:48
What is missing for a new groupfolders release? :)

**Comment by PVince81** [comment] 2022-11-16 08:59
as discussed, @icewind1991 will take care of the release in the next days

**Comment by fschrempf** [comment] 2022-11-16 18:49
Please don't spread a single topic over multiple duplicate issues. Closing as duplicate of #2148.

**Closed by fschrempf** 2022-11-16 18:49 UTC
Labels: bug, 1. to develop, regression
