### ISSUE TITLE
Everyone with access to the group folder can rename it - groupfolder is unusable afterwards

### ISSUE THREAD

**Issue by lordoftheboard** [nextcloud/groupfolders#48] opened 2017-08-02 13:42 UTC
everyone with access to the group folder can rename it. afterwards it seems to be like this:

a local copy (unshared, not a group folder) of the group folder is made to the users nextcloud
the original group folder is still here - but files in it are not usable any more
sometimes it is even not possible to create new files anymore

the best would be probably to prevent users from renaming the group folder.

**Comment by kosli** [comment] 2017-08-03 19:32
When I rename it as a normal user via the web UI, then i have a copy of that folder, just without the "GS icon". Doing the same with the client gets random behaviour (some files "moved" to the new folder, some not etc).

**Comment by icewind1991** [comment] 2017-08-15 14:59
Duplicate of https://github.com/nextcloud/groupfolders/issues/48 which is fixed in Nextcloud core (12.0.1 iirc)

**Closed by icewind1991** 2017-08-15 14:59 UTC

**Comment by kosli** [comment] 2017-08-15 15:03
@icewind1991 i think #48 is a typo because this HERE IS #48 ?
