### ISSUE TITLE
Group Folders will not show up if group has only one member

### ISSUE THREAD

**Issue by cyclinggeorgian** [nextcloud/groupfolders#1200] opened 2020-12-28 12:22 UTC
When creating Group Folder and assigning a group to it which contains only one user that folder will not show up in folder list of that particular user.
Expected behavior would be for Group Folders to show up in the list of any/every user of that particular group, regardless of how many users that group contains.
How to reproduce:
- create Group Folder
- assign a group to it. make sure that this group has only one member.
- check your folder list (group folder is not there)
- add another member to the group
- check file list again (group folder is in the list)

I do have to add a side-note (although i doubt it plays a role here) - i use LDAP as a auth backend and group management as well.

**Comment by Chartman123** [comment] 2021-01-04 13:52
Might be indeed LDAP related as I couldn't reproduce it right now on 20.0.4 and groupfolders 8.2.0.

**Comment by pierreozoux** [comment] 2021-03-15 16:37
Couldn't reproduce neither.

**Comment by pierreozoux** [comment] 2021-03-15 16:38
Can you give us the versions, the list of apps you are using and if you found a workaound?

**Comment by cyclinggeorgian** [comment] 2021-03-16 12:42
> Can you give us the versions, the list of apps you are using and if you found a workaound?

Unfortunately at this time my NC environment is not representative of the initial situation any more. But when i submitted the bug report it was clean install of 20.04 version with only "two factor authentication" and "ldap" apps install and enabled. Next to whatever apps are preinstalled en enabled on a fresh install instance.
I was planning to run a recovery procedure to test of my backups... i could try to replicate that situation. Give me a week to get back on this issue with more details. 

PS and as a workaround i remember creating a dummy ldap user and adding it to the group. Dummy user without access rights of course ;-).

**Comment by pierreozoux** [comment] 2021-03-16 14:16
As you want with the nbackup and recover, if you don't have it anymore, let's close it.

**Closed** 2021-04-02 15:01 UTC
Labels: 0. Needs triage, bug, ldap, needs info
