### ISSUE TITLE
Preview in shared group folder not working

### ISSUE THREAD

**Issue by santhrax** [nextcloud/groupfolders#67] opened 2017-09-28 22:42 UTC
when group folder is shared via link user can access it and download the files but it is not possible to run the preview for photos

Error! Could not generate a preview of this file.

preview in "normal" shared folder working fine

**Comment by icewind1991** [comment] 2018-11-27 16:32
I can't reproduce this issue, previews show as expected when link-sharing a group folder

**Comment by svenb1234** [comment] 2020-04-06 19:28
Can this issue be be closed?

**Comment by ZeikoFr** [comment] 2020-12-06 13:14
@juliushaertl We can close this one imo

**Closed** 2020-12-07 06:12 UTC
