### ISSUE TITLE
Crumb trail does not show correct path, changes to number when selecting folder

### ISSUE THREAD

**Issue by Omaha2002** [nextcloud/groupfolders#3125] opened 2024-08-18 15:22 UTC
### Steps to reproduce
1. select a subfolder in the tree
2. for a brief moment the name of the subfolder appears in the crumb trail
3. it then changes to a number

### Expected behaviour
the correct subfoldername should be visible in the crumb trail

### Actual behaviour
a number appears after briefly showing the correct foldername

### Server configuration

both Ubuntu 22.04 local installation and Nextcloud AOI installation

Nextcloud 29.0.4
Groupfolders 17.0.2

Groupfolders selection of subfolders:

https://github.com/user-attachments/assets/e3e8474b-38ac-45f2-bb9d-b51c3cddc070

Not groupfolders don't show this behaviour:

https://github.com/user-attachments/assets/410513f6-1269-4ffc-84f8-192f772a6d0f

**Comment by dunz0r** [comment] 2024-08-19 12:15
I can verify that this is happening with Nextcloud 29.0.4 and Groupfolders 17.0.2. Any logs I can help with?

**Comment by ThibautPlg** [comment] 2024-08-19 15:55
Duplicate of https://github.com/nextcloud/groupfolders/issues/3068 it will probably be fixed in the future release. 

Hotfix is quite simple if needed: https://github.com/nextcloud/server/pull/46694/files

**Comment by joshtrichards** [comment] 2024-09-09 21:25
Released in 29.0.5 and 28.0.9 maintenance releases.

**Closed** 2024-09-09 21:25 UTC
Labels: bug, 0. Needs triage
