### ISSUE TITLE
[Req] Add nested group folders

### ISSUE THREAD

**Issue by sonaro** [nextcloud/groupfolders#92] opened 2018-02-13 22:09 UTC
It would be helpful to have nested group folders, since we have some systems with 30+ shared folders that should not be deleted / moved / renamed under a main shared folder.

Example:
GRP-MainShared/
GRP-MainShared/GRP-Timesheets/
GRP-MainShared/GRP-Timesheets/DwightSchrute/  <--per user sharing (additional feature)
GRP-MainShared/GRP-Accounting/
GRP-MainShared/GRP-Operations/
GRP-MainShared/GRP-Marketing/

**Comment by randomnickname1337** [comment] 2018-03-28 09:25
I have same situation , i really want this feature ... 
I got more group folders with different access rights and different users and i need them to hide inside one directory. Because users have too many directories in their cloud ...

**Comment by Sunsheep** [comment] 2018-06-16 15:33
As @randomnickname1337 said: Nested group folders with permission setting are a must have for a company.  

Companies often work with a fixed folder structure that needs to prevent. Also often, not all Users/Workers have permission too access all project specific folders. Sharing with users/groups would clutter the root dir of that user, which lead to unstructured workflows.

To make it clear - an example of a typical workplace file-structure:

- Projects/
| - Project X/    --> only users assigned to group projectX can access
| | - Engineering/
| | - Documents/
| | - etc/
| - Project Y/   --> only users assigned to group projectY can access
| | - Engineering/
| | - Documents/
| | - etc/

**Comment by Sunsheep** [comment] 2018-06-17 10:21
Actually it is working. You can create a Directory "Project" which is assigned to the group "engineering", then you can create a subdirectory "Project/Project X" and can assign users of the group "engineering" to this subdirectory as a special projectgroup like "ProjectX".

Only the GUI needs some adaption.

**Comment by sunjam** [comment] 2018-07-29 18:54
Nesting works for me in 13.0.4.  Just needs documentation.  You can write the nested directories in manually.  Would benefit from a folder selector from the GUI.

Example:`
/Documents/Shared/Gaming`

**Comment by icewind1991** [comment] 2018-11-28 12:47
Child group folders not inheriting quota from their parents in intended behavior, having the option to have them inherit the parent quota sounds like an interesting features but brings some technical problems to overcome and is not planned at the moment.

**Comment by icewind1991** [comment] 2018-11-28 12:48
I'll close this issue for now as nested group folders are possible as described above, feel free to open a new ticket about inheriting quota

**Closed by icewind1991** 2018-11-28 12:48 UTC
