### ISSUE TITLE
Group Folder titles in breadcrumbs menu are incorrect

### ISSUE THREAD

**Issue by nooblag** [nextcloud/groupfolders#3068] opened 2024-07-19 05:43 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Update to Nextcloud 29.0.4
2. Enter a group folder and click around the directory tree

### Expected behaviour
Folder name displayed should be the name of the folder, not the name of the folder from the file system.

### Actual behaviour
Name from file system is displayed.

![Screenshot from 2024-07-19 15-35-26](https://github.com/user-attachments/assets/cece5898-6fe9-4cca-a423-40a7385efc3a)

![Screenshot from 2024-07-19 15-44-08](https://github.com/user-attachments/assets/2dd79e6b-063a-4024-8623-6379163a1b47)

### Server configuration

**Operating system:** Ubuntu 22.04.4 LTS

**Web server:** nginx/1.18.0 (Ubuntu) 

**Database:** mariadb  Ver 15.1 Distrib 10.6.18-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

**PHP version:** PHP 8.2.21 (cli) (built: Jul  4 2024 16:26:28) (NTS)

**Nextcloud version:** (see Nextcloud admin page) 29.0.4.1

**Group folders version:** 17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** nextcloud.com

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No/none.

### Client configuration
**Browser:** Firefox 128.0

**Operating system:** Linux

#### Browser log
<details>
<summary>Browser log</summary>

```
[DEBUG] files: Directory contents changed 
Object { app: "files", uid: "***redacted***", level: 0, view: {…}, folder: {…}, contents: [] }
​
app: "files"
​
contents: Array []
​
folder: Object { _data: Getter & Setter, _attributes: Getter & Setter, _knownDavService: Getter & Setter, … }
​
level: 0
​
uid: "***redacted***"
​
view: Object { _view: {…} }
​
<prototype>: Object { … }
core-common.js:1:10102
[DEBUG] uploader: Destination set 
Object { app: "uploader", uid: "***redacted***", level: 0, folder: {…} }
​
app: "uploader"
​
folder: Object { _data: Getter & Setter, _attributes: Getter & Setter, _knownDavService: Getter & Setter, … }
​
level: 0
​
uid: "***redacted***"
​
<prototype>: Object { … }
core-common.js:1:10102
[DEBUG] files: Fetched contents 
Object { app: "files", uid: "***redacted***", level: 0, dir: "/***redacted path***/Meeting Minutes", folder: {…}, contents: (3) […] }
​
app: "files"
​
contents: Array(3) [ {…}, {…}, {…} ]
​
dir: "/***redacted path***/Meeting Minutes"
​
folder: Object { _data: Getter & Setter, _attributes: Getter & Setter, _knownDavService: Getter & Setter, … }
​
level: 0
​
uid: "***redacted***"
​
<prototype>: Object { … }
core-common.js:1:10102
[DEBUG] files: Directory contents changed 
Object { app: "files", uid: "***redacted***", level: 0, view: {…}, folder: {…}, contents: (3) […] }
​
app: "files"
​
contents: Array(3) [ {…}, {…}, {…} ]
​
folder: Object { _data: Getter & Setter, _attributes: Getter & Setter, _knownDavService: Getter & Setter, … }
​​
__ob__: Object { shallow: false, mock: false, vmCount: 0, … }
​​
_attributes: 
​​
_children: 
​​
_data: 
​​
_knownDavService: 
​​
handler: 
​​
readonlyAttributes: 
​​
<get _attributes()>: function get()​​
<set _attributes()>: function set(t)​​
<get _children()>: function get()​​
<set _children()>: function set(t)​​
<get _data()>: function get()​​
<set _data()>: function set(t)​​
<get _knownDavService()>: function get()​​
<set _knownDavService()>: function set(t)​​
<get handler()>: function get()​​
<set handler()>: function set(t)​​
<get readonlyAttributes()>: function get()​​
<set readonlyAttributes()>: function set(t)​​
<prototype>: Object { … }
​
level: 0
​
uid: "***redacted***"
​
view: Object { _view: {…} }
​
<prototype>: Object { … }
​​
__defineGetter__: function __defineGetter__()
​​
__defineSetter__: function __defineSetter__()
​​
__lookupGetter__: function __lookupGetter__()
​​
__lookupSetter__: function __lookupSetter__()
​​
__proto__: 
​​
constructor: function Object()
​​
hasOwnProperty: function hasOwnProperty()
​​
isPrototypeOf: function isPrototypeOf()
​​
propertyIsEnumerable: function propertyIsEnumerable()
​​
toLocaleString: function toLocaleString()
​​
toString: function toString()
​​
valueOf: function valueOf()
​​
<get __proto__()>: function __proto__()
​​
<set __proto__()>: function __proto__()
```
</details>

**Comment by PW-RTR** [comment] 2024-07-19 08:13
We have the same issue after updating our production system to Nextcloud 29.0.4 and Group Folders 17.0.1
Strangely, we don't have this issue on our Test system with same Nextcloud and Group Folders version.

**Comment by Dennis1993** [comment] 2024-07-20 08:22
In our live system the same problem after the update to 29.0.4

![image](https://github.com/user-attachments/assets/c8e9ec82-e29f-4cce-a2fc-d452f658234c)

**Comment by XueSheng-GIT** [comment] 2024-07-20 14:39
Having the same issue on three instances with NC 29.0.4. Could also be a files issue.
Reminds me of https://github.com/nextcloud/groupfolders/issues/2527.

**Comment by solracsf** [comment] 2024-07-21 19:50
Cc @susnux since this can be related to recent code changes in breadcrumbs handling.

**Comment by pablorgzzz** [comment] 2024-07-22 11:35
I have detected 3 errors

1 - Group folder titles in breadcrumbs menu are incorrect

2 - In nextcloud 29.0.3 there was an option in the menu that said "group folders", that option is no longer there

3 - If I put any number as the name of a group folder in front of a word that occupies more length than the visibility space, the number does not appear

![13 01 59 - 01](https://github.com/user-attachments/assets/c468f3fb-36dd-4584-9e77-805946302c3a)
![13 15 47 - 03](https://github.com/user-attachments/assets/cede2329-b133-4f69-842b-d5cdf2ac4359)
![13 16 57 - 04](https://github.com/user-attachments/assets/c22667e7-b7a6-41a8-b454-f06691dd89d5)
![13 23 18 - 05](https://github.com/user-attachments/assets/c7443309-c0fa-42a9-be82-9b98c2964627)

**Comment by susnux** [comment] 2024-07-22 16:27
Partly fixed with https://github.com/nextcloud/server/pull/46690

But there is a backend issue here:
Groupfolders return the internal mountpoint id as the displayname instead of the mount point name.

**Closed** 2024-07-24 13:22 UTC
Labels: bug, 0. Needs triage

**Comment by pablorgzzz** [comment] 2024-07-24 15:34
> I have detected 3 issues
> 
> 1 - Group folder titles in breadcrumbs menu are incorrect
> 
> 2 - In nextcloud 29.0.3 there was an option in the menu that said "group folders", that option is no longer there
> 
> 3 - If I put any number as the name of a group folder in front of a word that occupies more length than the visibility space, the number does not appear
> 
> ![13 16 57 - 04](https://private-user-images.githubusercontent.com/170978184/350949899-c22667e7-b7a6-41a8-b454-f06691dd89d5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzQ3MDUsIm5iZiI6MTcyMTgzNDQwNSwicGF0aCI6Ii8xNzA5NzgxODQvMzUwOTQ5ODk5LWMyMjY2N2U3LWI3YTYtNDFhOC1iNDU0LWYwNjY5MWRkODlkNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQxNTIwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTVhNTExMjZmZDYyOWJkNjViMGRmNGE2ZmJmMGNkYWMwMDIzYmUwNTc1N2Q1ZTFiZGMzNzgzNDM3MzZmN2ZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7jMKAzOZdVpMv20eWlbPpuMbZz9KSN0PKnaM3QJr5R4) ![13 01 59 - 01](https://private-user-images.githubusercontent.com/170978184/350949884-c468f3fb-36dd-4584-9e77-805946302c3a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzQ3MDUsIm5iZiI6MTcyMTgzNDQwNSwicGF0aCI6Ii8xNzA5NzgxODQvMzUwOTQ5ODg0LWM0NjhmM2ZiLTM2ZGQtNDU4NC05ZTc3LTgwNTk0NjMwMmMzYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQxNTIwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjEyZWI0MzAwMjNjYzY5YTMxYWZjMTViZWEwMjQwY2FmNTE5MDI5MWI0NWRjZWQ1NjQxN2FjZmEwZWU4MzFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SQrqZ7sebZfUuDz9MyVs-OCx5KRjoF0XiBUIr0JRQD8) ![13 23 18 - 05](https://private-user-images.githubusercontent.com/170978184/350949905-c7443309-c0fa-42a9-be82-9b98c2964627.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzQ3MDUsIm5iZiI6MTcyMTgzNDQwNSwicGF0aCI6Ii8xNzA5NzgxODQvMzUwOTQ5OTA1LWM3NDQzMzA5LWMwZmEtNDJhOS1iZTgyLTliOThjMjk2NDYyNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQxNTIwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDYxYTI2ODg0YTI5ZWU1MjNhOWQ0MGNiYWNkYzVjMjNiZGRhNjk3NmE3NmNiYmI2OGEyY2I3ODk1NGZjMTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UaeuAWZJraTzXyV-50BAyYWHVQBod7e3OkhscEGZtDs) ![13 15 47 - 03](https://private-user-images.githubusercontent.com/170978184/350949892-cede2329-b133-4f69-842b-d5cdf2ac4359.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzQ3MDUsIm5iZiI6MTcyMTgzNDQwNSwicGF0aCI6Ii8xNzA5NzgxODQvMzUwOTQ5ODkyLWNlZGUyMzI5LWIxMzMtNGY2OS04NDJiLWQ1Y2RmMmFjNDM1OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQxNTIwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzJjYjE3NThhNzZmMzM5NGQwM2M0ZTA2OWM1MWZlOTg0N2I1MDdkZmVjYjdhNmI2YTNiODZjOTVhYmY4MTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zEq6qkGLFjTOS4qygl4c0GICBo6wTo7a708WzHY_ZAw)

The issues 2 and 3 are still there

**Comment by ostasevych** [comment] 2024-07-25 07:09
The same goes with 28.0.8

**Comment by solracsf** [comment] 2024-07-25 07:45
Confirmed that https://github.com/nextcloud/server/pull/46694 fixes this issue. 👍
