### ISSUE TITLE
Cannot modify header information (Sapi.php:132) NC 19.0.2 /20.0.1

### ISSUE THREAD

**Issue by dzi77** [nextcloud/groupfolders#1146] opened 2020-11-17 09:27 UTC
Hello, 
I'm opening here this topic as I strongly believe that the below error is related with Groupfolders plugin. I'm not receiving any error when I'm uploading any file on the local storage. Please check the below error output: 

> **Error:` Cannot modify header information - headers already sent by (output started at /var/www/html/nextcloud/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php#690**

We had also a long discussion on this topic: https://github.com/nextcloud/server/issues/22509

**Comment by pierreozoux** [comment] 2021-03-13 08:13
Dif you see any UI errors, or is it just a log that is worrying you?

**Comment by mmaridev** [comment] 2021-04-15 15:20
Probably related to #1445

**Comment by fschrempf** [comment] 2021-11-25 12:13
I assume this is a duplicate of #1445 and the issue is fixed now. If you think this is wrong please create a new issue. Thanks!

**Closed by fschrempf** 2021-11-25 12:13 UTC
Labels: bug, 0. Needs triage, error_log
