### ISSUE TITLE
Changed file IDs in Groupfolders

### ISSUE THREAD

**Issue by gzoritchak** [nextcloud/groupfolders#1468] opened 2021-04-27 10:27 UTC
We experienced the same issue mentioned here: 

https://help.nextcloud.com/t/changed-file-ids-in-groupfolders/91916

It's very annoying since we used a root spreadsheet to referenced a lot of internal documents. All links are now broken.

**Comment by fschrempf** [comment] 2021-04-30 08:37
@juliushaertl @icewind1991 Are the file ids meant to stay unchanged? If yes, this is a bug. If no there should be something in the docs that informs users about this. Personally I think it is a bug? What's your point of view?

**Comment by juliushaertl** [comment] 2021-05-17 15:16
Yes, file ids should remain unchanged and I haven't encountered such a behavior until now. Please fill out the issue template and it would be especially interesting if there is any groupfolder related errors in the logs. Might also be worth to check if there was any suspicious action like a delete or move during the time this occured in the access logs of the webserver.

**Comment by acsfer** [comment] 2021-05-25 07:31
Hi @juliushaertl there was nothing in the logs either about group folders or anything else. The problem faced by @gzoritchak has arrived at night, with little or no activity at all.

After investigation, at the SQL dump from 3h26am (nightly backup) & production at 13h43 the same day, we could obseve an ID 2281 and an ID 6208 for the same file, exposing this ID increment, respectivelly. There was nothing unusual in the webserver, database, php or nextcloud logs. Only things related to https://github.com/nextcloud/groupfolders/pull/1381 and https://github.com/nextcloud/groupfolders/pull/1472 essentially.

**Comment by SimJoSt** [comment] 2021-06-22 11:11
@juliushaertl when we encountered this, there was a bulk file ownership change on the server. The file ownerships were adjusted to match the ones used by the Nextcloud Docker image. Some files were previously owned by the root user and group.  
The change was made with `chown`.

**Comment by konfiot** [comment] 2021-07-08 09:35
Also experienced the same issue, we did a files:scan for manually imported files, and some file ids have changed in other group folders, maybe this has something to do with the ids changing

**Comment by freshdomi** [comment] 2021-08-19 14:12
we have the same problem after moving the data directory....
I have checked that in the table oc_filecache, entries are duplicated. Example below.. 

Have anyone a solution for this problem? 
Our current idea is that we replace the fileids of the new database with the old one... but if that will work...
would be great if someone has another idea that does not attack the DB... 

example: (same path but different fileid)

`MariaDB [nextcloud]> SELECT * FROM oc_filecache WHERE fileid=3485643;
+---------+---------+------------------------------------------------+----------------------------------+---------+-----------+----------+----------+----------+------------+---------------+-----------+-----          -------------+---------------+-------------+----------+
| fileid  | storage | path                                           | path_hash                        | parent  | name      | mimetype | mimepart | size     | mtime      | storage_mtime | encrypted | unen          crypted_size | etag          | permissions | checksum |
+---------+---------+------------------------------------------------+----------------------------------+---------+-----------+----------+----------+----------+------------+---------------+-----------+-----          -------------+---------------+-------------+----------+
| 3485643 |     280 | __groupfolders/83/2021-09-10_ISAB-02/Upload AM | e9779aced0ca83c359098cc637dfebf1 | 3485639 | Upload AM |        2 |        1 | 61154122 | 1629368109 |    1629367052 |         0 |                          0 | 611e2f2d32386 |          31 |          |
+---------+---------+------------------------------------------------+----------------------------------+---------+-----------+----------+----------+----------+------------+---------------+-----------+-----          -------------+---------------+-------------+----------+
1 row in set (0.00 sec)

 

MariaDB [nextcloud]> SELECT * FROM oc_filecache WHERE fileid=1689517;
+---------+---------+------------------------------------------------+----------------------------------+---------+-----------+----------+----------+----------+------------+---------------+-----------+-----          -------------+---------------+-------------+----------+
| fileid  | storage | path                                           | path_hash                        | parent  | name      | mimetype | mimepart | size     | mtime      | storage_mtime | encrypted | unen          crypted_size | etag          | permissions | checksum |
+---------+---------+------------------------------------------------+----------------------------------+---------+-----------+----------+----------+----------+------------+---------------+-----------+-----          -------------+---------------+-------------+----------+
| 1689517 |       1 | __groupfolders/83/2021-09-10_ISAB-02/Upload AM | e9779aced0ca83c359098cc637dfebf1 | 1689457 | Upload AM |        2 |        1 | 48815043 | 1629124416 |    1629124416 |         0 |                          0 | 611a7740865db |          31 |          |
+---------+---------+------------------------------------------------+----------------------------------+---------+-----------+----------+----------+----------+------------+---------------+-----------+-----          -------------+---------------+-------------+----------+
1 row in set (0.00 sec)

 

MariaDB [nextcloud]>`

**Comment by juliushaertl** [comment] 2021-08-19 14:19
When moving the data directory to a different path this is expected as the existing filecache entries are not longer valid for the new location. For a possible workaround for that see https://help.nextcloud.com/t/howto-change-move-data-directory-after-installation/17170 however this is not a supported approach.

Note that execution of the scan command could cause creation of new filecache entries if Nextcloud is not able to map the existing entries to the path.

**Comment by freshdomi** [comment] 2021-08-19 14:39
after this instruction I have actually also proceeded... I have just not updated the oc_storage table... should be no longer necessary from version 13.1 I thought...
but now our problem is that I have moved the directory 3 days ago and the operation continued normally... today we have seen that the shares are no longer there...
Is this now a problem if I adjust the oc_storage afterwards?

**Comment by individual-it** [comment] 2023-02-16 06:08
Has anyone ever found the reason for this issue (besides moving the data folder)?

**Comment by OlJohnny** [comment] 2023-11-15 15:52
Still happening with our nextcloud installation on the currently latest version.

**Comment by juliushaertl** [comment] 2023-11-15 19:01
When reading related code a bit I might have a guess where this could potentially go wrong. I prepared a patch that could provide some logging in this case for the Nextcloud server itself.

```diff
index 3d5a2f098b2..2dadfe66d50 100644
--- a/lib/private/Files/Storage/Common.php
+++ b/lib/private/Files/Storage/Common.php
@@ -894,6 +894,9 @@ abstract class Common implements Storage, ILockingStorage, IWriteStreamStorage {

        public function getDirectoryContent($directory): \Traversable {
                $dh = $this->opendir($directory);
+               if ($dh === false) {
+                       throw new \Exception('opendir failed, not yielding any results');
+               }
                if (is_resource($dh)) {
                        $basePath = rtrim($directory, '/');
                        while (($file = readdir($dh)) !== false) {
```

If anyone who encounters this regularly could apply this patch to their instance and share the log results to see if this part is logged with a trace, this would be much appreciated.

**Comment by juliushaertl** [comment] 2023-11-16 10:52
Ok, opendir should still log an error already unless E_WARNING is suppressed via PHP config.

**Comment by max-nextcloud** [comment] 2024-01-11 11:09
I managed to reproduce the new fileids with some fairly simple steps:
* create a groupfolder, added some files, inspected the database
* move the `__groupfolders` folder to `__groupfolder`
* run `occ groupfolders:scan` for the folder in question
* move the folder back to `__groupfolders`
* run the scan again
* see new file ids, lost tags and shares and so on.

If this behavior persists I suspect that scans with a missing groupfolder are causing this bug.

We can prevent this by checking if the __groupfolders folder is present before running any scan. Otherwise the scan should err out.

We can also check if the folder for the groupfolder ( __groupfolders/123 ) in question is still present before performing a scan. If it's not we should inform the admin rather than dropping all the file cache entries.

So far I reproduced this on Nextcloud 23. I will try current master next.

**Comment by joshtrichards** [comment] 2024-11-08 18:03
Has anyone encountered this since nextcloud/server#43787? So basically that PR is in Server >=v28.0.4.

**Comment by max-nextcloud** [comment] 2024-11-08 19:42
Thanks for bringing this up here @joshtrichards - I remember that PR fixed the scenario I used to reproduce the behavior. So I think we could close this bug - but happy to wait to see if your question yields some response.

**Comment by juliusknorr** [comment] 2024-11-11 07:59
Let's close this, we can reopen if anyone reports this still being an issue.

**Closed by juliusknorr** 2024-11-11 07:59 UTC
Labels: bug, high, 1. to develop
