### ISSUE TITLE
A suggestion: I wanted a way to indicate where the files should be located.

### ISSUE THREAD

**Issue by SamuelAbrantes** [nextcloud/groupfolders#2987] opened 2024-06-02 23:02 UTC
A suggestion: I wanted a way to indicate where the files should be located. For example, I insert a new SAS HDD into my server, then I'll go and mount it in /mnt/extern1 Then when I create a group folder I can indicate which directory I want these files to find. This, together with the feature of setting usage limits per directory, will help a lot in expanding file storage and the usability of the APP.

I tried using a symbolic link to the point where I mounted the disk. I created the symbolic link in /var/www/html/nextcloud/data/__foldersgroup. However, because the use of the Symbolic Link was blocked, my idea of ​​simplifying this intention did not work. 

I need to do this effectively and safely. I didn't want to be forced to lower the NextCloud security of the company I work for so much for such functionality. It would be interesting if this could be set only when creating the folder, and from the moment it is blocked it guarantees that this symbolic link created by the Group Folders App will not be changed.

I used the translator, I don't speak English. Sorry if the idea was illegible, if you didn't understand, feel free to ask.

Thanks,
Samuel Abrantes.

**Comment by joshtrichards** [comment] 2024-09-11 23:31
> I insert a new SAS HDD into my server, then I'll go and mount it in /mnt/extern1 

You can do this without a symbolic link by mounting the storage device at the actual spot desired (e.g.`/var/www/html/data/__groupfolders`). 

In any case, duplicate of #87

**Closed by joshtrichards** 2024-09-11 23:31 UTC
Labels: enhancement, 0. Needs triage
