### ISSUE TITLE
add download permissions

### ISSUE THREAD

**Issue by LoveWaguan** [nextcloud/groupfolders#1852] opened 2022-01-04 03:04 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It controls whether folders or files can be downloaded

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/31790541/148004132-9b1909fa-d827-45bb-97d9-6b844fee740d.png)

**Comment by fschrempf** [comment] 2022-01-04 11:53
Closing as duplicate of #1199.

**Closed by fschrempf** 2022-01-04 11:53 UTC
Labels: enhancement, 0. Needs triage
