### ISSUE TITLE
Group Folders data counts against user quota

### ISSUE THREAD

**Issue by alden-david** [nextcloud/groupfolders#303] opened 2019-01-30 20:38 UTC
In NextCloud 15.0.2 with Group Folders 2.0.2 and using an S3 bucket as primary storage, group folder contents count against user quotas for every user who has access to it.

Uploads to the folder are limited by both folder and user quotas, so that 0 B user quotas prevent uploads even directly to the folder by that user. Large group folder data can leave users unable to upload even to other folders.

**Comment by richard-dg** [comment] 2019-02-16 18:51
Hi!
I'm on nextcloud 15.0.4 and group folders 2.0.2 and I don't have this issue. I set the user quota to 1 MB for every user but users can upload more to the group folder.

**Comment by alden-david** [comment] 2019-02-18 14:48
@richard-dg Are you using an S3 bucket as primary storage?

**Comment by richard-dg** [comment] 2019-02-18 19:34
No, I don't do that.

**Comment by MaxGitHubAccount** [comment] 2019-05-15 12:23
Hm in a full fletch perfect solution I guess the group folders would not count to the users quota but a group folder could either have an own quota or a quota per user - however a quota per user might also not make 100 % sense as users share data and even if you say the users data is the one he created other users could occupy his quota by editing his files. if you then say - ok ok - let's count the diffs of the file changes to the quota of the editor, people could remove things from your files transferring quota from one to another :D
I think counting quota to a users directory is the simplest and fairest solution - or alternatively having a switch to count or not count this group folder to a users data. (then you could give users read-only access to not counting folders e.g.)

**Comment by CarlSchwan** [comment] 2021-11-11 16:15
I can't reproduce. Please update :)

**Closed by CarlSchwan** 2021-11-11 16:15 UTC
Labels: bug, 0. Needs triage, integration, feature: quota
