### ISSUE TITLE
An unhandled exception has been thrown

### ISSUE THREAD

**Issue by re-vax** [nextcloud/groupfolders#396] opened 2019-04-25 07:30 UTC
An unhandled exception has been thrown:
ParseError: syntax error, unexpected '=' in /xdata/www/nextcloud/apps/groupfolders/lib/Command/ACL.php:150
Stack trace:
#0 /xdata/www/nextcloud/lib/composer/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/xdata/www/next...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('OCA\\GroupFolder...')
#2 [internal function]: spl_autoload_call('OCA\\GroupFolder...')
#3 /xdata/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(96): ReflectionClass->__construct('OCA\\GroupFolder...')
#4 /xdata/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(119): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\GroupFolder...')
#5 /xdata/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(453): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GroupFolder...')
#6 /xdata/www/nextcloud/lib/private/ServerContainer.php(116): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\GroupFolder...')
#7 /xdata/www/nextcloud/lib/private/Console/Application.php(219): OC\ServerContainer->query('OCA\\GroupFolder...')
#8 /xdata/www/nextcloud/lib/private/Console/Application.php(134): OC\Console\Application->loadCommandsFromInfoXml(Array)
#9 /xdata/www/nextcloud/console.php(95): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /xdata/www/nextcloud/occ(11): require_once('/xdata/www/next...')
#11 {main}

**Comment by fasterit** [comment] 2019-04-25 09:23
duplicate of #395

**Comment by TP75** [comment] 2019-04-28 15:37
This seems to be a  _PHP 7.0 with NC 14 & NC 15_ compatibilty issue.  See the [#395 comment by @nuvitong](https://github.com/nextcloud/groupfolders/issues/395#issuecomment-487271065).

@juliushaertl : Hopefully groupfolder 3.0.0 gets fixed and will be continued for running with PHP 7.0 in NC 15 environments.

**Comment by icewind1991** [comment] 2019-05-08 11:15
3.0.1 has been released for NC14/15 to fix this issue

**Closed by icewind1991** 2019-05-08 11:15 UTC

**Comment by TP75** [comment] 2019-05-09 12:01
Beware of #417 and apparently the more current version 3.0.2 should fix...

Thanks to @fasterit and certainly @icewind1991
