### ISSUE TITLE
Is there a recycler function?

### ISSUE THREAD

**Issue by lhxuji** [nextcloud/groupfolders#103] opened 2018-03-14 12:06 UTC
With nexctcloud, and enabled group files, but found deleted files in the group file do not know how to restore?

**Comment by hriekehof** [comment] 2018-03-19 09:36
I have the same issue #99 . It would be so great if someone from nextcloud could say something about this :)

**Comment by icewind1991** [comment] 2018-11-26 13:13
Closing as duplicate of #99

**Closed by icewind1991** 2018-11-26 13:13 UTC
