### ISSUE TITLE
Can not assign `admin` to groupfolder anymore

### ISSUE THREAD

**Issue by susnux** [nextcloud/groupfolders#2203] opened 2022-12-09 14:54 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Update to NC 25
2. Add group folder
3. try to assign folder to `admin` group

### Expected behaviour
Can assign `admin` to list of folder owners, like it was possible with NC24 (btw `admin` is member of group folders created before updating to NC25).

### Actual behaviour
Group `admin` is not shown as a option

### Server configuration

**Operating system:** Docker image

**Web server:** Docker image (Apache)

**Database:** MariaDB from Docker Image

**Nextcloud version:** 25.0.2

**Group folders version:** 13.1.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 24.0.7

**Where did you install Nextcloud from:** Docker

**Are you using external storage, if yes which one:** -

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### Web server error log
No interesting entries

**Comment by Sick-Andrew** [comment] 2022-12-11 18:16
We have the same issue, just on a slightly different server.
NC 25, GF 13.1.0

**Comment by miaulalala** [comment] 2022-12-29 16:16
Hi, you can still assign the groups via occ command:

`occ groupfolders:group YourFolderId admin`

 I'm not sure yet why the dropdown isn't showing the amin group any longer.

**Comment by christianlupus** [comment] 2023-01-05 17:47
This looks like a regression. There is a [filter function installed](https://github.com/nextcloud/groupfolders/blob/9a3256fa5fb38e219cb31a26c97626d966d1bbd8/src/settings/Api.ts#L53) that filters out the `admin` group. According to the comments that group should have been added at another location in code. Probably that was changed and the adding of the group was overseen.

The quick fix would be to drop the linked line. In the answer from the server, the admin group is present. So, it should work in theory. 

If desired, I can open a short PR with this change.

**Comment by stepka0815** [comment] 2023-02-15 18:17
I have the same issue, just on a slightly different server with both
NC 25.0.2 & GF 13.1.0 and 
NC 25.0.3 & GF 13.1.1

The problem did not exist with NC24.

Unfortunately, I can only administer NC via browser.

**Comment by susnux** [comment] 2023-02-15 18:20
> Unfortunately, I can only administer NC via browser.

As a workaround, but I do not know if that app still works, you could try to use [OCC web](https://apps.nextcloud.com/apps/occweb). Even if not officially supported it worked at least on NC24 for me.

**Comment by stepka0815** [comment] 2023-02-15 20:40
Thank you very much for the workaround tip with the "OCC Web" app. Even though the app officially only supports NC versions <= NC23, I was able to successfully assign the admin group to a group folder via browser using NC25.

**Comment by felag** [comment] 2023-03-01 16:19
I have bumped on such issue on NC 25.0.3 & GF and workaround 13.1.1 (as stated before).

Thanks for the `occ` command workaround.

I do not know if it is related, but a "new" `Admins` group has appeared on users page containing all users with admins' permission ("old" admin group).

**Comment by stepka0815** [comment] 2023-04-23 09:22
Is there a schedule to provide a solution for this problem? 
Because even with GF version 14.0.1 under NC 26 the problem still exists. 
And unfortunately under NC 26 the workaround via OccWeb app does not work anymore.
Thanks for any feedback!

**Comment by kboykov** [comment] 2023-04-24 10:41
Please fix this issue, because the group "admins" still cannot be assigned to group folders!

**Comment by susnux** [comment] 2023-04-25 20:02
> This looks like a regression. There is a [filter function installed](https://github.com/nextcloud/groupfolders/blob/9a3256fa5fb38e219cb31a26c97626d966d1bbd8/src/settings/Api.ts#L53) that filters out the `admin` group. According to the comments, that group should have been added at another location in code. Probably that was changed and the adding of the group was overseen.

`admin` is never added as a member group, so the query will fail here: https://github.com/nextcloud/groupfolders/blob/58710e7fe76e0ef3da8b6c89a83cd06cabefc010/lib/Folder/FolderManager.php#L501 which is called by https://github.com/nextcloud/groupfolders/blob/58710e7fe76e0ef3da8b6c89a83cd06cabefc010/lib/Folder/FolderManager.php#L713

I guess it should have been added by `createFolder` / `addFolder` (controller or manager)?

**Comment by stepka0815** [comment] 2023-04-30 15:26
Thank you for your detailed explanations.

Unfortunately, I have only a rudimentary understanding of the code and 
can not clearly classify to which NC component it exactly belongs. 
Therefore the 2 following questions:
- In which NC component (app if any) is the problem?
- Where should I address the problem so that those who can also solve it 
become aware of it?

Thanks for answers!


Am 25.04.2023 um 22:03 schrieb Ferdinand Thiessen:

**Comment by stepka0815** [comment] 2023-04-30 15:37
Many thanks for your detailed explanations but especially for placing the problem where it seems it can be solved.

**Closed** 2023-05-01 15:47 UTC
Labels: bug, 0. Needs triage, regression
