### ISSUE TITLE
Moving files requires "delete" permission

### ISSUE THREAD

**Issue by awesome-manuel** [nextcloud/groupfolders#859] opened 2020-04-07 10:56 UTC
When using ACLs in group folders I cannot decline "delete" without also preventing any moves or renames, since those are practically delete+create.

But regarding ACLs, moving or renaming a files is far from being as dangerous as deleting a file.

**Comment by susnux** [comment] 2024-08-07 13:52
Moving is just a composite of `copy the file` and `remove the original`, so a composite of `create` and `delete`.

(some storages might have only one operation for this, but that is not guaranteed)

**Comment by awesome-manuel** [comment] 2024-08-12 08:47
@susnux that's what I stated in the original post already. Still from a usage point of view it's desireable to allow users to move/rename files but disallow to delete files.

**Comment by provokateurin** [comment] 2024-09-17 19:17
Duplicate of https://github.com/nextcloud/groupfolders/issues/1646.

**Closed by provokateurin** 2024-09-17 19:17 UTC
Labels: enhancement, low, 0. Needs triage, feature: acl
