### ISSUE TITLE
Group Folders quota information

### ISSUE THREAD

**Issue by rmsmgaspar** [nextcloud/groupfolders#3029] opened 2024-06-26 15:59 UTC
Hi,
I'm using Group Folders for some stuff, therefore when I have the need for larger data movement, the quota applied is exceeded, but I don't have the visibility before, is there the possibility to implement a quota information in the group folder?
Thanks so much for your work.

**Comment by joshtrichards** [comment] 2024-09-12 18:39
Duplicate of #1736 (admin) or #44 (user). Subscribe and/or upvote and/or comment on those issues if they're of interest.

**Closed by joshtrichards** 2024-09-12 18:39 UTC
Labels: enhancement, 0. Needs triage
