### ISSUE TITLE
activities are not detected

### ISSUE THREAD

**Issue by mc9625** [nextcloud/groupfolders#77] opened 2017-11-29 08:15 UTC
The users activities in a groupfolder are not recorder in the activity log.

**Comment by hriekehof** [comment] 2017-11-29 14:00
have the same problem here. Would be nice if activities and versioning would work in group folders

**Comment by icewind1991** [comment] 2017-11-30 16:00
Duplicate of https://github.com/nextcloud/groupfolders/issues/70

**Closed by icewind1991** 2017-11-30 16:00 UTC
