### ISSUE TITLE
Comments listing fails to load if file is inside a group folder

### ISSUE THREAD

**Issue by avvertix** [nextcloud/groupfolders#1500] opened 2021-05-18 14:48 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

1. Create a group folder named "Test-Group-Folder"
2. Create a sub folder, e.g. "Test subfolder"
2. Add a file in the sub-folder, e.g. "Test_filename.docx"
3. Click on the three dots menu (or right click) on the file and chose details and then click the comments sections
4. add a comment
5. close the sidebar and refresh the page
6. an icon with the unread comments count should show up
7. click on that icon and the sidebar will open with a message "Error while loading the file data"

![image](https://user-images.githubusercontent.com/5672748/118668587-4e180680-b7f5-11eb-9c4f-6811c6acac65.png)

### Expected behaviour

The sidebar loads properly and the comments are listed

### Actual behaviour

The error is displayed and the request seems to note take into account that the file is in a folder and not in the root of the user.

I tried also to reproduce the problem in a normal folder and in a shared folder and the behavior was correct. The error only happened in the group folder so that's why I'm posting here the bug report.

### Server configuration

**Operating system:** Linux 4.19.0-8-amd64 x86_64 in Docker container on Debian 10

**Web server:** Apache behind Traefik reverse proxy

**Database:** MySQL 10.5.9

**PHP version:** 7.4.16

**Nextcloud version:** 21.0.1 using official Docker image

**Group folders version:** 9.0.1

<details>
<summary>Screenshot of the version number</summary>

![image](https://user-images.githubusercontent.com/5672748/118672734-c207de00-b7f8-11eb-97c5-6dacf7b61e3f.png)

</details>

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** Docker official Nextcloud image

**Are you using external storage, if yes which one:** no, only local storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Edge 92.0.884.2 and Chrome  90.0.4430.212

**Operating system:** Windows 10

### Logs

I'm including only browser related log entries because on the web server ones shows exactly the request as performed by the browser and the Nextcloud log do not show relevant entries.

#### Browser log

Javascript console log for a **failed request**

```
xhr.js:177 PROPFIND https://cloud.ithen.eu/remote.php/dav/files/user/Test_filename.docx 404
(anonymous) @ xhr.js:177
e.exports @ xhr.js:13
e.exports @ dispatchRequest.js:50
Promise.then (async)
c.request @ Axios.js:61
(anonymous) @ bind.js:9
(anonymous) @ FileInfo.js:26
...

Sidebar.vue:409 Error while loading the file data Error: Request failed with status code 404
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.d.onreadystatechange (xhr.js:62)
(anonymous) @ Sidebar.vue:409
...
Sidebar.vue:411 Uncaught (in promise) Error: Error: Request failed with status code 404
    at Sidebar.vue:411
...
```

The network tab shows the 404 not found entry with this result in the body

```
https://domain.eu/remote.php/dav/files/user/Test_filename.docx
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name //Test_filename.docx could not be located</s:message>
</d:error>
```

In case of a successful request to load the file sidebar the request has this form

```
https://domain.eu/remote.php/dav/files/user/Test-Group-Folder/Test%20subfolder/Test_filename.docx
```

which returns a positive response

**Comment by fschrempf** [comment] 2021-11-10 15:41
I can't reproduce this with latest master (nextcloud/server@586cc9b, ccd8e4e) and therefore assume this is fixed if no one objects in the near future.

**Comment by fschrempf** [comment] 2021-11-22 14:18
Closing this as explained above. Please reply, reopen or create a new issue if this problem persists. Thanks!

**Closed by fschrempf** 2021-11-22 14:18 UTC
Labels: bug, needs info, 0. Needs triage
