### ISSUE TITLE
drag n drop not working for groupfolders

### ISSUE THREAD

**Issue by diemelone** [nextcloud/groupfolders#1469] opened 2021-04-27 10:52 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install NC 21 and Groupfolders 9.0.1
2. Create a groupfolder with all permissions for you
3. Create a folder inside the gf
4. Drag n drop files into the subfolder without opening it

### Expected behaviour
Files should be uploaded into the subfolder as they usually do in every other folder

### Actual behaviour
files are not uploaded, instead a spinning circle and a line of text appear ("one file is beeing uploaded")
This stays like this for ever, even >1kb textfiles are not uploaded. Uploading via drag n drop while having the folder open is no problem. It is more or less the reverse of this: https://github.com/nextcloud/server/issues/16238#issuecomment-508627719
![grafik](https://user-images.githubusercontent.com/46229652/116227856-e0783d80-a754-11eb-883d-a27f99a87c0e.png)

### Server configuration

**Operating system:**
 Linux, distribution and version unkown
**Web server:**
unknown
**Database:**
MariaDB 10.5.8
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
21.0
**Group folders version:**
9.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
webhoster
**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
no
### Client configuration
**Browser:**
firefox and edge, most recent updates
**Operating system:**
win 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
i have no access to that
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
no new log created
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by fschrempf** [comment] 2021-11-10 15:33
I can't reproduce this with latest master (nextcloud/server@586cc9bcbc3a2c659d241cf82a538326aaeb3b1d, ccd8e4e5d990b41d0b6f098b9a11749ff5f38b1d) and therefore assume this is fixed if no one objects in the near future.

**Comment by fschrempf** [comment] 2021-11-22 14:22
Closing this as explained above. Please reply, reopen or create a new issue if this problem persists. Thanks!

**Closed by fschrempf** 2021-11-22 14:22 UTC
Labels: bug, needs info, 0. Needs triage
