### ISSUE TITLE
missing permission settings for subfolders in sharing dialog

### ISSUE THREAD

**Issue by 32kv** [nextcloud/groupfolders#2171] opened 2022-11-04 12:14 UTC
I have configured group folders in NC 24. The setup for those I have set groups and advanced permissions. After that I created a lot of subfolders. Each subfolder got his own permissions which was accessible of the sharing details.

After updating to NC 25 and group folder 13, the subfolder share details no longer have the permission setting. However, the settings I had previously made in NC 24 are still applied to the users.

**Comment by fschrempf** [comment] 2022-11-04 14:26
@32kv Please use the issue template and look for existing issues before you open a new one! Closing as duplicate of https://github.com/nextcloud/groupfolders/issues/2148.

**Closed by fschrempf** 2022-11-04 14:26 UTC
Labels: bug, 0. Needs triage
