### ISSUE TITLE
$path is a integer (versions)

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/groupfolders#1023] opened 2020-08-25 16:23 UTC
Same issue here... (also groupfolders)

<details>
<summary>JSON-Object:</summary>

```json
{"reqId":"xEIL38IsJazQ0iUo73FZ","level":3,"time":"2020-08-24T16:40:05+00:00","remoteAddr":"[redacted]","user":"server","app":"no app in context","method":"PUT","url":"/remote.php/dav/files/server/[redacted]","message":{"Exception":"LogicException","Message":"$path is a integer: 45314","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","line":63,"function":"normalizePath","class":"OC\\Files\\Node\\Node","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","line":138,"function":"getFullPath","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php","line":96,"function":"get","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/var/www/nextcloud/apps/files_versions/lib/Versions/VersionManager.php","line":93,"function":"createVersion","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->"},{"file":"/var/www/nextcloud/apps/files_versions/lib/Storage.php","line":207,"function":"createVersion","class":"OCA\\Files_Versions\\Versions\\VersionManager","type":"->"},{"file":"/var/www/nextcloud/apps/files_versions/lib/Hooks.php","line":61,"function":"store","class":"OCA\\Files_Versions\\Storage","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Hook.php","line":110,"function":"write_hook","class":"OCA\\Files_Versions\\Hooks","type":"::"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":381,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":162,"function":"emitPreHooks","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1143,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":515,"function":"updateFile","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":320,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Files/Node/Node.php","Line":307,"CustomMessage":"--"},"userAgent":"curl/7.68.0","version":"19.0.1.1","id":"5f43ed65cf231"}
```

</details>

<details>
<summary>Stacktrace</summary>

```
LogicException: $path is a integer: 45314
/var/www/nextcloud/lib/private/Files/Node/Folder.php - line 63:
OC\Files\Node\Node->normalizePath()
/var/www/nextcloud/lib/private/Files/Node/Folder.php - line 138:
OC\Files\Node\Folder->getFullPath()
/var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php - line 96:
OC\Files\Node\Folder->get()
/var/www/nextcloud/apps/files_versions/lib/Versions/VersionManager.php - line 93:
OCA\GroupFolders\Versions\VersionsBackend->createVersion()
/var/www/nextcloud/apps/files_versions/lib/Storage.php - line 207:
OCA\Files_Versions\Versions\VersionManager->createVersion()
/var/www/nextcloud/apps/files_versions/lib/Hooks.php - line 61:
OCA\Files_Versions\Storage::store()
/var/www/nextcloud/lib/private/legacy/OC_Hook.php - line 110:
OCA\Files_Versions\Hooks::write_hook()
/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php - line 381:
OC_Hook::emit()
/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php - line 162:
OCA\DAV\Connector\Sabre\File->emitPreHooks()
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1143:
OCA\DAV\Connector\Sabre\File->put()
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 515:
Sabre\DAV\Server->updateFile("*** sensiti ... *")
/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:
Sabre\DAV\CorePlugin->httpPut()
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:
Sabre\DAV\Server->emit()
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:
Sabre\DAV\Server->invokeMethod()
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:
Sabre\DAV\Server->start()
/var/www/nextcloud/apps/dav/lib/Server.php - line 320:
Sabre\DAV\Server->exec()
/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:
OCA\DAV\Server->exec()
/var/www/nextcloud/remote.php - line 167:
require_once("/var/www/ne ... p")
```

</details>

_Originally posted by @Pingger in https://github.com/nextcloud/server/issues/19010#issuecomment-679243257_

**Comment by Pingger** [comment] 2020-08-25 18:00
Thanks, but now you can go and close it here because of #907 please use the search before opening duplicate issues...

**Comment by juliushaertl** [comment] 2020-08-25 18:12
Same error message but this is a different issue in the code

**Comment by Pingger** [comment] 2020-08-26 01:08
> 
> 
> Same error message but this is a different issue in the code

while it might be a different location in the code of groupfolders, it is still caused by the same 2 lines in the Files module in the actual nextcloud/server repository...

**Closed** 2020-09-01 10:12 UTC
Labels: 1. to develop, bug
