### ISSUE TITLE
Solved (GF 4.0.2): GF 4.0.1: Can't open documents within groupfolder with onlyoffice (since update 4.0.0->4.0.1)

### ISSUE THREAD

**Issue by jpbraun** [nextcloud/groupfolders#443] opened 2019-05-23 12:07 UTC
NC 16: I can't open OnlyOffice documents in groupfolders. I had no problems with GF 4.0.0

**Comment by tikoflano** [comment] 2019-05-23 13:47
I'm having the same problem with uploaded documents. I can open the ones created directly from NC though.

The error log shows:

> Error: Call to a member function getUID() on null

**Comment by jpbraun** [comment] 2019-05-27 08:34
This is a serious problem for us. When will it be fixed?

**Comment by jpbraun** [comment] 2019-05-27 14:23
Thank you for fixing the problem.

**Comment by thecube13** [comment] 2019-06-12 11:01
Can't open documents within groupfolder with Read Only wrights. GF 4.0.2 ((
In out.log:
Error: Error response: statusCode:404 ;body:
{"message":"Files not found"}

**Comment by psyk3d** [comment] 2019-11-13 13:13
is it wierd that I am experiencing the same issue on 5.0.4?

**Comment by pierreozoux** [comment] 2021-03-14 22:43
can't reproduce so I'll close it.

feel free to reopen

**Closed by pierreozoux** 2021-03-14 22:43 UTC
Labels: 0. Needs triage
