### ISSUE TITLE
Start/Home directory/folder #question

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/groupfolders#695] opened 2019-12-14 12:03 UTC
Users logging in and only see one folder, the orgafolder. Up to now everything is within this folder. So I want to start their user experience within this folder. How to do that?

The reason why I'm not mv everything of this folder to first level is that it could happen, that we gonna have another organisation on the nc, so I don't wanna mix that up.

**Comment by pierreozoux** [comment] 2021-03-14 22:41
duplicate of #757

**Closed by pierreozoux** 2021-03-14 22:41 UTC
Labels: 0. Needs triage
