### ISSUE TITLE
Creating New Files

### ISSUE THREAD

**Issue by morgan2233** [nextcloud/groupfolders#1101] opened 2020-11-03 04:22 UTC
**Server**
Operating System: CloudLinux 7
Web Server: Apache
Database: MySQL
PHP: 7.4
Nextcloud: 20.0.1

**Client**
OS: Windows 10
Browser: Edge Chromium

When I try and create a new file in a group folder, the following errors appear in the log and of course, the file is not created

Error 1:

`Sabre\DAV\Exception: path needs to be relative to the system wide data folder and point to a user specific file`

Error 2:

`Error: Cannot modify header information - headers already sent by (output started at /home/kohinoor/cloud.kohinoorltd.co.uk/3rdparty/sabre/http/lib/Sapi.php:132) at /home/kohinoor/cloud.kohinoorltd.co.uk/apps/dav/lib/Connector/Sabre/File.php#691`

Error 3:

`Error: Cannot modify header information - headers already sent by (output started at /home/kohinoor/cloud.kohinoorltd.co.uk/3rdparty/sabre/http/lib/Sapi.php:132) at /home/kohinoor/cloud.kohinoorltd.co.uk/apps/dav/lib/Connector/Sabre/File.php#691`

Error 4:

`Error: Cannot modify header information - headers already sent by (output started at /home/kohinoor/cloud.kohinoorltd.co.uk/3rdparty/sabre/http/lib/Sapi.php:132) at /home/kohinoor/cloud.kohinoorltd.co.uk/apps/dav/lib/Connector/Sabre/File.php#691`

If I try to create a file such as test.mb, it says it failed to create, however, if I try again it says it already exists and magically the file is there.

**Comment by pierreozoux** [comment] 2021-03-13 08:22
Duplicate of #1102

**Closed by pierreozoux** 2021-03-13 08:22 UTC
