### ISSUE TITLE
Trashbin cannot be cleared with group folder data

### ISSUE THREAD

**Issue by hriekehof** [nextcloud/groupfolders#314] opened 2019-02-11 15:31 UTC
I'm running NC 15.0.4 with the group folder plugin 2.0.2. At the moment i have the strange behavior. 

1. I delete some files in a group folder and they appear in the trash bin of every user which as access to the group folder. I can safely restore files from there.
2. When i try to empty the trash bin it seems to work in the first place but when i refresh the side. All files i deleted show up again. I can also still restore them if i want. It seems that it is not possible to empty the trashbin of group folder deleted files.
3. When i run trashbin:cleanup for all users. The files still appear in the trashbin

Has someone else experienced something like this ?

**Comment by hriekehof** [comment] 2019-02-11 15:55
Ok i have to add something. I recognized a minute ago that when i mark the file and folders one by one and delete empty the tashbin it seems to works. But when i use the mark all button in the top left it doesn't.

**Comment by PpaiSanchez** [comment] 2019-03-14 16:39
Same here

**Comment by rerobins** [comment] 2019-05-22 15:57
This appears to be because the call that is made to delete all of the files is different than multi-selected files.  For deleting all trashed files, a DAV DELETE request is sent with the trash path, and multi-selected deletes each file individually.  

It appears that if the deleteAll call in TrashBin.php is returning if there isn't a trash bin path defined for the user, which is preventing the code from advancing to part where the deleteAll event is fired off.  Adding a non-group folder file and deleting it creates this trashbin directory and allows progress to move on.
https://github.com/nextcloud/server/blob/49e161d1ad9f7de42bdc5addae3fe0b2541d09cf/apps/files_trashbin/lib/Trashbin.php#L497

This doesn't actually fix the issue, but does allow us to get to the code where the deleteAll event is fired off.  It appears that GroupFolders should subscribe to the event: 

```php
		\OC_Hook::emit('\OCP\Trashbin', 'deleteAll', array('paths' => $filePaths));
```
(From: https://github.com/nextcloud/server/blob/49e161d1ad9f7de42bdc5addae3fe0b2541d09cf/apps/files_trashbin/lib/Trashbin.php#L524)

and delete all of the files that are stored in the groupfiles trashbackend.  Note $filePaths is going to be an empty array because it is built off of the values that are stored in files trashbin.

NOTE: This is based on NextCloud 15 only.

**Comment by DBJRdev** [comment] 2019-08-21 18:52
I can confirm that the problem persists in NC 16.0.4 and Group folders 4.0.5

**Comment by ernolf** [comment] 2019-12-22 16:54
I have the problem, that a trashbin from one group folder is physically deleted (trashbin has been deleted manually on server file system level, I know, it was dumb)
`occ groupfolders:scan` does not scan the trashbin. I understand that scanning the trashbin for NEW files would be impossible, since they need the meta data from where they came from etc. but is there a way, to get those entries out of my mariadb database?
A scan mechanism that recognises the absence of files registered in trash, would that not be a good idea?
Who knows the mysql commands to do this job by hand or does there exist a how to somewhere out there?

Thanks a lot in advance for any answer :revolving_hearts:

**Comment by bastiencyr** [comment] 2020-04-29 11:17
Hello, 

I have a provisional solution to empty the trashbin. Do this : 
1. select the mark all button and suppress all (only files NOT in group folder will be removed)
2. select the mark all button again, and uncheck only one file on the list. 
3. Remove all files (except the one last file)
4. it works for me

Hoping it really works :)

**Comment by alexisberindei** [comment] 2020-05-06 22:03
Thank you @bastiencyr this workaround works for me.

**Comment by freiheitswolke-org** [comment] 2020-06-09 08:15
Hey,
we opened a bounty on this missing function.
Please spread the voice and contribute as you can:
https://www.bountysource.com/issues/69919948-tashbin-cannot-be-cleared-with-group-folder-data

**Comment by expert-geeks** [comment] 2020-10-17 02:26
Function to clear group folders trash has recently been added by [rullzer & juliushaertl](https://github.com/nextcloud/groupfolders/commit/6119b1e245c750667a14ae24cede9b25b2bff29f) (thanks guys!) 

`sudo -u www-data php /var/www/nextcloud/occ groupfolders:trashbin:cleanup`

**Comment by jothoma1** [comment] 2020-11-04 15:18
Really nice to have occ groupfolders:trashbin:cleanup
Thanks !

It will be great if we can specify a duration like only delete file older than 7 days

**Comment by ZeikoFr** [comment] 2020-11-15 18:58
Yes I agree, I proposed to link this new function with the parameter 'trashbin_retention_obligation' in this issue. Sadly i'm a really bad programmer and can't develop this myself....
#https://github.com/nextcloud/groupfolders/issues/345

**Comment by CarlSchwan** [comment] 2022-02-02 09:15
I believe this issue can be closed. From the original comment:

> 1. I delete some files in a group folder and they appear in the trash bin of every user which as access to the group folder. I can safely restore files from there.
> 2. When i try to empty the trash bin it seems to work in the first place but when i refresh the side. All files i deleted show up again. I can also still restore them if i want. It seems that it is not possible to empty the trashbin of group folder deleted files.

Works for me now locally with 200 items in my trash bin with both master and stable22

> 3.  When i run trashbin:cleanup for all users. The files still appear in the trashbin

Works with `sudo -u www-data ./occ groupfolders:trashbin:cleanup`. I don't think ` trashbin:cleanup --all-users` should also delete groupfolders trash as a groupfolders is explicitly not owned by a user. 

Additionally, points mentioned in this ticket about trash retentions have also been fixed recently and landed in NC 23.

Please fill free to reopen if you think I missed something :)

**Closed by CarlSchwan** 2022-02-02 09:15 UTC
Labels: bug, high, 1. to develop, workaround, feature: trashbin, bounty

**Comment by unsalkorkmaz** [comment] 2022-07-08 15:55
Why is this closed?
problem is still here

**Comment by punkyard** [comment] 2024-02-21 17:28
this worked for me:

empty all bins of all users:
`sudo -u www-data php /var/www/html/occ trashbin:cleanup --all-users`

empty groupfloder bins:
`sudo -u www-data php /var/www/html/occ groupfolders:trashbin:cleanup`

or go to the the folder of your NC installation and occ file (doesn't work if you can't access Command Line Interface) and run the commands
