### ISSUE TITLE
Personal files erased on sharing group folder with duplicate name

### ISSUE THREAD

**Issue by winstonford** [nextcloud/groupfolders#105] opened 2018-03-15 23:05 UTC
To recreate:

1. In personal files in web ui, or in webdav folder in Finder on macos, create a folder named danger.  Save an important file to it.

2. In group folders on web ui, create a folder also named danger.  Share it with a group of which you are a member.  

3. Important file disappears.

Appears that perhaps, when admin creates a group folder and shares it, if the name conflicts with a group member's personal folder, contents of personal folder may be be overwritten with empty folder.

**Comment by Nils160988** [comment] 2018-03-16 09:08
Duplicate of https://github.com/nextcloud/groupfolders/issues/18

**Comment by winstonford** [comment] 2018-03-16 15:17
Doh

**Comment by icewind1991** [comment] 2018-11-27 16:11
Closing as duplicate

**Closed by icewind1991** 2018-11-27 16:11 UTC
