### ISSUE TITLE
Improve sharing with existing folders

### ISSUE THREAD

**Issue by C0kkie** [nextcloud/groupfolders#2379] opened 2023-05-11 09:56 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Currently it's not possible to use existing folders to share them with others. I would like that it will be possible like in owncloud that you can create a folder and later add users/groups to it. Currently you need to do it in nextcloud via the admin page and in owncloud its more comfortable (i attached a image)

**Describe alternatives you've considered**
Not really a good alternative atm
![c0kkie_11-05-2023_11-55-22](https://github.com/nextcloud/groupfolders/assets/20169938/8fa827dd-7d1c-47d0-834d-d7fd2fd40df3)

**Comment by provokateurin** [comment] 2024-09-17 17:15
That's just sharing and not Groupfolders in Owncloud.
Duplicate of https://github.com/nextcloud/groupfolders/issues/612

**Closed by provokateurin** 2024-09-17 17:15 UTC
Labels: enhancement, 0. Needs triage
