### ISSUE TITLE
Error searching files by name if user do not have permissions to see one of the matching files

### ISSUE THREAD

**Issue by victor-solvethex** [nextcloud/groupfolders#1563] opened 2021-06-21 14:37 UTC
### Steps to reproduce

1. Create a group folder and set advanced permissions
2. Create more folders with files
3. Create some files with a matching pattern (ex. hello1.pdf, hello2.pdf, hello3.pdf) so we can search later by name 'hello'
4. Allow a user A to reading those files except at least 1
5. Search files on the files browser by name (ex. 'hello')  

### Expected behaviour
As user A, we should only see the files on which we have read permissions

### Actual behaviour
An error occurs and no files are shown

### Server configuration

**Operating system:** Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** PHP 7.3.27-1~deb10u1 

**Nextcloud version:** 21.0.2

**Group folders version:** 9.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** Source

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome & Firefox

**Operating system:** Ubuntu 20.10 & Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

We have no logs on the Apache server related to this error

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

<a href="https://gist.github.com/victor-solvethex/f038baaa1891c909651a0dc725199ba1">Nextcloud logs</a>

</details>

#### Browser log

<details>
<summary>Browser log</summary>

<a href="https://gist.github.com/victor-solvethex/52aba7a74763f6db42925be61eba0297">Browser logs</a>

</details>

**Comment by christian-callau** [comment] 2021-06-22 15:17
We needed this asap, so we made a temporary fix.

On the function OC\\Files\\Cache\\Wrapper\\CacheJail::getJailedPath()

```php
private function formatSearchResults($results) {
	return array_map(function ($entry) {
		$entry['path'] = $this->getJailedPath($entry['path'], $this->getGetUnjailedRoot());
		return $entry;
	}, $results);
}
```

We simply filtered the `$results` array to remove the entries that have null "path" property:

```php
private function formatSearchResults($results) {
	$results = array_values(array_filter($results, function ($entry) {
		return $entry['path'] !== null;
	}));
	return array_map(function ($entry) {
		$entry['path'] = $this->getJailedPath($entry['path'], $this->getGetUnjailedRoot());
		return $entry;
	}, $results);
}
```

And it's working just fine.

**Comment by JMoVS** [comment] 2021-11-04 12:04
@christian-callau Is there any chance your patch might be upstreamed or this issue fixed upstream? If that is an easy and acceptable patch, this might help! If I can help in the processs, let me know.

**Comment by CarlSchwan** [comment] 2021-11-26 15:01
Duplicate of #1605

**Closed by CarlSchwan** 2021-11-26 15:01 UTC
Labels: bug, 1. to develop, feature: acl, feature: search
