### ISSUE TITLE
Group Folder deletes data if you put a . (dot) in a sub-folder name

### ISSUE THREAD

**Issue by HealthCIO** [nextcloud/groupfolders#551] opened 2019-08-06 21:39 UTC

**Comment by wiswedel** [comment] 2019-08-07 03:51
@icewind1991 @juliushaertl 
Just reproduced this.
Applies to dot anywhere in a subfolder name.
Happens only on renaming a folder when already inside a group folder. Moving a folder with a dot in name from user storage into a group folder keeps the folder alive.

**Comment by juliushaertl** [comment] 2019-08-07 08:05
I cannot reproduce this with 4.0.5 anymore, as it should actually be fixed by https://github.com/nextcloud/groupfolders/pull/542

**Closed** 2019-08-12 06:46 UTC
Labels: backport-request, bug, high
