### ISSUE TITLE
15.2.0 not saving advanced permission rule

### ISSUE THREAD

**Issue by oFlyer** [nextcloud/groupfolders#2564] opened 2023-09-19 20:45 UTC
Hello!

Version 15.2.0 not saving advanced permission rule for user (delete rule) and reset after page reloaded. Can you help me?
thank you!

**Comment by XueSheng-GIT** [comment] 2023-09-21 10:44
Can you provide detailed steps how to reproduce (including the admin settings and users involved)? Maybe a screenshot of the issue? For me your issue is not clear.

**Comment by oFlyer** [comment] 2023-09-21 12:20
folder tree:

- folder (permissions for group Employees (employee 1, employee 2, etc...) - only write)
-- subfolder 1
-- subforder 2 (advanced permission for employee 1 - delete, share)

advanced permission for subfolder 2 not working

**Comment by XueSheng-GIT** [comment] 2023-09-21 17:23
That's by design, I assume:
https://github.com/nextcloud/groupfolders/#setting-advanced-permissions
> Denied permissions configured for the group folder itself cannot be overwritten to "allow" permissions by the advanced permission rules.

**Comment by XueSheng-GIT** [comment] 2023-09-23 09:02
@oFlyer does your install behave like described within the documentation? If yes, please close this issue. If not, please provide further info. Thanks.

**Comment by joshtrichards** [comment] 2024-09-11 17:33
Closing per above comments + no further info provided in 12 months.

**Closed by joshtrichards** 2024-09-11 17:33 UTC
Labels: bug, needs info, 0. Needs triage, feature: acl
