### ISSUE TITLE
Allow ACL Permissions don't overwrite Deny permission

### ISSUE THREAD

**Issue by emilianocapasso** [nextcloud/groupfolders#438] opened 2019-05-20 13:22 UTC
I have a problem with the granular permissions:

Using this configuration:
![image](https://user-images.githubusercontent.com/26569178/58024670-07627980-7b13-11e9-914c-21dbaea5359e.png)

and adding these permission in a subfolder:
![image](https://user-images.githubusercontent.com/26569178/58024604-d8e49e80-7b12-11e9-8829-55f3f563755e.png)

from the other side (the test group) I'm see this permissions instead
![image](https://user-images.githubusercontent.com/26569178/58024645-f74a9a00-7b12-11e9-95df-f08f76f3a355.png)

**Comment by Chartman123** [comment] 2019-05-23 21:59
I think that it's intended that Deny overrules Allow. But I also miss the possibility to stop the inheriting of permissions without having to deny them. It would be nice to be able to just not give the permissions without having to deny them.

**Comment by BoxedBrain** [comment] 2019-06-15 20:27
Any update on this? Having the same issue.

**Comment by icewind1991** [comment] 2019-06-17 14:43
Advanced permissions currently cannot allow permissions that are denied in the "normal" permissions.

To get the behaviour you have to allow the permissions to the group in the group settings and then deny them using advanced permissions on the root of the folder. You can then re-allow the permission for any child folder

**Comment by emilianocapasso** [comment] 2019-06-17 15:46
looks like it works in this way, not sure if it's intended or it's just a workaround

**Comment by miketranagfa** [comment] 2019-09-10 17:47
> Advanced permissions currently cannot allow permissions that are denied in the "normal" permissions.
> 
> To get the behaviour you have to allow the permissions to the group in the group settings and then deny them using advanced permissions on the root of the folder. You can then re-allow the permission for any child folder

I tried this but it's not working.

In the "Settings > Group folder" setup I added the groups with read access.  Then I went to the root folder and clicked on the share icon.  I disabled read access for a group using advanced permission rules and then further down the tree, I enabled the read permission, but the users in the group could not see that folder.

**Comment by icewind1991** [comment] 2019-09-17 16:42
If a user doesn't have read permissions on a folder there is no way for him to see and of the contents inside of it, and thus adding read permissions back in a subfolder is useless since the user will never be able to reach the subfolder in the first place

**Comment by fri-sch** [comment] 2019-09-27 18:25
@miketranagfa I think you're right. It doesn't work the way @icewind1991 describes it. I just tried to do the same and the problem is just as described.

Even if the user has full access in the "normal" permission settings, it is not possible to overwrite a "deny" further up the directory tree with an "allow" further down in the tree of the "advanced permissions".

**Comment by anjoze** [comment] 2019-09-30 15:39
Same problem with me

**Comment by pgassmann** [comment] 2019-10-01 17:26
> If a user doesn't have read permissions on a folder there is no way for him to see and of the contents inside of it, and thus adding read permissions back in a subfolder is useless since the user will never be able to reach the subfolder in the first place

This would be a very useful feature to have. I expected, that I can add read permission on a subfolder and the recipient would then see the same path to that subfolder instead of having the subfolder now directly in his home folder.
My use case: Groupfolder for `IT-Department`, but i'd like to share the `Accounting` subfolder to another person without giving that person read access for the whole IT-Department groupfolder, but see that its `IT-Department/Accounting`
Other example:
Groupfolder `Photos`. Subfolders `Switzerland/Youth` `Switzerland/Children` and `Germany/Youth`, now a photographer should have access to the Youth Photos of Switzerland and Germany, but not to the `Children` Photos. If I share the Youth folder directly, he will have two "Youth" folders (or a conflict) in his Home-Folder. 

Would this be possible to implement? Or add an option to "Share with original Path".

**Comment by emilianocapasso** [comment] 2019-10-04 14:12
agree with @pgassmann, this behaviour cause our clients (and internal team) with different levels of access a lot of problems.

**Comment by wiswedel** [comment] 2019-10-23 12:22
> @icewind1991:
> 
> > If a user doesn't have read permissions on a folder there is no way for him to see and of the contents inside of it, and thus adding read permissions back in a subfolder is useless since the user will never be able to reach the subfolder in the first place
> 
> This would be a very useful feature to have. I expected, that I can add read permission on a subfolder and the recipient would then see the same path to that subfolder instead of having the subfolder now directly in his home folder.
> My use case: Groupfolder for `IT-Department`, but i'd like to share the `Accounting` subfolder to another person without giving that person read access for the whole IT-Department groupfolder, but see that its `IT-Department/Accounting`
> Other example:
> Groupfolder `Photos`. Subfolders `Switzerland/Youth` `Switzerland/Children` and `Germany/Youth`, now a photographer should have access to the Youth Photos of Switzerland and Germany, but not to the `Children` Photos. If I share the Youth folder directly, he will have two "Youth" folders (or a conflict) in his Home-Folder.
> 
> Would this be possible to implement? Or add an option to "Share with original Path".

@pgassmann 
What you describe is something different than the original topic of this issue. Could you please open a new issue for your request?

**Comment by pgassmann** [comment] 2019-10-23 13:55
@wiswedel @fri-sch @emilianocapasso I created a new Issue with my thoughts on how I would like it to function. https://github.com/nextcloud/groupfolders/issues/655

**Comment by rmeissn** [comment] 2019-10-23 14:48
I just ran into the same problem and had to find this issue in order to understand the behaviour and how to achieve what I desired.

I vote for overwriting a "deny" further up the directory tree with an "allow" further down in the tree of the "advanced permissions".

My scenario is:
We shared a folder with a group and denied delete rights on it.
Further down the tree of this shared folder is a folder for specific members of the group (subgroup). These subgroup members shall be able to freely use this folder (down in the tree), thus also delete files and folders inside of it.
I had to use the workaround

> @icewind1991 
> Advanced permissions currently cannot allow permissions that are denied in the "normal" permissions.
> 
> To get the behaviour you have to allow the permissions to the group in the group settings and then deny them using advanced permissions on the root of the folder. You can then re-allow the permission for any child folder

to achieve my desired behaviour. This use case won't interfere with what #655 is about (read permission).

**Comment by olaldiko** [comment] 2020-01-21 10:40
Same issue here. We created a subfolder that denied access to the group allowed in the parent folder, but that had allowed permissions for some users that were also part of the denied group. The folder disappeared for those users. 
I upload an example of the permissions defined for the folder. The root folder has full permissions for the consortium group, and my user is part of the consortium group. Changing the order of the rule does not help:
![image](https://user-images.githubusercontent.com/1711272/72798128-aca19480-3c42-11ea-927d-c5e87db5bf1b.png)

**Comment by thomaslauria** [comment] 2020-09-10 18:46
I have the same problem here. 
As a possible solution just a new permission value "do not inherit / do nothing" could be added. 
![grafik](https://user-images.githubusercontent.com/2863545/92783822-643c1000-f3a6-11ea-803a-9bf7c28653d5.png)
So in the above scenario one could choose "do not inherit" which just gain no access but also to the forced deny which explicitly denies the access.
All other options allow/deny/inherit could just remain as they are.

**Comment by pierreozoux** [comment] 2021-03-15 13:23
@olaldiko looks like a different issue, please open a new one.

About the original issue, Ill close as a wontfix.

It is a design decision that deny restriction is higher. We wont fix it in the foreseable future.

If you come up with a ux idea on how to address this, feel free to open a new issue.

**Closed by pierreozoux** 2021-03-15 13:23 UTC
Labels: 0. Needs triage, acl, design, enhancement, ui
