### ISSUE TITLE
An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '100408-1656379206' for key 'oc_group_folders_versions.gf_versions_uniq_index'

### ISSUE THREAD

**Issue by Jsalas424** [nextcloud/groupfolders#2700] opened 2023-12-25 15:55 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Enable Group Folders

### Server configuration

**Operating system:**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

**Web server:**

**Database:**
```
Type: mysql
Version: 8.0.35
Size: 107.8 MB
```

**PHP version:**
```
Version: 8.1.25

Extensions: Core, date, libxml, openssl, pcre, zlib, bcmath, bz2, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gmp, json, iconv, intl, SPL, ldap, mbstring, pcntl, PDO, session, posix, Reflection, standard, SimpleXML, mysqlnd, exif, sysvsem, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, redis, Zend OPcache
```

**Nextcloud version:** (see Nextcloud admin page)
```
v27.1.3
```

**Group folders version:**
```
v15.3.2
```

**Updated from an older Nextcloud/ownCloud or fresh install:**
```
Fresh install, snap 
```

**Where did you install Nextcloud from:**
```
Ubuntu Snap
```

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
```
no
```

**Are you using encryption:** yes/no
```
no
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
```
no
```

#### MySQL error log

```
2023-12-25T15:45:47.876962Z 8249 [Warning] [MY-013360] [Server] Plugin mysql_native_password reported: ''mysql_native_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'
```

#### Web server error log
<summary>Web server error log</summary>

```
[core] Error: OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '100408-1656379206' for key 'oc_group_folders_versions.gf_versions_uniq_index' at <<closure>>

0. /snap/nextcloud/38457/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php line 328
   OC\DB\Exceptions\DbalException::wrap()
1. /snap/nextcloud/38457/htdocs/lib/public/AppFramework/Db/QBMapper.php line 137
   OC\DB\QueryBuilder\QueryBuilder->executeStatement()
2. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/Versions/VersionsBackend.php line 88
   OCP\AppFramework\Db\QBMapper->insert()
3. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 72
   OCA\GroupFolders\Versions\VersionsBackend->getVersionsForFile()
4. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 59
   OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()
5. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 43
   OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
6. /snap/nextcloud/38457/htdocs/lib/public/BackgroundJob/Job.php line 81
   OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run()
7. /snap/nextcloud/38457/htdocs/lib/public/BackgroundJob/TimedJob.php line 103
   OCP\BackgroundJob\Job->start()
8. /snap/nextcloud/38457/htdocs/lib/public/BackgroundJob/TimedJob.php line 93
   OCP\BackgroundJob\TimedJob->start()
9. /snap/nextcloud/38457/htdocs/cron.php line 152
   OCP\BackgroundJob\TimedJob->execute()

Caused by:

Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '100408-1656379206' for key 'oc_group_folders_versions.gf_versions_uniq_index' at <<closure>>

 0. /snap/nextcloud/38457/htdocs/3rdparty/doctrine/dbal/src/Connection.php line 1814
    Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert()
 1. /snap/nextcloud/38457/htdocs/3rdparty/doctrine/dbal/src/Connection.php line 1749
    Doctrine\DBAL\Connection->handleDriverException()
 2. /snap/nextcloud/38457/htdocs/3rdparty/doctrine/dbal/src/Connection.php line 1163
    Doctrine\DBAL\Connection->convertExceptionDuringQuery()
 3. /snap/nextcloud/38457/htdocs/lib/private/DB/Connection.php line 295
    Doctrine\DBAL\Connection->executeStatement()
 4. /snap/nextcloud/38457/htdocs/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php line 354
    OC\DB\Connection->executeStatement()
 5. /snap/nextcloud/38457/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php line 280
    Doctrine\DBAL\Query\QueryBuilder->execute()
 6. /snap/nextcloud/38457/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php line 326
    OC\DB\QueryBuilder\QueryBuilder->execute()
 7. /snap/nextcloud/38457/htdocs/lib/public/AppFramework/Db/QBMapper.php line 137
    OC\DB\QueryBuilder\QueryBuilder->executeStatement()
 8. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/Versions/VersionsBackend.php line 88
    OCP\AppFramework\Db\QBMapper->insert()
 9. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 72
    OCA\GroupFolders\Versions\VersionsBackend->getVersionsForFile()
10. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 59
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()
11. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 43
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
12. /snap/nextcloud/38457/htdocs/lib/public/BackgroundJob/Job.php line 81
    OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run()
13. /snap/nextcloud/38457/htdocs/lib/public/BackgroundJob/TimedJob.php line 103
    OCP\BackgroundJob\Job->start()
14. /snap/nextcloud/38457/htdocs/lib/public/BackgroundJob/TimedJob.php line 93
    OCP\BackgroundJob\TimedJob->start()
15. /snap/nextcloud/38457/htdocs/cron.php line 152
    OCP\BackgroundJob\TimedJob->execute()

Caused by:

Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '100408-1656379206' for key 'oc_group_folders_versions.gf_versions_uniq_index' at <<closure>>

 0. /snap/nextcloud/38457/htdocs/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php line 103
    Doctrine\DBAL\Driver\PDO\Exception::new()
 1. /snap/nextcloud/38457/htdocs/3rdparty/doctrine/dbal/src/Connection.php line 1153
    Doctrine\DBAL\Driver\PDO\Statement->execute()
 2. /snap/nextcloud/38457/htdocs/lib/private/DB/Connection.php line 295
    Doctrine\DBAL\Connection->executeStatement()
 3. /snap/nextcloud/38457/htdocs/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php line 354
    OC\DB\Connection->executeStatement()
 4. /snap/nextcloud/38457/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php line 280
    Doctrine\DBAL\Query\QueryBuilder->execute()
 5. /snap/nextcloud/38457/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php line 326
    OC\DB\QueryBuilder\QueryBuilder->execute()
 6. /snap/nextcloud/38457/htdocs/lib/public/AppFramework/Db/QBMapper.php line 137
    OC\DB\QueryBuilder\QueryBuilder->executeStatement()
 7. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/Versions/VersionsBackend.php line 88
    OCP\AppFramework\Db\QBMapper->insert()
 8. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 72
    OCA\GroupFolders\Versions\VersionsBackend->getVersionsForFile()
 9. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 59
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()
10. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 43
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
11. /snap/nextcloud/38457/htdocs/lib/public/BackgroundJob/Job.php line 81
    OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run()
12. /snap/nextcloud/38457/htdocs/lib/public/BackgroundJob/TimedJob.php line 103
    OCP\BackgroundJob\Job->start()
13. /snap/nextcloud/38457/htdocs/lib/public/BackgroundJob/TimedJob.php line 93
    OCP\BackgroundJob\TimedJob->start()
14. /snap/nextcloud/38457/htdocs/cron.php line 152
    OCP\BackgroundJob\TimedJob->execute()

Caused by:

PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '100408-1656379206' for key 'oc_group_folders_versions.gf_versions_uniq_index' at <<closure>>

 0. /snap/nextcloud/38457/htdocs/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php line 101
    PDOStatement->execute()
 1. /snap/nextcloud/38457/htdocs/3rdparty/doctrine/dbal/src/Connection.php line 1153
    Doctrine\DBAL\Driver\PDO\Statement->execute()
 2. /snap/nextcloud/38457/htdocs/lib/private/DB/Connection.php line 295
    Doctrine\DBAL\Connection->executeStatement()
 3. /snap/nextcloud/38457/htdocs/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php line 354
    OC\DB\Connection->executeStatement()
 4. /snap/nextcloud/38457/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php line 280
    Doctrine\DBAL\Query\QueryBuilder->execute()
 5. /snap/nextcloud/38457/htdocs/lib/private/DB/QueryBuilder/QueryBuilder.php line 326
    OC\DB\QueryBuilder\QueryBuilder->execute()
 6. /snap/nextcloud/38457/htdocs/lib/public/AppFramework/Db/QBMapper.php line 137
    OC\DB\QueryBuilder\QueryBuilder->executeStatement()
 7. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/Versions/VersionsBackend.php line 88
    OCP\AppFramework\Db\QBMapper->insert()
 8. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 72
    OCA\GroupFolders\Versions\VersionsBackend->getVersionsForFile()
 9. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 59
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()
10. /var/snap/nextcloud/38457/nextcloud/extra-apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 43
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
11. /snap/nextcloud/38457/htdocs/lib/public/BackgroundJob/Job.php line 81
    OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run()
12. /snap/nextcloud/38457/htdocs/lib/public/BackgroundJob/TimedJob.php line 103
    OCP\BackgroundJob\Job->start()
13. /snap/nextcloud/38457/htdocs/lib/public/BackgroundJob/TimedJob.php line 93
    OCP\BackgroundJob\TimedJob->start()
14. /snap/nextcloud/38457/htdocs/cron.php line 152
    OCP\BackgroundJob\TimedJob->execute()

at 2023-12-25T10:44:31+00:00
```

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by vasyugan** [comment] 2023-12-27 10:52
same here. I see this i.a. when running occ groupfolders:expire

**Comment by solracsf** [comment] 2024-01-03 11:11
Closing as duplicate of https://github.com/nextcloud/groupfolders/issues/2559
Please follow discussion there.

**Closed by solracsf** 2024-01-03 11:11 UTC
Labels: bug, 0. Needs triage
