### ISSUE TITLE
Argument #1 ($user) must be of type OCP\IUser, null given, called in …/groupfolders/lib/Mount/MountProvider.php on line 206

### ISSUE THREAD

**Issue by ludogre** [nextcloud/groupfolders#2489] opened 2023-07-25 14:43 UTC
Hi!

I've got a issue when I scan my groupfolders with the occ command `occ groupfolders:scan id_folder`:

> An unhandled exception has been thrown:
> TypeError: OCA\GroupFolders\ACL\ACLManagerFactory::getACLManager(): Argument #1 ($user) must be of type OCP\IUser, null given, called in …/groupfolders/lib/Mount/MountProvider.php on line 206 and defined in …/groupfolders/lib/ACL/ACLManagerFactory.php:37
> Stack trace:
> #0 …/groupfolders/lib/Mount/MountProvider.php(206): OCA\GroupFolders\ACL\ACLManagerFactory->getACLManager()
> #1 …/groupfolders/lib/Command/Scan.php(82): OCA\GroupFolders\Mount\MountProvider->getMount()
> #2…/3rdparty/symfony/console/Command/Command.php(298): OCA\GroupFolders\Command\Scan->execute()
> #3…/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run()
> #4…/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run()
> #5…/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
> #6…/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
> #7…/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
> #8…/console.php(100): OC\Console\Application->run()
> 

I've juste migrated my nextcloud server from version 22 to 27.

Can I try something to fix this issue?

Here is my configuration:

> 
> occ status
>   - installed: true
>   - version: 27.0.0.8
>   - versionstring: 27.0.0
>   - edition: 
>   - maintenance: false
>   - needsDbUpgrade: false
>   - productname: Nextcloud
>   - extendedSupport: false

Debian bookworm

> nginx -version
> nginx version: nginx/1.22.1

> php-fpm8.2 --version
> PHP 8.2.7 (fpm-fcgi) (built: Jun  9 2023 19:37:27)
> Copyright (c) The PHP Group
> Zend Engine v4.2.7, Copyright (c) Zend Technologies
>     with Zend OPcache v8.2.7, Copyright (c), by Zend Technologies

> psql --version
> psql (PostgreSQL) 15.3 (Debian 15.3-0+deb12u1)

**Comment by solracsf** [comment] 2023-07-26 08:11
Please do a **search before posting**, [this](https://github.com/nextcloud/groupfolders/issues?q=is%3Aissue+OCP%5CIUser%2C+null+given+is%3Aclosed) is a duplicate of duplicate of duplicate ...

**Closed by solracsf** 2023-07-26 08:11 UTC
Labels: bug, 0. Needs triage
