### ISSUE TITLE
Feature Request:  Define a different default user as admin for Group Folders

### ISSUE THREAD

**Issue by JB1985** [nextcloud/groupfolders#137] opened 2018-07-09 08:28 UTC
Hi,

I wish that it is possible to define a standard user as admin.

Thanks a lot!

**Comment by icewind1991** [comment] 2018-11-27 16:33
Closing as duplicate of https://github.com/nextcloud/groupfolders/issues/35

**Closed** 2018-11-27 16:34 UTC
