### ISSUE TITLE
Scan part of the group folder

### ISSUE THREAD

**Issue by oliu321** [nextcloud/groupfolders#1017] opened 2020-08-21 12:50 UTC
Hi, We are moving from pydio to nextcloud, we have the following use case which we found to be difficult to implement with nextcloud
1. We have jenkins jobs which builds binaries, then we ssh them to a network attached storage (say /mnt/nas/pydio/clientA/build-xxx/* - where * could be multiple files plus multiple subfolders, basically build results)
2. In Pydio we set up that network attached storage as workspaces (say workspace/group clientA map to /mnt/nas/pydio/clientA).
3. Then in the pydio GUI we can immediately see the build-xxx as a folder under clientA and all files there.

In nextcloud case, we set up group folder clientA, clientB etc (so it's easier to share to users, and those files actually don't belong to one particular user, but the any people in group clientA). Then we will have to scan the whole clientA group folder to let nextcloud know that build-xxx is there. Problem is that we may have thousands of build (like for 1 client the latest build is 2708 which means we have to archive build-1 to build-2708), scanning all of them is slow, as we know the next build result will only be build-2709, is it possible to ask nextcloud to only scan build-2709 subfolder under the clientA group folder?

Or is there any other way to solve this case? Thanks.

**Comment by flowzen1337** [comment] 2020-12-08 13:40
I guess I'm hanging on exact the same problem.... -> https://github.com/nextcloud/groupfolders/issues/1168

Do you already have any solution found for that case?

**Comment by pierreozoux** [comment] 2021-03-14 22:21
duplicate of #1168

**Closed by pierreozoux** 2021-03-14 22:21 UTC
Labels: 0. Needs triage
