### ISSUE TITLE
add group option to groufolder is missing

### ISSUE THREAD

**Issue by bc1000** [nextcloud/groupfolders#133] opened 2018-06-29 15:01 UTC
I just updated to groupfolders 1.2.1 (nextcloud 13.0.4) and created an additional new groupfolder. After it´s created, I can not adjust the groups for this folder. If I click in "edit" next to "none" in the groups column, there is no field to enter the groupname.

I can also no longer add a new group to existing groupfolders. There I see the actuall group und permission. I can only change remove group, but also no option to add a group.

**Comment by gtchm** [comment] 2018-06-29 15:44
I was about to write the same. I've noticed however that this only affects the GUI, as it is possible to edit the database to achieve the desired result.

**Comment by gtchm** [comment] 2018-06-29 15:46
@icewind1991 would you be so kind to revert back to 1.2.0 temporarly so I can finish a new deployment? Also, if this bug affects everyone I belive that the product is not functional if you can't add groups at all. Thank you

**Comment by gtchm** [comment] 2018-06-29 18:57
@bc1000 I've managed to find a deployment with 1.2.0, have reverted the code and it's working again. Please reply if you need code and instructions

**Comment by climber10** [comment] 2018-06-29 22:10
I have the same problem. Nextcloud is hosted by the provider. How can I install the previous version? The mistake is a big problem.

**Comment by bc1000** [comment] 2018-06-30 04:31
@gtchm would be nice and thank you very much. I will test next week when I am back in office.

**Comment by nguyenhuuhanhlam** [comment] 2018-06-30 13:23
same problem, missing groupfolder

**Comment by michael2z** [comment] 2018-06-30 15:07
@gtchm downgrading from 1.2.1 to 1.2.0 is working for me
@climber10 Replace apps/groupfolders with https://github.com/nextcloud/groupfolders/archive/v1.2.0.zip and then occ upgrade

**Comment by fillmodl** [comment] 2018-07-01 03:10
I have an on premise install, but am experiencing the same problem.

@michael2z ... I downgraded the code using the link you provided and ran occ upgrade.... the occ script then upgraded the code again and I'm back in the same boat as before.

**Comment by icewind1991** [comment] 2018-07-02 14:18
Can you post a screenshot how the ui looks for you, I can't reproduce this issue

**Comment by johndoe7000** [comment] 2018-07-02 15:57
Same problem for me. The screenshot from bc1000 above looks the same for me - nextcloud 12.0.7 on my side.
Using API I can add groups but not over gui.
@icewind1991 are you using a custom installation or the "nextcloud virtual appliance" based on ubuntu  16.04 or now 18.04?

**Comment by michael2z** [comment] 2018-07-02 16:31
![image](https://user-images.githubusercontent.com/15636119/42175565-50016558-7e15-11e8-8447-0b3177f10c3c.png)

**Comment by gtchm** [comment] 2018-07-02 18:30
Hi @icewind1991 I can provide you full access to a VM in case you need testing to reproduce the issue. OS is Debian 9.4, NC is 13.0.4

**Comment by Cracky5457** [comment] 2018-07-03 11:23
Same here, I update to 1.2.1 because the API for folder/folderId was not working in the previous one. And now the UI is broken. But I still can add group ( even group who not exist ) through the API

**Comment by icewind1991** [comment] 2018-07-03 12:29
Fixed with 1.2.2

**Closed by icewind1991** 2018-07-03 12:29 UTC

**Comment by Cracky5457** [comment] 2018-07-03 12:58
Works with my 13.0.2 nexcloud instance, don't works with my 13.0.4

**Comment by Adambean** [comment] 2019-05-07 17:56
This is also broken on OC 15.0.7 with Group Folders 2.0.4.
