### ISSUE TITLE
No notification email is sent when a file is uploaded into a group folder

### ISSUE THREAD

**Issue by Nils160988** [nextcloud/groupfolders#112] opened 2018-05-05 13:40 UTC
This is very similar to this issue (https://github.com/nextcloud/activity/issues/244) here, but now, it only affects files in groupfolders. The former issue has been closed and not reopened, so I thought it might be more an issue with the groupfolder app.

For references, this is a post I opened in the nextcloud-forum at first place. 

I checked it again with Nextcloud Version 13.0.2 now:

### Steps to reproduce
1. Create two users A and B, both in one group "Test"
2. Make sure user B has checked the box "New file or folder has been created" of the activity settings
3. As Administrator, create a groupfolder for group "Test"
4. Create or edit a file in the groupfolder (no matter which user).

### Expected behaviour
User A and B should receive a notification email which announces that a file has been uploaded/changed in the group folder

### Actual behaviour
No notification emails are sent.

## Server configuration detail

**Operating system:** Linux 4.4.0-042stab128.2 #1 SMP Thu Mar 22 10:58:36 MSK 2018 x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.0.34

**PHP version:** 7.0.28-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.2 - 13.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>List of activated apps</summary>

Enabled:
 - activity: 2.6.1
 - comments: 1.3.0
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - groupfolders: 1.2.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - polls: 0.8.1
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
       ***REMOVED SENSITIVE VALUE***
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "13.0.2.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_smtpmode": "sendmail",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "force_language": "de",
    "htaccess.RewriteBase": "\/",
    "logtimezone": "Europe\/Berlin",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "beta",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

No relevant log entries

**Comment by squalo80** [comment] 2018-06-12 13:52
Repost also on this issue.
On NextCloud 13.0.4 updated this morning i cannot see mail notification if any files or folders are create or updated INSIDE a shared folder.
Seems also that if you are inside a group and the folder is shared to the group instead the user you don't receive notification.

**Comment by terrar** [comment] 2018-06-14 07:23
Will something be coming here in the near future?
If the group folders remain without trash and notification I have to look for an other platform.
The current state is only limited usable.

**Comment by jacestk** [comment] 2018-08-02 08:26
Would be nice to get this enhancement. We are using Groups Folders for people services (because people are moving throught the organization and change services) to let files and common datas in place.
Only the user that has shared something in the folder receives the notification, that is completly useless :P

**Comment by jacestk** [comment] 2018-08-02 09:31
To get notifications, there is a solution: just add share in the file navigator and not in the admistration panel. use "fonctionnal groups".

**Comment by RuudschMaHinda** [comment] 2018-10-23 20:40
I actually had to go back. Which means less data privacy (in the way this one customer as it set up). But group folders are a very awesome thing for especially that. No need for an admin to actually create a folder on their account and then have them set up as group folders. Let alone being able to access all of them.
A technician should never have any need to access patient files, or easy undocumentable means to do so.

But alas, it's more than half a year. And for now I am fine with going back to the "old" way. Oh the trouble I got into! (my own fault on how I migrated, but still)

**Comment by joe-speedboat** [comment] 2019-03-28 11:11
> et notifications, there is a solution: just add share in the file navigator and not in the admistration panel. use "fonctionnal groups".
Thanks for the hint, but if you do that you have to ways:
- remove Group Folders and share the folders as Admin to the groups
     - then I loose quota for folder function?!
- keep "group folders" AND create an additional share of the "group folder" to the "group folder group"
     - then activity shows up, but I have two shares:
        - one from group folder
        - one from share I created to fix the notification issue
          eg: group1 AND group1 (2)

If this is true, that is nothing I can use in real live ... user support requests would flood the IT team :-(

Did I miss somehting?
Thanks for all the help!
Chris

**Comment by wiswedel** [comment] 2020-02-04 11:14
duplicate of https://github.com/nextcloud/groupfolders/issues/101

**Closed by wiswedel** 2020-02-04 11:14 UTC
